### ISSUE TITLE
Simple authentication when running in GAE + GCE (or locally via Cloud SDK)

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#102]
Ideally we can "figure out" the environment and "just use the right credentials".

Order of eval should be the same as Python:

1. Specific credentials provided in code
1. Specific credentials provided in env var
1. Credential available in the Cloud SDK's magic path
1. ~~GAE credentials (magically discovered)~~
1. GCE credentials (magically discovered)

**Comment by blowmage** [comment]
@jgeewax We already support 1 and 2, and I have code for 3. It looks to me that the "_magically discovered_" credentials will be supported in [google-auth-library-ruby](https://github.com/google/google-auth-library-ruby). I think it would make more sense to wait for google-auth-library-ruby to be available than to [duplicate that code](https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/compute_engine.rb) here. What do you think?

**Comment by blowmage** [comment]
I just saw that [google-api-client](https://rubygems.org/gems/google-api-client) and [googleauth](https://rubygems.org/gems/googleauth) were updated this morning. I'll update our dependency on those libraries and rework my changes to it.

**Comment by jgeewax** [comment]
We can't announce anything until we have all these things done, so it's up to you whether you want to wait for external feedback or duplicate code. I'm fine with waiting, but we should set a hard deadline where we decide to stop waiting........

**Comment by blowmage** [comment]
The code that would be duplicated was released this morning. My original comment was written last week but wasn't submitted until this morning.

**Comment by jgeewax** [comment]
OK great :)

**Comment by blowmage** [comment]
Google App Engine doesn't have a Ruby runtime so that will be skipped for now. Updating description.
