### ISSUE TITLE
datastore local development creation

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-ruby#107]
The user shouldn't have to update their code in order to run locally vs against production Datastore.

In particular, they should be able to call:

    dataset = Gcloud.datastore "my-project"

If `DATASTORE_HOST` is set, it should use that for the host. Otherwise, it should use the default host (googleapis.com)

Also, even as is it should always use `DATASTORE_HOST` and `DATASTORE_PROJECT`. There shouldn't be a `DEVSERVER_HOST` and `DEVSERVER_PROJECT`.

**Comment by blowmage** [comment]
@pcostell Please take a look at #108. Thanks!
