### ISSUE TITLE
Keyfile from environment variables

### ISSUE THREAD

**Issue by premist** [GoogleCloudPlatform/gcloud-ruby#109]
Do you have any plans to allow setting json key file from environment variables?

Right now I toss all credentials via environment variables, and gcloud ruby library is the only exception which requires json file to be placed somewhere in the filesystem.

**Comment by blowmage** [comment]
Currently Gcloud only supports the project identifier and keyfile path in environment variables. The path must point to an actual file.

```ruby
require "gcloud/datastore"

ENV["DATASTORE_PROJECT"] = "project-identifier"
ENV["DATASTORE_KEYFILE"] = "/path/to/keyfile.json"

@datastore = Gcloud.datastore
@entity = @datastore.find "Task", 123
```

Here is what I think you are asking for:

```ruby
require "gcloud/datastore"

ENV["DATASTORE_PROJECT"] = "project-identifier"
ENV["DATASTORE_KEYFILE_JSON"] = "{\"private_key_id\": \"...\", \"private_key\": \"...\", \"client_email\": \"...\", \"client_id\": \"...\", \"type\": \"...\"}"

@datastore = Gcloud.datastore
@entity = @datastore.find "Task", 123
```

Is that right?

**Comment by premist** [comment]
Yes, that's right. Or since JSON file contains string values, it would be possible if gcloud allows setting them separately via environment variable.
