### ISSUE TITLE
Update documentation look and feel

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#114]
Match the Gcloud site.

**Comment by jgeewax** [comment]
I believe this is complete now, right?

**Comment by blowmage** [comment]
The documentation is matching the look and feel, but #115 isn't merged yet, which is why I haven't closed this issue. There are still some issues around applying the template to previous releases that need to be resolved.

**Comment by blowmage** [comment]
I am pretty confident that the lastest changes address the look and feel of the site and documentation. When I get a thumbs up on the changes I'll close the remaining open issues.

**Comment by jgeewax** [comment]
After looking things over, I think we're in good shape for the goal of this issue (based on http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud.html)
