### ISSUE TITLE
Should we drop support for 1.9.3?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#117]
@blowmage says:

> Ruby 1.9.3 has reached end of life and will no longer get security fixes.
> 
> https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/
> 
> What are your thoughts on removing support for 1.9.3? We have a failing build on the pubsub branch because of a small incompatibility with 2.0.0 and 1.9.3 that I forgot to check for locally. The fix isn't difficult, but it makes me wonder how long Gcloud will support 1.9.3.

**Comment by jgeewax** [comment]
Does Ruby have a standard for how long libraries support a version after security fixes stop coming out? I'd expect that we should give it O(months) before officially stopping support -- particularly if the fixes aren't all that much effort.

**Comment by blowmage** [comment]
I am not aware of a standard for libraries supporting EOL'd versions of Ruby.

**Comment by jgeewax** [comment]
Thought I'd add this link to the thread: http://archive.oreilly.com/pub/a/ruby/excerpts/ruby-best-practices/writing-backward-compatible.html

**Comment by blowmage** [comment]
We will keep 1.9 support for as long as we can. Some services will require 2.0, and we will raise a runtime error when running on 1.9.
