### ISSUE TITLE
Keep the left navigation bar in the documentation consistent

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#124]
Looks like when I click around in the items in the left-hand navigation bar, the content changes depending on where I am in the hierarchy.

Could we make this stay consistent so that you always have access to all of the navigation options (ie, I don't have to click to the top-level and then navigate down the tree) ?

I suspect that this will get long, so this div will need to be scrollable. Check out the gcloud-node CSS for an example (I just did `position: fixed` and `overflow-y: auto`).

**Comment by blowmage** [comment]
The left navigation is now [configurable](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/gcloud-rdoc/lib/rdoc/generator/gcloud/config/side.yml) as part of the documentation template. It is consistent across pages. A new API Reference link was added to display all constants and methods, leaving the left navigation free for only the most import links.

**Comment by jgeewax** [comment]
Looks like the first part of this is finished. Going to create a new issue to track the overflow + position.
