### ISSUE TITLE
On landing page, "gcloud-ruby" should probably say StackOverflow

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#131]
I understand that we're trying to be more specific (by saying the actual StackOverflow tag), but most people don't know the SO logo, so I think we need to be more clear about what the link does, which is take people to StackOverflow.

**Comment by jgeewax** [comment]
This also should be in the left-navigation inside the docs (http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/index.html -- see toward the bottom left)

**Comment by blowmage** [comment]
This is now changed.
