### ISSUE TITLE
Make version history and Report issue buttons on docs side-by-side ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#133]
The buttons on the docs page aren't actually side-by-side -- any chance we could make them appear horizontally stacked?

Screenshot of http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/Gcloud/Datastore/KeyfileError.html:

![not-side-by-side](https://cloud.githubusercontent.com/assets/112928/7571319/d57effac-f7e4-11e4-8fce-c57ff5eedc81.png)

**Comment by blowmage** [comment]
The buttons are now side-by-side.
