### ISSUE TITLE
Anchor links on the docs don't take the header bar into consideration

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#134]
Example: http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/index.html#label-Quick+Start

Note in the screenshot that the anchor is covered up by the header bar -- looks like we need some extra offset.....

![anchor covered](https://cloud.githubusercontent.com/assets/112928/7571395/53889e6c-f7e5-11e4-917a-f2e723011412.png)

**Comment by blowmage** [comment]
This is fixed. Here is an [example anchor](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/#label-Authentication) that is no longer be hidden by the navigation bar.
