### ISSUE TITLE
Make links to files at the bottom of the navigation bar use nicely friendly names

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#135]
Right now, CHANGELOG.md, CONTRIBUTING.md, etc are all shown verbatim, rather than as a nicely formatted string. Could we maybe hard-code these files in (it's unlikely that they'll change) to read Change history, Contributing, etc ?

**Comment by blowmage** [comment]
This is now [configurable](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/gcloud-rdoc/lib/rdoc/generator/gcloud/config/side.yml) as part of the documentation template.
