### ISSUE TITLE
Put the title in the white area of the docs rather than overloading the grey header?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#136]
Looking at http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/Gcloud/Storage/Bucket.html, notice that the grey header changes to Gcloud::Storage::Bucket

I think it might look better if the header lived inside the white target area -- here is how gcloud-node does it: http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0/storage/bucket

Not firm on this, but I think it's worth having a discussion.

**Comment by blowmage** [comment]
What text would you like to see in the gray header?

**Comment by jgeewax** [comment]
In the others, we just show the name of the language... So "Ruby" ?

**Comment by blowmage** [comment]
FWIW, the node project is now putting the title text in the gray header.

Changes to the documentation are coming, promise. :)

**Comment by blowmage** [comment]
@jgeewax I'd like to close this as wontfix. Is that okay?

**Comment by blowmage** [comment]
@jgeewax Since gcloud-node is using the gray header now, can I close this as wontfix?

**Comment by jgeewax** [comment]
Yep! Closing.
