### ISSUE TITLE
Organize left-hand navigation a bit more explicitly?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#138]
Right now the left-nav looks like all of the stuff in the package. Is there any way to make this a bit more explicit:

For others, we have an arrangement that is:

- gcloud
- BigQuery
  - Dataset
  - Job
  - Table
- Datastore
  - Dataset
  - Transaction
  - Query
- PubSub
  - Topic
  - Subscription
- Storage
  - Bucket
  - File

Then

- Authorization
- FAQ
- Troubleshooting

Might be better to follow a similar structure for each (notice that the services are alphabetically organized, but the classes inside each service are organized based on their hierarchy -- for the most part).

**Comment by blowmage** [comment]
This is now [configurable](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/gcloud-rdoc/lib/rdoc/generator/gcloud/config/side.yml) as part of the documentation template.
