### ISSUE TITLE
Anchor links on the docs still are a bit off positionally

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#143]
For example, going to http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/Gcloud/Storage/Bucket.html#delete-method

Here's what this looks like:

![scroll position](https://cloud.githubusercontent.com/assets/112928/8107715/71615d42-1019-11e5-9da2-9eaf115310b1.png)

Here's what I'd expect this to look like:

![scroll correct](https://cloud.githubusercontent.com/assets/112928/8107758/a45c38ca-1019-11e5-9cf6-902e32fda225.png)

**Comment by blowmage** [comment]
Ah, took me a bit to find this. The links in the blue area were linking to a different anchor point that didn't have the offset. I've updated the links to use the correct anchors. The link you would use now is http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/Gcloud/Storage/Bucket.html#method-i-delete
