### ISSUE TITLE
Pubsub has a concept of 'project' where the others don't?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#144]
For example (taken from the documentation)

Datastore:

```ruby
require "glcoud/datastore"

dataset = Gcloud.datastore "my-todo-project",
                           "/path/to/keyfile.json"
entity = dataset.find "Task", "start"
entity["completed"] = true
dataset.save entity
```

and Pubsub:

```ruby
pubsub = Gcloud::Pubsub.project "my-todo-project",
                                "/path/to/keyfile.json"
topic = pubsub.topic "my-topic"
msg = topic.publish "task completed"
```

Why does Pubsub need `.project` ? Should we just make it

```ruby
pubsub = Gcloud::Pubsub "my-todo-project",
                         "/path/to/keyfile.json"
topic = pubsub.topic "my-topic"
msg = topic.publish "task completed"
```

**Comment by jgeewax** [comment]
Might also be worth noting the difference in `Gcloud::Pubsub` versus `Gcloud.datastore` ... Any background on this inconsistency? Can we reasonably avoid this?

**Comment by blowmage** [comment]
This is a mistake in the docs. It should be:

```ruby
pubsub = Gcloud.pubsub "my-todo-project",
                       "/path/to/keyfile.json"
topic = pubsub.topic "my-topic"
msg = topic.publish "task completed"
```

What `Gcloud.pubsub` returns is an instance of `Gcloud::Pubsub::Project`, as all the classes are under the `Gcloud::Pubsub` namespace. But the guidance is to use `Gcloud.pubsub` to get that object instead of calling `Gcloud::Pubsub::Project.new`.

**Comment by blowmage** [comment]
This has been addressed in the updated documentation.

See https://github.com/GoogleCloudPlatform/gcloud-ruby#pubsub
