### ISSUE TITLE
Should we make the defaults use the auto-magical project + credential discovery?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#147]
In most of our code samples, we provide the project ID + keyfileJson path. Should we consider instead just using the implicit "I'll figure it out" syntax?

To be specific, I mean replacing (http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Dataset.html)

```ruby
dataset = Gcloud.datastore "my-todo-project",
                           "/path/to/keyfile.json"
```

with 

```ruby
dataset = Gcloud.datastore
```

**Comment by blowmage** [comment]
My intention is to only show the `Gcloud.datastore` calls with `project` and `keyfile` arguments when discussing authentication or documenting the `Gcloud.datastore` method. The Dataset code sample slipped through the cracks, I'll fix it.
