### ISSUE TITLE
Should we be explicit about defining a Dataset in Datastore?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#148]
Currently, Datastore only allows you to have one dataset, but this won't be the case forever. Eventually you'll be able to create datasets, and you'll need a way of asking for a specific Dataset. Further, the projectId would not be the same as the dataset ID, so we'd need both of those explicitly.

Would it be wise to still support the "default dataset" (dataset ID == project ID), but also allow users to say "I want dataset id = otherid" ?

Ie, to get multiple datasets explicitly

```ruby
datastore = Gcloud.datastore "my-todo-project",
                             "/path/to/keyfile.json"
dataset = datastore.dataset "my-dataset-id"
dataset2 = datastore.dataset "my-other-dataset-id"
```

Operations on the `datastore` object here would be operating on the dataset called "my-todo-project" implicitly. That is, these are the same:
```ruby
datastore = Gcloud.datastore "my-todo-project",
                             "/path/to/keyfile.json"
datastore.get ...

dataset = datastore.dataset "my-todo-project"
dataset.get ...
```

**Comment by blowmage** [comment]
I have heard whispers that multiple Datasets are coming to Datastore, but I don't know any of the specifics. The conclusion arrived previously is that Datastore service will have an API change to support these changes, and Gcloud will have API changes in response to that. I would expect that Datastore would behave more like Storage, with a top-level Project object that creates the Datasets. (I've also heard that the term "Dataset" is on its way out, and in the future it will be called "Database".)

**Comment by jgeewax** [comment]
This is correct. So given that, should we add this as a concept?

**Comment by blowmage** [comment]
A few questions:

1. Is the preferred term "dataset" or "database"?
2. When are these changes expected to be available? Will they be in a future v1beta3 release? Or post v1?
3. Are dataset/database names going to be globally unique across all accounts like buckets in the Storage service? Or locally unique within the project like topics in the PubSub service?
4. How will the names work with the current datasets? Currently, the dataset_id is the same as the Google Cloud project, and cannot be changed. In the future, will these existing datasets be given a different name? Or will it be a "default" dataset without a name and other datasets are created with a name?

**Comment by jgeewax** [comment]
> 1. Is the preferred term "dataset" or "database"?

As of today, it's "dataset".

> 2. Will they be in a future v1beta3 release?

Don't know for sure yet. Likely to be v2.

> 3. Are dataset/database names going to be globally unique across all accounts like buckets in the Storage service? Or locally unique within the project like topics in the PubSub service?

Locally unique within a project AFAIK.

> 4. How will the names work with the current datasets?

We'll likely keep that around as your "default dataset", so if you send requests without specifying the dataset, we'll fill it in with the default one (which is named after your project).

**Comment by blowmage** [comment]
Datastore v1beta3 support in gcloud-ruby is very close to being released. It doesn't allow more than one dataset, so this remains an unnecessary step. If a future v2 API includes multiple datasets it will provide additional information (e.g. naming), as well as require breaking changes. When that happens gcloud-ruby will release a major version change to support it. Closing until this becomes more actionable.
