### ISSUE TITLE
Datastore docs use `task` which could be confusing

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#149]
Could we switch our datastore docs to use a more obvious demo Kind / Entity ?

For example, http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Dataset.html#delete-method has

```ruby
dataset = Gcloud.datastore
dataset.delete task1, task2
```

It makes me think there are tasks floating around somewhere -- not that I have a Kind called Task and these are entities.

I'd be happier with...

```ruby
dataset = Gcloud.datastore
dataset.delete entity1, entity2
```

**Comment by blowmage** [comment]
Makes sense. This is an oversight and a holdover from the code examples in the previous documentation.
