### ISSUE TITLE
Add a way to get the dataset ID ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#150]
Since we expose Datastore/dataset.project, maybe we shoudl expose dataset.id? (http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Dataset.html#project-method)

These are currently identical, but won't always be that way.

**Comment by blowmage** [comment]
Gcloud originally has a `dataset_id` alias for `project`, but it was removed in c551eac46ae3d03f25862af1bfee1088b07d391d at the request of the Datastore team. I don't know much about the details. @silvolu, do you remember why?

**Comment by blowmage** [comment]
v1beta3 changed the name to `project_id`, which we have been exposing as `project`. So until there is a larger API change I think we can consider this closed.
