### ISSUE TITLE
Datastore Key isn't in the left-navigation

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#151]
To get to the Key documentation (http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Key.html) you have to find a link to it somewhere.

Any chance we could add it to the left nav?

**Comment by blowmage** [comment]
Yes, Key was originally in the left nav, but I removed it to closer match the gcloud-node left nav. I'll add it back.

**Comment by blowmage** [comment]
The key left nav is now there for both master and v0.1.0.
