### ISSUE TITLE
Storage docs don't list the `find_bucket` method in public class methods?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#152]
I'd expect the top-level doc for Storage (http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage.html) to have the `find_bucket` method listed there.

It's in the example, but not listed on that page. Any idea why that is the case?

**Comment by jgeewax** [comment]
Ah, it seems this is on the Gcloud::Storage::Project class -- should we put this on the Storage main page ?

**Comment by blowmage** [comment]
I think the revised Storage documentation will address this better. Coming soon.

**Comment by blowmage** [comment]
Please take a look at the updated documentation. There are links from the [Storage URL](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage.html) you used to [Project#find_bucket](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage/Project.html#method-i-find_bucket). If this is sufficient then this issue can be closed.

**Comment by jgeewax** [comment]
SGTM.
