### ISSUE TITLE
Rearranging report issue and version history buttons?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#155]
If you look at the Node page, we moved the report issue button to the top header, so that it's always available.

And then put the version selection stuff on the top left

https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.15.0

Could we do likewise for Ruby?

**Comment by blowmage** [comment]
Yes, the way documentation is structured we have the ability to implement this. This is on my roadmap of future changes to make, but I didn't have an issue created for it.

**Comment by blowmage** [comment]
The GitHub issue button is now moved to the header, and the versions button is removed as we have the version switcher dropdown now.
