### ISSUE TITLE
Put argument docs into a table?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#156]
Feels like we could make things more concise if we put the arg docs into tables (similar to https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.15.0/datastore/transaction).

Would Ruby folks would be put off by that?

**Comment by blowmage** [comment]
This is possible. RDoc markup doesn't generate tables, but we can put HTML in the documentation to achieve this.

**Comment by blowmage** [comment]
After playing with tables and having issues with them on the smaller screens, I decided a better solution may be to style the definition lists in a more compact, table-like way on bigger screens. See http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage/Project.html#method-i-buckets Does this work?

**Comment by jgeewax** [comment]
It's definitely better than before -- however what's the issue with small screens and tables? https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.16.0/bigquery/table?method=copy for example works just fine for me on mobile.

**Comment by blowmage** [comment]
I had some issues where I had to scroll the page horizontally to see the text on mobile screen sizes. And the documentation with longer descriptions weren't very readable in a table on small screens IMO. e.g. http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage/Bucket.html#method-i-create_file But I'm on an older iPhone with the smaller screen. :)

**Comment by jgeewax** [comment]
Hmm weird, this feels still like a table though -- maybe the border was an issue ? Let's call this closed for now and re-open if we think of a better way.
