### ISSUE TITLE
Can't find the anchor for some methods in the docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#159]
For example, http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Entity.html#method-i-key-3D-label-Example

is an anchor to the example for the `key=(new_key)` method, but I can't get an anchor thing to appear for the method itself.

**Comment by blowmage** [comment]
Links to method anchors have been added. See http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Entity.html#method-i-key-3D
