### ISSUE TITLE
Make the anchor links always visible?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#160]
Looks like the anchor links only ever appear when I hover. Could we make them always visible and use the `#` sign instead ? See https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.15.0/datastore?method=dataset for an example.

**Comment by blowmage** [comment]
The `#` symbol is meaningful in Ruby documentation. An instance method is described as `Class#method`, where a class method is `Class.method`. Is there another symbol you would prefer?

**Comment by jgeewax** [comment]
Got it. The paragraph symbol will be fine then :)

**Comment by blowmage** [comment]
I'm not able to change the markup in headings within the method descriptions, but I am able to style it differently. See http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud.html#method-c-datastore
