### ISSUE TITLE
Entity.exclude_from_indexes?(name) method is a bit confusing

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#161]
Particularly the definition about what's happening here is super confusing to me:

> Array property values will return an array of flag settings.
> 
> ```ruby
entity["tags"] = ["ruby", "code"]
entity.exclude_from_indexes? "tags" #=> true [false, false]
```

The closest anchor link I can get you is http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Entity.html#method-i-key-3D-label-Example (scroll up)

**Comment by blowmage** [comment]
Typo. That should be:

```ruby
entity["tags"] = ["ruby", "code"]
entity.exclude_from_indexes? "tags" #=> [false, false]
```

**Comment by blowmage** [comment]
The method is named like that because it is the lookup companion for `exclude_from_indexes!`.

```ruby
entity["tags"] = ["ruby", "code"]

entity.exclude_from_indexes! "tags", true
entity.exclude_from_indexes? "tags" #=> [true, true]

entity.exclude_from_indexes! "tags", false
entity.exclude_from_indexes? "tags" #=> [false, false]

entity.exclude_from_indexes! "tags", [true, false]
entity.exclude_from_indexes? "tags" #=> [true, false]

entity.exclude_from_indexes! "tags" do |tag|
  tag =~ /c/
end
entity.exclude_from_indexes? "tags" #=> [false, true]
```

**Comment by jgeewax** [comment]
I still have no idea why I'm getting back an array of booleans for a single property. Does it really work that way in production?

I thought you could say to exclude a property (in this case, the property "tags") -- not specific values of the property? I could be wrong though.

**Comment by blowmage** [comment]
It returns arrays of booleans if the property is an array. If the property is a single value, it returns a single boolean.

**Comment by jgeewax** [comment]
I'm confused still though. Are we effectively saying that "certain values for this won't be indexed" ? Isn't that a bit confusing? Wouldn't it be easier (and more common) to keep the level of granularity at the property-level?

**Comment by jgeewax** [comment]
And what happens if...

```ruby
entity["tags"] = ["ruby", "code"]
entity.exclude_from_indexes! "tags", [true, false, true]
```

Error?

**Comment by blowmage** [comment]
That will not error, it will use any flags given, and then use the default afterwards.

```ruby
entity["tags"] = ["ruby", "code"]
entity.exclude_from_indexes! "tags", [true, false, true]
entity.exclude_from_indexes? "tags" #=> [true, false]

# Change tags
entity["tags"] = ["ruby", "code", "rails", "default1", "default1"]
entity.exclude_from_indexes? "tags" #=> [true, false, true, false, false]
```

**Comment by blowmage** [comment]
> I thought you could say to exclude a property (in this case, the property "tags") -- not specific values of the property? I could be wrong though.

You can still do that. If you exclude a property that is an array, but you only give it a single value, that will be used for all property values.

```ruby
entity["tags"] = ["ruby", "code"]
entity.exclude_from_indexes! "tags", true
entity.exclude_from_indexes? "tags" #=> [true, true]

entity.exclude_from_indexes! "tags", false
entity.exclude_from_indexes? "tags" #=> [false, false]
```

This is actually the expected use case. Passing in a list of exclude flags or providing a block to evaluate each element in the array is the edge case.

**Comment by jgeewax** [comment]
OK, can we update the documentation for this then ? Maybe a big long thing in the setter saying what all of this means?

Referring specifically to "Properties that are arrays can be given multiple exclude flags." -- we should make that more detailed. I can take a crack at it.
