### ISSUE TITLE
Highlight the currently selected item in the left navigation?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#162]
Right now, the current page (if it exists in the left nav -- which it should) doesn't get highlighted when I'm on it. 

Any chance we could add this? Ie, http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.15.0/pubsub/topic (look on the left nav)

**Comment by blowmage** [comment]
The current page is now highlighted in the left nav.
