### ISSUE TITLE
Do we need the API Reference page?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#164]
Seems a bit redundant given the left nav that we have, right?

**Comment by blowmage** [comment]
IMO it is not redundant. There are many classes and methods that are not easily discoverable from the left nav. [Backoff](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Backoff.html) configuration, for example, can be found by linking from a method that supports backoff, but it is not listed anywhere else. In the future I would like to add search/filter functionality to the API Reference page to make it easier to use.

**Comment by jgeewax** [comment]
Hm -- OK, let's leave it for now. :)
