### ISSUE TITLE
Do we need the LICENSE / Contribute Guide on the usage-focused docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#165]
I'd expect this stuff to be on the GH repo, but not necessarily on the docs on gh-pages. Any thoughts?

**Comment by blowmage** [comment]
We can easily remove them. I find value in them but can see why you would rather not have them there. Should I make this change?

**Comment by jgeewax** [comment]
I'd vote to keep the gh-pages focused on people wanting to *use* the library.

GH's repo with MD files named appropriately would be for people wanting to *contribute* to the library.
