### ISSUE TITLE
Anchor links for non-methods are off a tiny bit

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#167]
(I thought I reported this already, and was trying to re-open, but I can't find that bug... apologies if this is a duplicate.)

Looking at http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Dataset.html#class-Gcloud::Datastore::Dataset-label-Dataset and comparing it to http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Datastore/Dataset.html#method-i-allocate_ids it looks like the first is totally flush with the top of the page, where the method has a nice amount of padding from the top.

Could we keep that padding for non-method anchors also?

Good:

![screen shot 2015-06-17 at 8 34 01 am](https://cloud.githubusercontent.com/assets/112928/8211436/b1a24108-14cb-11e5-88a9-4184b8e9a9b2.png)

Not so good:

![screen shot 2015-06-17 at 8 34 09 am](https://cloud.githubusercontent.com/assets/112928/8211442/b92701ac-14cb-11e5-9529-f34ea5e07574.png)

**Comment by blowmage** [comment]
@jgeewax Can you look at the links again and see if that fixes the issue?

**Comment by jgeewax** [comment]
LGTM.
