### ISSUE TITLE
What is the ordering logic for the version dropdown?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#171]
Looks like it's listed as:

- v0.1.1
- master
- v0.1.0

I don't think there's enough data, but it could be: latest public (selected), master, older (incrementing)

I think it might be better to do: master, latest public (selected), older (incrementing)

Thoughts?

**Comment by blowmage** [comment]
Yes, the way I have it now is current, then previous. This is mean to match the sort order found on the [documentation page](http://googlecloudplatform.github.io/gcloud-ruby/docs/). (This URL isn't linked to anywhere, but folks manipulating the URL will find it.) It shows the Current versions, which is the current released version, and master. Then it shows the Previous versions, which right now is only v0.1.0.

I originally had the order of the dropdown match the node project, but I think that the two most useful links are the current release and master, so they should be first I didn't like scrolling to the bottom to get to master.

The order can easily be changed, but I do think the current order has some benefits. I was thinking of adding a separator to better separate current from previous. Something like this:

* v0.1.1
* master
* --------
* v0.1.0

**Comment by jgeewax** [comment]
+1 to that. LGTM

**Comment by blowmage** [comment]
K, the nav switcher has the separator option now. Please check it out.

**Comment by blowmage** [comment]
Oops, commits 6779938 and ba3790f were supposed to reference this issue.

**Comment by jgeewax** [comment]
Awesome - thanks :)
