### ISSUE TITLE
Gcloud::Storage::File#signed_url does not work when using Google Cloud SDK credentials

### ISSUE THREAD

**Issue by premist** [GoogleCloudPlatform/gcloud-ruby#181]
I tried using [Gcloud::Storage::File#signed_url](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.1/Gcloud/Storage/File.html#method-i-signed_url) to generate object url with query strings, but I can't get it to work. I used the following code:

```ruby
s = Gcloud.storage "my-project-name"
buk = s.find_bucket "my-bucket"
file = buk.find_file "myfile.txt"
file.signed_url
```

It returns the following error:

```ruby
[10] pry(main)> file.signed_url
NoMethodError: undefined method `sign' for nil:NilClass
from /Users/premist/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/gcloud-0.1.1/lib/gcloud/storage/file.rb:502:in `signed_url'
```

I tried to investigate this and found out that [signing_key on Gcloud::Credentials](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/9c035ac0e388fc30bc7ae169829c052cd14f658f/lib/gcloud/credentials.rb#L138) is not being set properly.

I used gcloud auth credential from my computer initially, and I tried to explicitly provide keyfile for authentication too, but it didn't work.

**Comment by blowmage** [comment]
Hey @premist, the `File#signed_url` method expects that the Signet::OAuth2::Client object used for authenticating returns a valid object when calling it's [`signing_key`](http://www.rubydoc.info/gems/signet/0.6.1/Signet/OAuth2/Client#signing_key-instance_method) method. According to the documentation, `signing_key` can return a OpenSSL::PKey (which we expect), or a string (which we don't expect yet, but I'm not sure we will see since we create a OpenSSL::PKey object). But in your case `nil` is being returned, which is very strange.

I am having a hard time reproducing this. Are you available to pair remotely so I can see what you are doing in hopes of creating a reliable reproduction?

**Comment by premist** [comment]
I will try to replicate this on clean Linux machine soon and let you know. If this works properly on clean environment, there should be some misconfiguration on my machine which causes the issue.

**Comment by blowmage** [comment]
@premist Any luck reproducing this?

**Comment by premist** [comment]
Hi @blowmage, sorry for late reply. Will try this later today and I'll let you know how it goes.

**Comment by blowmage** [comment]
Thanks! Looking forward to it. :)

**Comment by blowmage** [comment]
Hey @premist, when you provide the keyfile explicitly, are you giving the absolute path to the file? e.g `/Users/premist/gcloud.json` and not `~/gcloud.json`?

**Comment by premist** [comment]
I created a clean Ubuntu (15.04 x64) VM, and did the following:
- Install Ruby 2.2.2 via rbenv
- Install [Google Cloud SDK](https://cloud.google.com/sdk/)
- Used `$ gcloud auth login` to sign in
- Install gcloud gem

I tried the code above again and it failed. Seems like `signing_key` doesn't work as intended when gcloud gem [authenticates using Cloud SDK credentials](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/AUTHENTICATION.md#cloud-sdk).

**Comment by blowmage** [comment]
@premist Thanks! You also said:

> I used gcloud auth credential from my computer initially, and I tried to explicitly provide keyfile for authentication too, but it didn't work.

I can't get it to fail when explicitly providing a keyfile, but I assume that the path you provided didn't resolve and so it fell back to the cloud SDK credentials. Any chance you can confirm?

**Comment by premist** [comment]
I tried providing JSON keyfile explicitly to `Gcloud.storage`, and it worked. Providing an invalid path like `~/Downloads/keyfile.json` raised a proper error, which is the following:

    RuntimeError: The keyfile '~/Downloads/keyfile.json' is not a valid file.

I'm not sure why I was unable to get signed url when I provided keyfile explicitly, but seems like it works as intended.

**Comment by blowmage** [comment]
It looks like that the code that derives credentials from the cloud SDK doesn't return "service account" credentials, which is missing the private key needed to sign the URLs. Right now we're trying to determine how we can convert "authorized user" credentials to "service account" credentials.

**Comment by premist** [comment]
I found something that might be related to this on gsutil documentation. In order to use `gsutil signurl` command, **you need to explicitly provide private key file regardless of Google Cloud SDK authentication**.  

I checked [gcloud-python](https://github.com/GoogleCloudPlatform/gcloud-python) and [gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node), seems like those libraries don't support authentication by Cloud SDK. Also I couldn't find a code which converts 'authorized user' credentials to 'service account' credentials.

**Comment by jgeewax** [comment]
I'm pretty sure both node and python will pull the creds set by the cloud SDK. CC @stephenplusplus @dhermes to comment.

**Comment by dhermes** [comment]
Yes, we have a tight integration with https://github.com/google/oauth2client and don't implement much of the signing ourselves, just proxy it out to the auth library.

**Comment by stephenplusplus** [comment]
Same as @dhermes said, our auth library is https://github.com/google/google-auth-library-nodejs which respects the cloud sdk session.

**Comment by premist** [comment]
Ah, thanks for the correction. Then it should be possible to generate signed url using Cloud SDK credentials.

**Comment by blowmage** [comment]
@dhermes @stephenplusplus Do your auth libraries give you credentials with the private key when authenticating with the cloud SDK? Or do you have a way to exchange the "authorized user" credentials for "service account" credentials?

**Comment by blowmage** [comment]
The [signed url documentation](https://cloud.google.com/storage/docs/access-control#Signed-URLs) is clear about requiring service account authentication for signing the url. We need the private key to sign the url.

**Comment by stephenplusplus** [comment]
No, haven't found a way to do this yet: https://github.com/GoogleCloudPlatform/gcloud-node/issues/211

**Comment by dhermes** [comment]
There is no way to sign with "authorized user" credentials, it must be a service account. Our code paths fail on non-service account credentials (as well as on GCE service account credentials).

**Comment by blowmage** [comment]
@stephenplusplus Ah, thanks for the link. I had missed than in my searches. Makes sense.

@dhermes Thank you for the confirmation.

@premist I have some ideas. I'll try to get a PR up today.
