### ISSUE TITLE
Language dropdown broken on certain pages..?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#182]
I found this one (http://googlecloudplatform.github.io/gcloud-ruby/docs/) but I'm guessing there may be more?

Might be worthwhile to do a quick pass over this.

**Comment by blowmage** [comment]
Is the dropdown broken? Or is it just missing?

**Comment by jgeewax** [comment]
It is visible, but broken in the sense that clicking on it does nothing.

**Comment by blowmage** [comment]
Oh, I thought you meant the doc navigation switcher dropdown. Yeah, that isn't working for me either. I'll get it working.

**Comment by blowmage** [comment]
The dropdown on this page is now working. Problem with how the `<script>` tags were formed. Thanks for the heads up!
