### ISSUE TITLE
Make dropdown inside the docs to link to "inside the docs" for other languages

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#184]
The dropdown you see here: http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.1/, when switching, links to the other-language-equivalent of http://googlecloudplatform.github.io/gcloud-ruby/

Could we have it link inside the docs of those other languages? 

ie:

Python: http://googlecloudplatform.github.io/gcloud-python/latest/
Node: http://googlecloudplatform.github.io/gcloud-node/#/docs

**Comment by blowmage** [comment]
Do you want these links changes so while you are in the docs you switch to the other language docs? Or do you want to link to the docs even from the homepage?

e.g http://googlecloudplatform.github.io/gcloud-ruby/ links to http://googlecloudplatform.github.io/gcloud-node/#/docs

**Comment by jgeewax** [comment]
Moral would be "switching should take you the same type of page, just in the other language". So the landing page switcher should take you to other language's landing page. Docs-page switcher should take you to the other language's docs-page.

**Comment by blowmage** [comment]
When viewing documentation the dropdown now links to the other languages' documentation. On the homepage it links to the other languages' homepage. Thanks!
