### ISSUE TITLE
Re-order the left-navigation to match gcloud-node

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#198]
In Node, we went with 3 groupings:

- Getting Started
 - Auth
 - FAQ
 - Troubleshooting
- API
 - gcloud
 - BigQuery
 - ...
- (no title)
 - GitHub
 - Issues
 - StackOverflow
 - npm (in our case, gem)
 - Change history (would go here)

Can we follow the same ordering for Ruby?

**Comment by blowmage** [comment]
@jgeewax It is pretty cumbersome to move Release History to the bottom of the side nav due to the way RDoc deals with documentation text files. How about treating it like README and only showing that page on the git repo and not in the documentation?

**Comment by jgeewax** [comment]
SGTM.

**Comment by blowmage** [comment]
DONE!
