### ISSUE TITLE
Get final review of BigQuery API by Cloud BigQuery team from Google

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#200]
We need someone on the Google team to review the ruby implementation and documentation and provide feedback.

**Comment by blowmage** [comment]
@jgeewax Do we have someone to look at this?

**Comment by blowmage** [comment]
@thagomizer You gave a talk about BigQuery at a ruby conference, do you have time this week to look over the API we've come up with and give us feedback?

**Comment by thagomizer** [comment]
Yes. I'm also getting a BigQuery proposal together for RubyConf. Is Wednesday okay?

**Comment by blowmage** [comment]
That would be awesome! Thanks!

**Comment by blowmage** [comment]
Our docs can be found here: http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Bigquery.html

They are only on the master docs until they are released. Hopefully we'll release on Friday. :)

**Comment by thagomizer** [comment]
This looks great. It makes sense and I think is pretty straightforward to integrate into a project. The async query API looks a bit awkward but async is awkward in Ruby so that part feeling weird makes sense.

**Comment by blowmage** [comment]
Thanks Aja!

**Comment by quartzmo** [comment]
Thank you @thagomizer. It will be so great to have your input.
