### ISSUE TITLE
Add inspect

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#208]
Some objects are overly large when displayed in IRB or test output. Overriding `inspect` on the classes will make them to be easier to view.

**Comment by quartzmo** [comment]
The easy, quick way to end the horrendously verbose console output is to override `inspect` (or `to_s`) in the connection classes. Another approach would be to try to bring the output of `inspect` (or `to_s`) for every public class in line with the Rest API resource representation. A big job for sure, but there may be value in it. As suggested by the official [Ruby documentation](http://ruby-doc.org/core-2.2.3/Object.html#method-i-inspect):

> User defined classes should override this method to provide a better representation of obj. When overriding this method, it should return a string whose encoding is compatible with the default external encoding.

@blowmage How were you originally picturing this scope of work?

**Comment by blowmage** [comment]
The default inspect reveals the internals of the object, the implementation, which may change over time. Normally it isn't a problem, but we have some very large objects in the object graph and the output is ridiculously big. I agree that the biggest bang for the buck is overriding the Connection objects, which are not part of the public API but expose many things about how gcloud works. Google API Client, Signet, etc. Those are the worst offenders IMO. But, if we override inspect on Connection I figure we might as well do the other classes as well. Consistency is good.

That said, I haven't started this yet so I don't know what the appropriate scope of the work is. Perhaps overriding inspect in all classes is more work for minimal benefit? Hard to say until we dig into it.

**Comment by quartzmo** [comment]
Let's schedule a time to pair on this one.

**Comment by quartzmo** [comment]
Here's what I currently have locally. The final method call shows how the new Storage connection inspect looks in a collection.

```
irb(main):001:0> gcloud.bigquery
=> #<Gcloud::Bigquery::Project:0x007ffb84099d90 @connection=Gcloud::Bigquery::Connection(nodal-almanac-725)>
irb(main):002:0> gcloud.datastore
=> #<Gcloud::Datastore::Dataset:0x007ffb8435a638 @connection=Gcloud::Datastore::Connection(nodal-almanac-725)>
irb(main):003:0> gcloud.pubsub
=> #<Gcloud::Pubsub::Project:0x007ffb83ab88b8 @connection=Gcloud::Pubsub::Connection(nodal-almanac-725)>
irb(main):004:0> gcloud.storage
=> #<Gcloud::Storage::Project:0x007ffb83cfd290 @connection=Gcloud::Storage::Connection(nodal-almanac-725)>
irb(main):005:0> _.buckets
=> [#<Gcloud::Storage::Bucket:0x007ffb8723a1d8 @connection=Gcloud::Storage::Connection(nodal-almanac-725), @gapi=#<Google::APIClient::Schema::Storage::V1::Bucket:0x3ffdc391d268 DATA:{"kind"=>"storage#bucket", "id"=>"bigquery-exports-0943faf3-5e27-42ec-acd9-765450b3ce55", "selfLink"=>"https://www.googleapis.com/storage/v1/b/bigquery-exports-0943faf3-5e27-42ec-acd9-765450b3ce55", "projectNumber"=>"324770174224", "name"=>"bigquery-exports-0943faf3-5e27-42ec-acd9-765450b3ce55", "timeCreated"=>"2015-08-19T22:29:55.089Z", "metageneration"=>"1", "owner"=>{"entity"=>"project-owners-324770174224"}, "location"=>"US", "storageClass"=>"STANDARD", "etag"=>"CAE="}>>, 
#<Gcloud::Storage::Bucket:0x007ffb8723a188 @connection=Gcloud::Storage::Connection(nodal-almanac-725), @gapi=#<Google::APIClient::Schema::Storage::V1::Bucket:0x3ffdc391d1f0 DATA:{"kind"=>"storage#bucket", "id"=>"datastore-backups-d914dd52-7f99-4a74-8aa2-8cb15c25a05c", "selfLink"=>"https://www.googleapis.com/storage/v1/b/datastore-backups-d914dd52-7f99-4a74-8aa2-8cb15c25a05c", "projectNumber"=>"324770174224", "name"=>"datastore-backups-d914dd52-7f99-4a74-8aa2-8cb15c25a05c", "timeCreated"=>"2015-08-24T22:58:09.821Z", "metageneration"=>"1", "owner"=>{"entity"=>"project-owners-324770174224"}, "location"=>"US", "storageClass"=>"STANDARD", "etag"=>"CAE="}>>
, #<Gcloud::Storage::Bucket:0x007ffb8723a138 @connection=Gcloud::Storage::Connection(nodal-almanac-725), @gapi=#<Google::APIClient::Schema::Storage::V1::Bucket:0x3ffdc391d178 DATA:{"kind"=>"storage#bucket", "id"=>"gcloud_ruby_regression_2015_07_31t17_28_30z_f7396365_dataset", "selfLink"=>"https://www.googleapis.com/storage/v1/b/gcloud_ruby_regression_2015_07_31t17_28_30z_f7396365_dataset", "projectNumber"=>"324770174224", "name"=>"gcloud_ruby_regression_2015_07_31t17_28_30z_f7396365_dataset", "timeCreated"=>"2015-08-07T14:47:26.213Z", "metageneration"=>"1", "owner"=>{"entity"=>"project-owners-324770174224"}, "location"=>"US", "storageClass"=>"STANDARD", "etag"=>"CAE="}>>]
```

I think the new inspect on the Connection class for each service solves most of the problem at very low cost, but maybe I should try to improve some of the *slightly* too verbose classes such as Bucket?

**Comment by blowmage** [comment]
I kinda agree about overriding inspect on other classes. Especially when viewing collections. But I can also see the argument for only doing Connection.

Up to you IMO. :)

**Comment by quartzmo** [comment]
After thinking about it, I think it's best to leave this @gapi output as-is, for the benefit of easy inspection of any attribute that someone may be interested in. PR coming soon for connection changes.
