### ISSUE TITLE
Make `.from_response`/`.from_resp` usage consistent

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#212]
The names of these private methods are sometimes inconsistent across gcloud.

**Comment by quartzmo** [comment]
Which one do you prefer, `from_response` or `from_resp`? I vote for `from_response`, but not if it's going to cause line-length issues with rubocop.

**Comment by blowmage** [comment]
Sounds good to me.

**Comment by quartzmo** [comment]
OK, i'll do this one right now.

**Comment by jgeewax** [comment]
+1 to `from_response` :)
