### ISSUE TITLE
Error building v0.1.0 docs with `rake pages:rebuild`

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#215]
Calling `bundle exec rake pages:rebuild` will fail on v0.1.0 because of missing hoe dependency. It would be good if that first release played nice with bundler...

We don't want to add hoe as a dependency because it was only used on the v0.1.0 release and we'd rather not force all future developers to install it.

**Comment by quartzmo** [comment]
Any suggestions for how to fix this without adding hoe to the Gemfile?

**Comment by blowmage** [comment]
I think we should just swap the Gemfile and gcloud.gemspec file to a version that works with what we use since the transition to using Bundler. Similar to the ae0019150f07c8ffde4bb96a996ceec0ac79b119 commit. Thats the only way I can see to resolve this.

R.I.P [hoe](https://rubygems.org/gems/hoe)...

**Comment by blowmage** [comment]
The problem wasn't loading Hoe, it was Bundler applying the parent settings to sub shells. Judicial use of `Bundler.with_clean_env` solved the problem. The tag commit remains unchanged. :+1:
