### ISSUE TITLE
'create_file' unhandled exception

### ISSUE THREAD

**Issue by VincentVanGoat** [GoogleCloudPlatform/gcloud-ruby#219]
I'm trying to upload a file to a bucket using the following script:

```
require "gcloud"

gcloud = Gcloud.new "g-storage-103621",
                    'C:\Users\Kanishka\GoogleCloudStorage\keyfile\google-storage-756c0950e8bc.json'
storage = gcloud.storage

bucket = storage.bucket "g-storage-bucket"

bucket.create_file "C:/Users/Kanishka/GoogleCloudStorage/dataset/language_id.csv"
```

When I run this, I get this error:

```
$ ruby storage-api-test.rb
c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gcloud-0.2.0/lib/gcloud/storage/bucket.rb:330:in `create_file': unhandled exception
        from storage-api-test.rb:9:in `<main>'
```

Please help!

**Comment by blowmage** [comment]
Hi @VincentVanGoat, it would be helpful to see the entire error backlog. But it would be most helpful to remote pair with you. Can you connect to the following URL so we can step through your code and see what is happening?

https://join.me/blowmage1

**Comment by blowmage** [comment]
Are you sure that file exists? What happens if you open IRB and do the following:

```
$ irb
File.file? "C:/Users/Kanishka/GoogleCloudStorage/dataset/language_id.csv"
```

**Comment by blowmage** [comment]
I have to leave now. Send me an email at mike@blowmage.com so we can schedule a time for remote pairing.

**Comment by VincentVanGoat** [comment]
Hey! I made a very stupid blunder: my .csv file was saved as a text document. Thanks and sorry.

**Comment by blowmage** [comment]
No problem! Glad you figured it out. Thank you for using gcloud! Please feel free to ask questions or open issues.
