### ISSUE TITLE
Uploading a file to a bucket

### ISSUE THREAD

**Issue by VincentVanGoat** [GoogleCloudPlatform/gcloud-ruby#221]
I successfully uploaded a file in my bucket with the help of the following script:

require "gcloud"

gcloud = Gcloud.new "g-storage-103621",
                    'C:\Users\Kanishka\GoogleCloudStorage\keyfile\google-storage-756c0950e8bc.json'
storage = gcloud.storage

bucket = storage.bucket "g-storage-bucket"

bucket.create_file "C:/Users/Kanishka/GoogleCloudStorage/dataset/language_id.csv"

When I checked my bucket, I found that the bucket had a path called "C:/Users/Kanishka/GoogleCloudStorage/dataset/language_id.csv".

Instead of directly uploading the file to the bucket, it made directories similar to my computer and uploaded it there. 

How do I upload the file so that it doesn't create directories such has mentioned above and directly uploads it in my bucket like: 'BUCKET_NAME' -> 'FILE_NAME'?

**Comment by blowmage** [comment]
Hi @VincentVanGoat, the [Bucket#create_file](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.2.0/Gcloud/Storage/Bucket.html#method-i-create_file) method takes two arguments, the first is the file to upload, the second is the path for the file to use in the bucket. If the second argument isn't given, the file's path is used.

**Comment by VincentVanGoat** [comment]
Got it.
