### ISSUE TITLE
BigQuery Job#wait_until_complete

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#228]
I would like a helper method that will block on a job until the state moves to `DONE`.

```ruby
job = dataset.query_job "SELECT name, age FROM [users]"
job.wait_until_complete # continually refreshes until the job is DONE.
job.done? #=> true
```

**Comment by blowmage** [comment]
`The mechanism could be similar to the incremental backoff we use when dealing with API calls and quotas. We could incrementally increase the time between refreshing the job data to check if its complete. We might also put a max on the total number of seconds to wait (or iterations to perform) before returning.

```ruby
job = dataset.query_job "SELECT name, age FROM [users]"
job.wait_until_complete max: 120 # max of 2 minutes before returning
job.done? #=> true
```

**Comment by blowmage** [comment]
@quartzmo Is there a better name for this method than `Job#wait_until_complete`?

**Comment by blowmage** [comment]
`Job#block_until_done`?

**Comment by quartzmo** [comment]
I think `wait` is better than `block`, it is a common term in concurrent programming. What about `Job#wait_until_done`? Is `Job#wait` edging too far into concurrency?
