### ISSUE TITLE
cannot load such file -- gcloud

### ISSUE THREAD

**Issue by VincentVanGoat** [GoogleCloudPlatform/gcloud-ruby#229]
Hey I am using g-cloud to upload a some files in the cloud storage and whenever I upload the .csv file, I get an error saying: cannot load such file -- gcloud

This is my controller logic: 

```ruby
def import
    # PurchasedOrder.import(params[:file])
    require 'gcloud'

	gcloud = Gcloud.new "g-storage-103621",
	                    'C:\Users\Kanishka\GoogleCloudStorage\keyfile\google-storage-756c0950e8bc.json'
	storage = gcloud.storage

	bucket = storage.bucket "g-storage-bucket"

	bucket.create_file params[:file].path , "directory"


    redirect_to root_path, :notice => "Data Values imported into database."
  end
```
Please Help!

**Comment by blowmage** [comment]
@VincentVanGoat I assume the error occurs on the `require 'gcloud'` line? Do you have `gcloud` added as a dependency in your Gemfile?

**Comment by VincentVanGoat** [comment]
yes.

**Comment by blowmage** [comment]
I asked two questions. Which one are you saying "yes" to?

**Comment by blowmage** [comment]
In cases like this it is best to create a reliable reproduction that anyone can run on any system and see the behavior you suspect is a defect in the library. This means you have to post much more code for us to be able to recreate this. I suspect that this is not an issue with the library, but an issue in your setup, and the process of creating a reproduction would help you identify what needs to be changed in your setup.

That said, I suspect creating a reproduction might be outside your skillset right now. And GitHub Issues is probably not the right place to explain how to do this. The easiest way for us to help you is to do some remote pair programming where we can see your code and help you correct your problems. If you will email me at mike@blowmage.com we can schedule that.

**Comment by VincentVanGoat** [comment]
I have the gcloud dependency in my Gemfile. Sorry for being unclear :disappointed:

**Comment by blowmage** [comment]
Is a remote pair programming session a possibility? Is that something we can try?

**Comment by VincentVanGoat** [comment]
Yes. I'll send you an email about the same then.

**Comment by blowmage** [comment]
Excellent. Thanks!

**Comment by quartzmo** [comment]
@VincentVanGoat I will try to help. How are you installing the gcloud gem? Can you paste your exact commands into a comment?

**Comment by quartzmo** [comment]
I am going to assume the controller above is in a Rails application, using bundler. I'll try to reproduce...

**Comment by quartzmo** [comment]
I didn't have any problem using Gcloud in a fresh Rails application (Ruby 2.2.3, Rails 4.2.3). Here are the steps I took, using [rbenv](https://github.com/sstephenson/rbenv) and [rbenv-gemset](https://github.com/jf/rbenv-gemset). Not all console output is shown.

```
$ mkdir sandbox
$ cd sandbox
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ rbenv gemset init gcloud-rails
$ gem install bundler
$ gem install rails
$ rails new gcloud-rails
$ cd gcloud-rails
$ bundle inject 'gcloud' '0.2.0'
$ bundle install
$ bundle exec rails console
```

Then, in Rails console. Note that `require 'gcloud'` returns `false` because Rails already required it.

```
Loading development environment (Rails 4.2.3)
irb(main):001:0> require 'gcloud'
=> false
irb(main):002:0> gcloud = Gcloud.new "[hidden]", "/Users/quartzmo/gcloud.json"
=> #<Object:0x007fe283fc2188 @project="[hidden]", @keyfile="/Users/quartzmo/gcloud.json">
irb(main):003:0> storage = gcloud.storage
=> #<Gcloud::Storage::Project:0x007fe287820c00 ... 
```

Hopefully this helps!

**Comment by VincentVanGoat** [comment]
Hey! @quartzmo. I'll try this today and let you know. Thanks for all the help!

**Comment by VincentVanGoat** [comment]
Hey all, I did a fresh install of gcloud and ran 'bundle install'. Surprisingly, my code worked. Thanks for all the help!

**Comment by blowmage** [comment]
:+1: Glad you got it worked out!

**Comment by quartzmo** [comment]
Great to hear!
