### ISSUE TITLE
[Documentation Issue] Example code on BQ doesn't have highlighting

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#236]
http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Bigquery/Dataset.html

**Comment by blowmage** [comment]
This typo was fixed in other code examples, but missed in this file. I didn't find any other instances of this mistake.

**Comment by blowmage** [comment]
This is fixed now.

**Comment by blowmage** [comment]
More ammunition for GoogleCloudPlatform/gcloud-ruby#226...
