### ISSUE TITLE
Support `DATASTORE_DATASET` environment variable

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#237]
The gcloud SDK instructs users to use the `DATASTORE_HOST` and `DATASTORE_DATASET` environment variables. Add `DATASTORE_DATASET` to the list of environment variables that gcloud-ruby looks for.

[refs GoogleCloudPlatform/gcloud-common#24]

**Comment by quartzmo** [comment]
Just wondering: Is the value of `DATASTORE_DATASET` is always a Google Cloud Project ID? 

From the official Datastore [Sign Up](https://cloud.google.com/datastore/docs/activate) doc:

> Note: During the activation process, you will create a Cloud Project ID for your project. This ID value is used as the Dataset ID. The Dataset ID identifies the Cloud Datastore storage used for your project.

Or is it possible to create a Datastore Dataset with an ID other than a Project ID?

**Comment by blowmage** [comment]
The Datastore project ID and dataset ID will eventually be separate identifiers in a future version of the Datastore API. But for now they are the same.

**Comment by quartzmo** [comment]
OK, great, about to submit PR for this.
