### ISSUE TITLE
Storage File docs example could use real-world detail

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#238]
I got the following error while trying to use the example for downloading a file at the [top of the File class](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.3.0/lib/gcloud/storage/file.rb#L35). I was trying to download some Datastore backup files.

```
irb(main):027:0> all_files.each {|x| x.download "#{bucket.name}/#{x.name}"};nil
Errno::ENOENT: No such file or directory @ rb_sysopen - datastore-backups-d914dd52-7f99-4a74-8aa2-8cb15c25a05c//ahNzfm5vZGFsLWFsbWFuYWMtNzI1ckALEhxfQUVfRGF0YXN0b3JlQWRtaW5fT3BlcmF0aW9uGMGEPQwLEhZfQUVfQmFja3VwX0luZm9ybWF0aW9uGAEM.User.backup_info
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/storage/file.rb:210:in `initialize'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/storage/file.rb:210:in `open'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/storage/file.rb:210:in `download'
	from (irb):27:in `block in irb_binding'
	from (irb):27
```

I think the example implies that missing directories in the path will be created. (In this case, the bucket name directory.) Also, the file names created by the Datastore backup begin with a forward slash (`/`), so the example produces a double slash. Of course this may be an unusual case. I don't know how common it is for Storage files to begin with a slash.

```
irb(main):029:0> file.id
=> "datastore-backups-d914dd52-7f99-4a74-8aa2-8cb15c25a05c//ahNzfm5vZGFsLWFsbWFuYWMtNzI1ckALEhxfQUVfRGF0YXN0b3JlQWRtaW5fT3BlcmF0aW9uGMGEPQwLEhZfQUVfQmFja3VwX0luZm9ybWF0aW9uGAEM.User.backup_info/1440457327667000"
irb(main):030:0> file.name
=> "/ahNzfm5vZGFsLWFsbWFuYWMtNzI1ckALEhxfQUVfRGF0YXN0b3JlQWRtaW5fT3BlcmF0aW9uGMGEPQwLEhZfQUVfQmFja3VwX0luZm9ybWF0aW9uGAEM.User.backup_info"
```

I'm not very experienced with Storage yet and everything might be fine, just wanted to share what I observed.

**Comment by blowmage** [comment]
Did you create a directory with the name of the bucket? The download isn't going to creat the directory structure, just the file.

**Comment by blowmage** [comment]
You get this behavior in ruby by writing to a file path that has a directory structure that does not exist.

```ruby
File.write "dir-that-does-not-exist/hello.txt", "hello world!"
# => Errno::ENOENT: No such file or directory @ rb_sysopen - dir-that-does-not-exist/hello.txt
```

**Comment by quartzmo** [comment]
Yes, I know. I just think the example is misleading. My preference (as far as it is practical) is for examples that you paste in and they actually work. On this note, the global namespace for bucket names is at odd with examples like: `storage.create_bucket "my-bucket"`.

**Comment by quartzmo** [comment]
I think it's worth the additional complexity to add some supporting details like:

```
bucket = storage.create_bucket "my-bucket-#{SecureRandom.uuid()}"
...
Dir.mkdir bucket.name
...
```
So that the example actually works. Just my preference.

**Comment by quartzmo** [comment]
I shouldn't have added the `bug` label. This is just my opinion on the docs.

**Comment by blowmage** [comment]
Yes, this is why very generic names were used in the documentation. The problem with creating a random bucket name for the create example you referenced in your previous comment is that you can't use the exact same name when retrieving a bucket by its name like the code example you referenced in the issue's description does.

**Comment by blowmage** [comment]
> Also, the file names created by the Datastore backup begin with a forward slash (/)

A Storage file's name is just a string, but can behave like a path. It can include directory structures, but Storage isn't a real file system. It looks like the Datastore backup prepended "`/`" to the name of the file, which is perfectly okay to do. Or not to do. You just have to be aware of that when downloading the file.

**Comment by blowmage** [comment]
You can treat Storage files that follow a nested directory naming convention like a file system by passing the parent directory path in the `prefix` option:

```ruby
require "gcloud"

gcloud = Gcloud.new
storage = gcloud.storage
bucket = storage.bucket "my-bucket"
files = bucket.files prefix: "/backup-files/"
```
