### ISSUE TITLE
BigQuery table refresh

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#242]
In BigQuery we added `Job#refresh!` to update the data for the job. This has proven to be very useful, we should extend this to Table and View.

**Comment by blowmage** [comment]
I kinda wonder if we should refresh all the things... Thoughts?

**Comment by quartzmo** [comment]
The question is where to stop... I know Table makes sense because I find myself trying it in console, and feeling frustrated that it's not there. I say we add it to Table for now, and see where else we wish we had it.

**Comment by blowmage** [comment]
I meant being able to refresh a Storage Bucket and File, a Pub/Sub Topic and Subscription, and a Datastore Entity. Extending this pattern to more than just BigQuery.

**Comment by quartzmo** [comment]
Agreed. If you know where it's needed, let's do it.

Question: Any chance you want to go with `reload!` instead of `refresh!` if we are going to do this widely? Fewer characters and similar to http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-reload

**Comment by blowmage** [comment]
Currently Storage ACL and BigQuery Job use `refresh!`. Nothing in the public API uses `reload!`, although we can add an alias for it.

**Comment by quartzmo** [comment]
OK, I vote for adding a `reload!` alias.
