### ISSUE TITLE
Datastore refresh!

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#243]
Add a method to allow Entity objects to refresh the data from the API.

refs #242

**Comment by quartzmo** [comment]
Dataset doesn't need a `refresh!` method, does it? It seems like a stateless [repository](http://martinfowler.com/eaaCatalog/repository.html).

**Comment by blowmage** [comment]
Correct, Dataset doesn't need refresh. In my notes I just listed Entity. I don't know why I added Dataset to the issue. ¯\\_(ツ)_/¯

**Comment by quartzmo** [comment]
Right now, `Entity` doesn't implement the [ActiveRecord pattern](http://www.martinfowler.com/eaaCatalog/activeRecord.html), meaning that it doesn't contain the persistence logic needed for `refresh!`. This logic is in the repository, `Dataset`. Introducing a dependency on the `Dataset` singleton into `Entity` seems like a bad idea, and moving the logic (`to_gcloud_entities`, etc) into Entity is a big change. Any thoughts?

**Comment by quartzmo** [comment]
All I can think of is to add a `refresh` (no bang) method to `Dataset`:

```
key = Gcloud::Datastore::Key.new "ds-test", "thingie"
entity = dataset.find key

refreshed_entity = dataset.refresh entity
```

**Comment by jgeewax** [comment]
Why wouldn't I just use:

```ruby
refreshed_entity = dataset.find entity.key
```
?

**Comment by quartzmo** [comment]
@jgeewax I agree. If you are required to have both the repository and the entity to invoke it, refresh doesn't add much.

**Comment by jgeewax** [comment]
Sure -- but there's value (IMO) of having `entity.refresh!`, right..? I get that we don't want to make this too heavy, but if that's the case shouldn't we just deal with hashes all the time?

If we're going to do Entity objects, shouldn't it know how to save itself, and therefore refresh itself?

**Comment by quartzmo** [comment]
It sounds good to me. I want to hear what @blowmage thinks, he may know some backstory on the current design.

**Comment by blowmage** [comment]
I forgot that Entity doesn't hold a connection to the service. We would need to change the way Datastore is implemented to add an Entity#refresh! method. I say we put this issue on hold for now.

A bit of history, the original proposal for Datastore put forth the idea of a "model API" similar to lots of other ruby ORMs. It would allow for users to define classes that would be backed by Datastore entities. Something like this:

```ruby
class User
  include Gcloud::Datastore::Model

  property :name
  property :email
  property :age, :integer
end

mike = User.find "blowmage" # lookup by Key("User, "blowmage")
```

We were asked to put that on hold, and to implement the API we have now. When gcloud-ruby's Datastore implementation moves past the Repository pattern and allow entities to hold a connection and save and refresh themselves, I think it would make a lot of sense to also implement a Model API like the above.

**Comment by jgeewax** [comment]
Huge +1 to that.

An ORM should (ideally) live somewhere else. Nothing stopping us from doing
it, but putting the ORM inside gcloud-ruby might be a bit heavy...

**Comment by quartzmo** [comment]
Is it OK then to remove this issue from the 0.3.1 milestone?

**Comment by blowmage** [comment]
Yeah, remove it from 0.3.1.

**Comment by blowmage** [comment]
In late 2014 I made a couple attempts at a gcloud-model gem that would implement this Model API using the Datastore implementation in gcloud-ruby. (This was on the side and not part of working on gcloud-ruby.) I think the Model API is possible to do as an external library, I unfortunately never finished it.

Apologies for causing confusion by creating this issue. I didn't give it enough thought before creating it.

**Comment by quartzmo** [comment]
No prob! It was good for me to get more familiar with the Datastore impl.

**Comment by jgeewax** [comment]
Agreed -- no problem :)

**Comment by blowmage** [comment]
Closing as this isn't likely anytime soon.
