### ISSUE TITLE
Storage refresh!

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#244]
Add a method to allow Bucket and File objects to refresh the data from the API.

refs #242

**Comment by quartzmo** [comment]
Bucket looks pretty much immutable to me. I was thinking maybe a Bucket's Acl could use `refresh!`, but it already has it. File definitely can use `refresh!`. OK to remove Bucket from this issue?

**Comment by blowmage** [comment]
Bucket has data, its just not on the implementation yet. See #91. I say we implement it.

**Comment by quartzmo** [comment]
OK, great. So some/all of the mutable attributes in #91 will be on the bucket's `@gapi` object? In that case I'll go ahead.
