### ISSUE TITLE
Feedback requested for accessing property values

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#25]
How should Datastore's Entity behave when accessing properties that have not yet been set?

```ruby
entity = Gcloud::Datastore::Entity.new
entity["name"] = "John Jacob Jingleheimer Schmidt"
puts entity["name"] #=> John Jacob Jingleheimer Schmidt
puts entity["email"] #=> ???
```

The current behavior is to return `nil`. Another option is to raise an error.

IMO the behavior should be permissive. Consider the case of a projection query where entity records stored in Datastore have both name and email, but only name is projected in the query. In ActiveRecord the attributes that are not selected are set to `nil`.

```ruby
query = Gcloud::Datastore::Query.new.kind("User").select("name")
entities = Gcloud::Datastore.connection.run query
entities.each do |entity|
  puts entity["email"]
end
```

Thoughts?

**Comment by pcostell** [comment]
The next version of the API will have an explicit null value. So something to consider is that if entity[...] returns nil, there will be no way to distinguish between a set null value and a missing value.

**Comment by blowmage** [comment]
For the past month or so I've been thinking about differentiating between and entity not having a property vs. having a property with a NULL value. Closely related is how to remove a property from an entity vs. setting the property's value to NULL. First, a bit of background. Currently the Entity has a `properties` method that returns an array of arrays of the properties and values. But this is a read-only list, and modifications aren't possible.

```ruby
entity["name"] = "Mike"
entity["email"] = "mike@example.com"
entity.properties #=> [["name", "Mike"], ["email", "mike@example.com"]]
entity.properties.clear #=> []
entity.properties #=> [["name", "Mike"], ["email", "mike@example.com"]]
```

I'd like to change `properties` to return a hash-like object that can be inspected and modified:

```ruby
entity["name"] = "Mike"
entity["email"] = "mike@example.com"
entity.properties #=> {"name" => "Mike", "email" => "mike@example.com"}

# Check for a property that exists
entity.properties.exist? "name" #=> true
entity["name"] #=> "Mike"
entity.properties["name"] #=> "Mike"

# Check for a property that does not exist
entity.properties.exist? "age" #=> false
entity["age"] #=> nil
entity.properties["age"] #=> nil

# Deleting a property
entity.properties.exist? "email" #=> true
entity.properties.delete "email"
entity.properties.exist? "email" #=> false
entity.properties #=> {"name" => "Mike"}
```

Here is the my proposed API for this new property object:

* `PropertyStore#[] key`
* `PropertyStore#[]= key, value`
* `PropertyStore#read key`
* `PropertyStore#write key, value`
* `PropertyStore#exist? key`
* `PropertyStore#fetch key, &block`
* `PropertyStore#delete key, &block`
* `PropertyStore#each`

This object would also be responsible for normalizing keys to make sure they were always stored as strings but could be accessed as symbols.

```ruby
entity[:name] = "Mike"
entity[:email] = "mike@example.com"
entity.properties.exist? :name #=> true
entity.properties.exist? "name" #=> true
entity.properties #=> {"name" => "Mike", "email" => "mike@example.com"}
```

In the future I can also see this object being responsible for dirty tracking changes, so we don't have to update every property when saving an entity, only the properties that changed. This would be API-compatible with ActiveModel's dirty tracking. Thoughts?

**Comment by jgeewax** [comment]
:+1: from me.

**Comment by blowmage** [comment]
Please see #62.
