### ISSUE TITLE
Shorten URL for gcloud-java link

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-ruby#256]
gcloud-java is in the midst of cleaning up it's gh-pages branch, and part of that is making the URL shorter. The link on ruby's website to gcloud-java should be modified to http://googlecloudplatform.github.io/gcloud-java/ (removing "site/latest/").

**Comment by ajkannan** [comment]
@blowmage It seems like lib/rdoc/generator/gcloud/_header.html.erb in the `gcloud-rdoc` branch controls the link to gcloud-java from the docs pages.  However, if I modify the gcloud-java link in that file, that won't update the existing docs pages' links, right?  Do you have a recommendation on how to best modify the links in the existing docs pages?

**Comment by blowmage** [comment]
I'll take care of it, no problem. I was distracted all afternoon on another issue. :)

**Comment by ajkannan** [comment]
Great, thanks!

**Comment by blowmage** [comment]
K, the site links and the documentation links are updated now. Thanks for the heads up!
