### ISSUE TITLE
Manage Bucket Versioning

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#272]
Support management of a bucket's versioning setting. 

- [ ] Allow setting versioning during bucket creation:

```ruby
storage.bucket_create "new_todo_bucket", versioning: true
```

- [ ] Allow getting values using a well named method.

```ruby
bucket.versioning #=> false
```

- [ ] Allow setting a new value using a setter method.

```ruby
bucket.versioning = true
```

Calling this method makes an API call to update the value.

**Comment by quartzmo** [comment]
The getter will have a `?`: `bucket.versioning? #=> false`

**Comment by blowmage** [comment]
IMO it would be good for the getter to be without the `?`, and have an alias with the `?`.
