### ISSUE TITLE
Manage Bucket Logging Settings

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#274]
Support management of a bucket's logging settings.

- [x] Allow setting the values using bucket creation:

```ruby
storage.bucket_create "new_todo_bucket", logging_bucket: "todo_logging_bucket",
                                         logging_prefix: "todo_log_"
```

- [x] Allow getting the values from the bucket:

```ruby
bucket.logging_bucket #=> "todo_logging_bucket"
bucket.logging_prefix #=> "todo_log_"
```

- [x] Allow setting the website values:

```ruby
bucket.logging_bucket = "todo_logging_bucket"
bucket.logging_prefix = "todo_log_"
```

This will make two API calls. This will be addressed in a future issue to add the `update` method which can make both of these changes in a single API call:

```ruby
bucket.update do |b|
  b.logging_bucket = "todo_logging_bucket"
  b.logging_prefix = "todo_log_"
end
```

**Comment by quartzmo** [comment]
The update issue mentioned above is Issue #279.
