### ISSUE TITLE
DNS Project data representation

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#282]
Represent the [DNS project](https://cloud.google.com/dns/api/v1/projects) data, including the quota data.

**Comment by blowmage** [comment]
It doesn't look like gcloud-node pulls the [project resource](https://cloud.google.com/dns/api/v1/projects#resource) or has a way to convey the quota data to users. @jgeewax, is pulling the project resource and showing the quota something we should skip?

**Comment by jgeewax** [comment]
Quota info is lower priority for sure, so let's keep this towards the bottom of the list.

**Comment by blowmage** [comment]
Will do.

**Comment by quartzmo** [comment]
gcloud python is loading the DNS quotas: https://googlecloudplatform.github.io/gcloud-python/latest/dns-usage.html#project-quotas

**Comment by blowmage** [comment]
That makes me think we should have it then.

**Comment by quartzmo** [comment]
Closed by PR #338
