### ISSUE TITLE
DNS Project reload

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#283]
Allow a DNS project object to reload itself and the associated quota data.

```ruby
dns = gcloud.dns
dns.reload!
```

**Comment by quartzmo** [comment]
Does the quota data (or other properties) change frequently enough to justify this?

**Comment by blowmage** [comment]
Not sure. @jgeewax, who can we talk to about decisions like these? Is there someone on the DNS team?

**Comment by blowmage** [comment]
Not sure. @jgeewax, who can we talk to about decisions like these? Is there someone on the DNS team?

**Comment by jgeewax** [comment]
I pinged someone internally asking him to comment on the issue -- hopefully that can be our contact for DNS.

**Comment by quartzmo** [comment]
Closed by PR #338
