### ISSUE TITLE
DNS Record data

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#291]
Represent the [ResourceRecordSets](https://cloud.google.com/dns/api/v1/resourceRecordSets) data. These objects will be immutable, and should be easy for end users to create.

**Comment by quartzmo** [comment]
The gcloud-node [record test](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/test/dns/record.js) tests for following resource record types: `a`, `aaaa`, `cname`, `mx`, `ns`, `soa`, `spf`, `srv`, and `txt`. If anyone can suggest additional types, please post them here.

**Comment by blowmage** [comment]
See the [supported record types](https://cloud.google.com/dns/what-is-cloud-dns#supported_record_types).

**Comment by quartzmo** [comment]
Perfect, thanks @blowmage

**Comment by quartzmo** [comment]
@blowmage So, I think I now see that the record type support should be handled by #300 and #301 instead of this issue?

**Comment by blowmage** [comment]
Yeah, there is definitely a lot of work to be done to create a terrific experience working with records while using gcloud/dns, and it will probably be done outside of this particular issue.

**Comment by blowmage** [comment]
I do think that some time could be spent on thinking about the ease of creating record objects. Since these are value objects, and not remote resources like most things in gcloud, we will need a way to easily create new objects to be added (or removed). I think I would prefer something like:

```ruby
a_rec = zone.record "A", "example.com.", 86400, ["1.2.3.4"]
```

To something like this:

```ruby
a_rec = Gcloud::Dns::Record.new type: "A", name: "example.com.", ttl: 86400, rrdatas: ["1.2.3.4"]
```

Or:

```ruby
a_rec = Gcloud::Dns::Record.new.tap do |rec|
  rec.type = "A"
  rec.name = "example.com."
  rec.ttl = 86400
  rec.rrdatas = ["1.2.3.4"]
end
```

I have no set idea of what the ux should be like, just a notion that it could be great if we give it some thought and love.

**Comment by quartzmo** [comment]
Yes, regarding this request:

> should be easy for end users to create

Unlike the typical GCloud entity (such as a Zone), which is created by a factory method that calls an `insert` API method on the service, the Record is actually more of a value object. It does not have an `id` for example, cannot be retrieved using a `get` API method, and is always managed in a ResourceRecordSet. It seems like the most user-friendly experience might be to depart from factories, and allow it to be directly instantiated as a transient value object.

**Comment by quartzmo** [comment]
I was picturing this:

```ruby
unsaved_record = new Gcloud::Dns::Record "A", ["1.2.3.4"], name: "example.com.", ttl: 86400
unsaved_record_2 = new Gcloud::Dns::Record "MX", ["10 mail.example.com.","20 mail2.example.com."], name: "example.com.", ttl: 86400
change = zone.add_records [unsaved_record, unsaved_record_2]
```

The first two parameters in the constructor, `type` and `data`, are required. The `name` and `ttl` are optional.

**Comment by blowmage** [comment]
Makes sense.

My earlier point is that `zone.record` is less characters and easier to type than `Gcloud::Dns::Record.new`. So perhaps a `#record` helper method on Project and Zone would be useful.

**Comment by blowmage** [comment]
BTW, I don't know if `name` and `ttl` are optional. But I also don't know that they aren't.

I'm also not good at not avoiding to not write double negatives, and i'm not not good at not following non double negatives as well.
