### ISSUE TITLE
DNS Zone list Records

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#292]
A DNS zone object must be able to [list the records](https://cloud.google.com/dns/api/v1/resourceRecordSets/list) belonging to the zone. The records can be filtered by name and type. A maximum number of records to return can be set. The returned records can be paginated with a token. This will require a Record::List class.

**Comment by quartzmo** [comment]
Regarding:

> The records can be filtered by name and type. 

I am planning to do this via the [API method's optional params](https://developers.google.com/apis-explorer/#p/dns/v1/dns.resourceRecordSets.list) `name` **AND** `type`. But I happened to notice that the gcloud-node implementation [does its filtering client-side](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/dns/zone.js#L620-L624). @callmehiphop Do you have any background for us on this? Just thought I'd ask.

**Comment by callmehiphop** [comment]
I believe we went with client-side filtering to allow the user to provide multiple types to filter by, where as the upstream API looks like it only allows you to filter by a single type. Obviously it's not very efficient if the user only specifies a single type to filter by.. maybe @stephenplusplus can elaborate why we went this route?

**Comment by quartzmo** [comment]
Supporting multiple types is exactly what @blowmage guessed. Just thought I'd ask in case there was more to the story. Thanks.

**Comment by stephenplusplus** [comment]
> "Restricts the list to return only records of this type. If present, the "name" parameter must also be present. (string)"

It was this requirement that made it pretty inconvenient for a user to "just get the A records" or "mail records" etc, since all of their fully qualified domain names would be different.

**Comment by quartzmo** [comment]
Thanks @stephenplusplus!

**Comment by blowmage** [comment]
```ruby
zone.records.map { |r| ["A", "AAAA"].include? r.type }
```

**Comment by blowmage** [comment]
The `Zone#records` method as implemented now allows `name` and `type` to be passed in as optional parameters. I think these two should be promoted to named parameters to reflect their importance for querying records.

```ruby
class Zone
  def records name = nil, type = nil, options = {}
    # ...
  end
end
```

The current signature is:

```ruby
class Zone
  def records options = {}
    # ...
  end
end
```
