### ISSUE TITLE
DNS Zone bulk change Records

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#295]
A zone object must allow for multiple records to be added and removed in the same API call. This will return a Change object that can be used to track the status of the change.

**Comment by quartzmo** [comment]
The [Changes API documentation](https://cloud.google.com/dns/api/v1beta1/#Changes) for `v1beta1` states:

> As a best practice to prevent collisions with other changes, you should increment the serial number of your SOA record with each request to this method by sending a deletion and addition of the SOA record with your other changes.

We should research/test whether this is still required for `v1`, or if perhaps the service has automated it.

This comment also applies to #293, #294.
