### ISSUE TITLE
DNS replace records by criteria

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#298]
Instead of specifying the records that need to be deleted, allow users to specify the types of records to be removed and replaced.

```ruby
zone.replace "NS", [new_ns_record1, new_ns_record2]
```

**Update:** The example code should be:

```ruby
zone.replace "example.net"., "A", 18600, ["127.0.0.1"]
```

See the discussion below about this.

**Comment by jgeewax** [comment]
Definitely have a look at what we did on gcloud-node for this, it was a bit
of a discussion IIRC

**Comment by blowmage** [comment]
@jgeewax is that discussion somewhere we can see it? I didn't find many DNS issues on gcloud-node. But I may be poor at searching for it...

**Comment by jgeewax** [comment]
@stephenplusplus - do you recall where we had the debate about replacing
records in cloud DNS?

**Comment by quartzmo** [comment]
There is some discussion here: https://github.com/GoogleCloudPlatform/gcloud-node/pull/706

**Comment by quartzmo** [comment]
@jgeewax Is this likely to be the concern you meant to point us to?

> is it possible that not all of the records would be returned via getRecords and there would be additional records via nextQuery?

In that case, point taken: Be sure to fetch *all* matching records before making the call to replace.

**Comment by stephenplusplus** [comment]
I don't think there was much of a discussion about it. I just did it and you said something like "this is cool, just make sure you mention it's not atomic."

Here it is: https://github.com/GoogleCloudPlatform/gcloud-node/pull/706#discussion_r33977558

**Comment by quartzmo** [comment]
Thanks @stephenplusplus

**Comment by blowmage** [comment]
@stephenplusplus @callmehiphop Hey guys, can you give us some background on the use case for `replace()` removing _all_ records by type? What user problem is it solving?

**Comment by stephenplusplus** [comment]
My only direct experience with records has been pretty simplistic: updating the nameservers for my domains. When I was playing with the API while developing, I wanted to see how easy that would be, which is how I ended up with removing the records by type. Was it a bad idea?

**Comment by blowmage** [comment]
No, not at all! :) We were just curious where it came from. We are thinking about an option to auto-update the SOA record when changes are made, and we were curious where `replace()` came from. In order to auto-update SOA we will need to grab all records like `replace()` does. Thanks for the info!

**Comment by blowmage** [comment]
I've spent a fair amount of time looking into managing DNS records and how Google Cloud DNS behaves. My thinking has changed from the time this issue was first created. Google Cloud DNS does not allow multiple records to exist for a `name`/`type` combination, so replace can simply take the 4 records values, check if a record already exists, and them perform the add/remove. So the method signature would match the `Zone#record` signature:

```ruby
zone.replace "example.net"., "A", 18600, ["127.0.0.1"]
```

**Comment by blowmage** [comment]
Our intention is to allow multiple replacement calls within a single change request using `Zone#update` when passing a block:

```ruby
zone.update do
  replace "example.com.", "A", 18600, ["127.0.0.1"]
  replace "example.net.", "A", 18600, ["127.0.0.1"]
  replace "example.org.", "A", 18600, ["127.0.0.1"]
  replace "example.com.", "MX", 18600, ["10 mail.example.com"]  
  replace "example.net.", "MX", 18600, ["10 mail.example.com"]  
  replace "example.org.", "MX", 18600, ["10 mail.example.com"]  
end
```
