### ISSUE TITLE
DNS remove records by criteria

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#299]
Instead of specifying the records to be removed, provide the types of records to be removed

```ruby
zone.remove "NS"
```

**Comment by blowmage** [comment]
I've spent some time looking at this, and I think the best signature for `Zone#remove` is to provide `name` and `type`. The record can be looked up with those two arguments and then given to `Zone#update`.

```ruby
zone.remove "example.net.", "NS"
```

**Comment by quartzmo** [comment]
Agreed! This is how Cloud DNS manages resource records.
