### ISSUE TITLE
DNS import records from a file

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#300]

**Comment by quartzmo** [comment]
It looks like `Zone#import` will require an external dependency for zonefile parsing, just as [gcloud-node utilizes the `dns-zonefile` lib](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/dns/zone.js#L28). I am currently evaluating [boesemar/zonefile](https://github.com/boesemar/zonefile).

**Comment by blowmage** [comment]
I want to keep the dependencies to a minimum, but I agree with this approach. :+1:

**Comment by quartzmo** [comment]
Unfortunately, [boesemar/zonefile](https://github.com/boesemar/zonefile) does not have a license. The readme states: "based on Simon Flack Perl library DNS::ZoneParse", for which I found this [copyright summary](https://launchpad.net/ubuntu/trusty/+source/libdns-zoneparse-perl/+copyright).

**Comment by quartzmo** [comment]
Another unfortunate oversight in all three of Ruby zonefile libs that @blowmage identified is that they do not expose the "rrdata" as a single string, but instead immediately decompose it into object properties. This then requires recomposition [as done in gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/dns/record.js#L84-L97). Not too big a deal, but unfortunate.

**Comment by quartzmo** [comment]
@jgeewax The PR I have created for this issue adds a dependency on [boesemar/zonefile](https://github.com/boesemar/zonefile), which currently does not have a license. I have opened an issue on the project to add one.

**Comment by quartzmo** [comment]
Good news, the maintainer of the zonefile lib responded to my issue by [adding the MIT license] (https://github.com/boesemar/zonefile/commit/7062c06a430c7df416f1aba72a10e95a5ed20f360).

**Comment by blowmage** [comment]
:+1:

**Comment by jgeewax** [comment]
Awesome ! Great catch Mike

**Comment by jgeewax** [comment]
Whoops! I meant Chris! Sorry!

**Comment by quartzmo** [comment]
No prob!
