### ISSUE TITLE
DNS Modify records

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#319]
We have the ability to replace records (if they exist), but we also want to be able to modify an existing record. For instance, we want to be able to update the `ttl` without caring what `data`. Currently, we need to do something like this:

```ruby
existing_mx_record = zone.records(name: "example.com.", type: "MX").all.first
updated_mx_record = existing_mx_record.dup
updated_mx_record.ttl = 3600 # change the TTL
zone.update updated_mx_record, existing_mx_record
``` 

We would prefer it be this instead:

```ruby
zone.modify "example.com.", "MX" do |mx|
 mx.ttl = 3600 # change the TTL
end
```

**Comment by quartzmo** [comment]
Closed by PR #321
