### ISSUE TITLE
BigQuery: Table copy is not working if destination table does not exist

### ISSUE THREAD

**Issue by vitaliel** [GoogleCloudPlatform/gcloud-ruby#326]
Samples from the docs: http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Bigquery/Table.html#method-i-copy

```ruby
      ds = bigquery.dataset 'logging'
      # destination_table = ds.table "logs_week"

      5.times do |i|
        src = "logs2015092#{i}"
        table = ds.table src
        table.copy('logging.logs_week_test', create: :needed, write: :append)
      end
```
/Users/lz/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/table.rb:428:in `copy': undefined method `gapi' for "logging.logs_week_test":String (NoMethodError)

If I uncomment line 2 and use that variable I get 
/Users/lz/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/table.rb:428:in `copy': undefined method `gapi' for nil:NilClass (NoMethodError)

**Comment by quartzmo** [comment]
Thanks for reporting this @vitaliel. We will investigate it today.

**Comment by blowmage** [comment]
Hi @vitaliel, the ability to reference a table as a string was added to version 0.3.1, but the error line you shared confirms you are using 0.3.0. Can you try upgrading to 0.3.1 and see if that fixes this?

As for the second error you get when you uncomment line 2. That looks to be because the table "logs_week" doesn't exist yet. To send in a table object you will need to make sure the variable is not nil. You can try something like this for line 2:

```ruby
destination_table = ds.table "logs_week" || ds.create_table "logs_week"
```

**Comment by quartzmo** [comment]
I would be happy to try to improve the error messages today, @blowmage.

**Comment by blowmage** [comment]
Okay, gcloud could use some better messaging when methods are given a nil object for sure.

**Comment by vitaliel** [comment]
With 0.3.1 I get below error:
```ruby
      ds = bigquery.dataset dataset
      destination_table = "#{dataset}.logs_week"

      6.times do |i|
        src = "logs2015092#{i}"
        table = ds.table src
        table.copy(destination_table, create: :needed, write: :append)
      end
```

/Users/lz/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.1/lib/gcloud/bigquery/table.rb:520:in `copy': Required parameter is missing (Gcloud::Bigquery::ApiError)

**Comment by vitaliel** [comment]
It worked if I put project_id in destination_table:
```
destination_table = "#{project_id}:#{dataset}.logs_week"
```

Maybe we need to add documentation that for copy operation project id is required.

**Comment by quartzmo** [comment]
Thanks @vitaliel, this is very helpful! We will need to handle the case in which `table_id` and `dataset_id` are specified, but not `project_id`.

**Comment by blowmage** [comment]
The `project_id` is required for the API call to BigQuery, but the source table's `project_id` and `dataset_id` values _should_ be used when they are missing from the destination table string. Hmmm...

Thanks for your continued help. We'll get this fixed ASAP.

**Comment by blowmage** [comment]
I was able to recreate this. We will get a fix posted soon. Thanks again for your help and letting us know about this.

FWIW, the intention here is that if you are copying _within_ the same project and dataset you _should_ be able to only specify the table name in the string. But as you said you can specify the entire table string to workaround this bug for now.

**Comment by blowmage** [comment]
@vitaliel The fix for this has been merged into master. If you are using bundler you can change your dependency to this git repo. Otherwise, we will get this included in the release scheduled for this week.
