### ISSUE TITLE
Final review of DNS API by Google Cloud DNS team

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#339]
We need someone from the Google Cloud DNS team to perform a review of the DNS implementation in gcloud-ruby. The documentation is [available here](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Dns.html).

**Comment by blowmage** [comment]
@balajisam Is this something you can help us with?

**Comment by jgeewax** [comment]
/cc @balajisam -- any chance you can take a look and tell us if anything's completely backwards? 

@blowmage : Can you point him at the docs to review?

I'm going to set a 1-week timer, so if we don't hear anything, let's ship Oct 6.

**Comment by balajisam** [comment]
I have looked at the doc's and they are fine. I haven't had a chance to
test myself, however will do it shortly.

If I have to provide comments/ or edit myself in future, what's the
workable way?

**Comment by blowmage** [comment]
@balajisam Comments can be made on this issue. We will make any needed changes. Good to have you on board!

**Comment by blowmage** [comment]
@balajisam Have you had a chance to play with or test the code? We are eager to cut a release. ;)

**Comment by blowmage** [comment]
@balajisam We will plan on releasing tomorrow unless we hear from you.

**Comment by balajisam** [comment]
Please proceed Mike in releasing the new build. Thanks.

**Comment by blowmage** [comment]
Great! Thank you!
