### ISSUE TITLE
List Projects

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#342]
Include the ability to filter the projects [by criteria](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter) and paginate.

- [x] Allow searching for all projects:

```ruby
resource_manager.projects
```

- [x] Allow pagination on projects:

```ruby
projects = resource_manager.projects
projects.next? # Are there more pages?
projects.next # Get the next page of projects
projects.all # Get all pages of projects
```

- [x] Allow search on projects:

```ruby
production_projects = resource_manager.projects filter: "labels.env:production"
```

**Comment by blowmage** [comment]
I promoted the filter option to a named parameter, so you can instead do this:

```
production_projects = resource_manager.projects "labels.env:production"
```

**Comment by jgeewax** [comment]
What if I have a list of labels as a hash that I built up somewhere. Now I have to prepend "labels." to each key in the hash? That seems like a bummer... right?

**Comment by blowmage** [comment]
That's the syntax for the [filter option from the list API](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter). You can also filter on `id` and `name`.

What syntax would you prefer to see?

**Comment by jgeewax** [comment]
I don't think this is necessarily bad (it's what we do in Python for example).

I think it might be cool if eventually we could handle "labels" as a nested hash ... but no idea if that's a good idea...

**Comment by blowmage** [comment]
_nods_

I agree something better would be good, but I also don't know what it could be. :)

I've been moving fast on getting RM stubbed out, but I expect we will have some time to give it some TLC after.

**Comment by jgeewax** [comment]
Totally.

Ok, move along, nothing to see here ;)

**Comment by quartzmo** [comment]
Again for reasons of consistency, as with `name` and `labels` in #344, maybe the `filter` parameter should have been left an `options` param, as in the original example?

This is how it is done in [Bigquery::Project#jobs](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/bigquery/project.rb#L510):

```ruby
require "gcloud"

gcloud = Gcloud.new
bigquery = gcloud.bigquery

running_jobs = bigquery.jobs filter: "running"
```

**Comment by blowmage** [comment]
@jgeewax Thoughts? FWIW I am opposed to reverting 485e6c6f02d71527ec1763669620e0a6b631d361, so we need a tie breaker.

**Comment by quartzmo** [comment]
In case it sways anyone: https://robots.thoughtbot.com/ruby-2-keyword-arguments#keyword-arguments-vs-positional-arguments

**Comment by blowmage** [comment]
In ruby 2.0+ a method can have both positional and named arguments. Its no different than what we are doing with the options hash today.

**Comment by jgeewax** [comment]
I'm not sure who I'm siding with here, but I think the following is more clear to me as an outsider:

```ruby
projects = resource_manager.projects filter: "labels.env:production"
```

(https://github.com/GoogleCloudPlatform/gcloud-ruby/commit/485e6c6f02d71527ec1763669620e0a6b631d361#diff-62fdafe487a3890dedaf56be4d01b329L102)

What's unclear to me in that syntax is how I filter with multiple labels... and I'm no Ruby expert, but I'd expect the map to be an actual map, not a string looking like a map, so ideally...

```ruby
filters = { :labels => { :env => "production" } }
# or if we can't do nesting
filters = { "labels.env" => "production" }
# or (if we want multiple options)
filters = { "labels.env" => ["production", "prod"], "name" => "name" } # (production *or* prod) *and* name
projects = resource_manager.projects filter: filters
```

**Comment by quartzmo** [comment]
@jgeewax The rest API docs [give an example](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter), as Mike noted above: `labels.color:red label.size:big` (Note that the example contains a typo, `label.size` should be `labels.size`.)

BUT I do agree that a [query by example]() approach would be much nicer. I think the only question is how to query for the presence of a label, which can't be done by example. The rest API expression does it with `*` symbol.

**Comment by blowmage** [comment]
I've reverted 485e6c6. Let's move the discussion for improving the filter to #363.
