### ISSUE TITLE
Create New Project

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#344]
```ruby
require "gcloud"

rm = Gcloud.new.resource_manager
project = rm.create_project "my-new-project", "My New Project", env: :production
```

The signature for the method is `Manager#create_project(project_id, name, labels)`

**Comment by jgeewax** [comment]
What does the `env` do? Just curious. We don't have that (AFAIK) in the other implementations.

**Comment by quartzmo** [comment]
I see `environment` as an example for the `labels` map  in the docs, but that's all. https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects#Project

**Comment by jgeewax** [comment]
Got it -- those are the labels. Wasn't super clear reading the example --
didn't see the word "labels" anywhere. :-X

**Comment by blowmage** [comment]
Yeah, it is the labels. I created these issues in a hurry. I'll try to update them with more info.

**Comment by quartzmo** [comment]
It's just my opinion, but I think that for the "least surprise" we should stick to the convention so common in this library: a final `options` hash parameter. 

```ruby
require "gcloud"

rm = Gcloud.new.resource_manager
labels = { "env" => "production" } # or { env: :production }
project = rm.create_project "my-new-project", "My New Project", labels: labels
```

I do realize that the only option right now is `labels`. In isolation this may seem wrong, but in the context of the whole library, the benefits from consistency should be worth the tradeoff.

**Comment by jgeewax** [comment]
I'm +1 to @quartzmo

**Comment by blowmage** [comment]
Updated.

**Comment by blowmage** [comment]
The example is now:

```ruby
require "gcloud"

rm = Gcloud.new.resource_manager
project = rm.create_project "my-new-project", "My New Project", filter: {env: :production}
```

**Comment by quartzmo** [comment]
`filter`? How about `labels`?

**Comment by blowmage** [comment]
Typo, comment was updated 1 second after posting.

**Comment by quartzmo** [comment]
Since the second parameter, `name`, is [also listed as optional in the rest API docs](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects#Project), can it be changed to an `options` param as well?

**Comment by blowmage** [comment]
Updated again. The signature for the method is now `Manager#create_project(project_id, options)`

```ruby
require "gcloud"

rm = Gcloud.new.resource_manager
project = rm.create_project "my-new-project", name: "My New Project", labels: {env: :production}
```
