### ISSUE TITLE
Delete a Project

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#345]
- [x] Call delete on a project object:

```ruby
project = resource_manager.project "my-existing-project-123"
project.delete
```

- [x] Call delete with only a `project_id`:

```ruby
resource_manager.delete "my-existing-project-123"
```

**Comment by jgeewax** [comment]
Does `.project` make an API call or is it just a factory for a Project object?

**Comment by blowmage** [comment]
It makes an API call. We will have a delete on Manager that takes just the project_id. Similar to Manager#undelete.
