### ISSUE TITLE
Project Reload

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#350]
Allow a project to be reloaded. Useful for checking for state changes:

```ruby
require "gcloud"

rm = Gcloud.new.resource_manager
project = rm.project "my-existing-project"
project.active? #=> true
project.delete
project.reload!
project.active? #=> false
project.delete_requested? #=> true
project.reload!
project.delete_requested? #=> false
project.delete_in_progress? #=> true
```

**Comment by blowmage** [comment]
What happens if you call `reload!` on a project object that was deleted? The API will return a 404. Does `reload!` raise? Is there are 5th state for `deleted?`? Hmm....

**Comment by jgeewax** [comment]
I have an open request to have the `delete` API request return the updated project resource, so that the `reload` call shouldn't be required. If that happens, does that change anything here?

**Comment by blowmage** [comment]
No, we will handle that just fine with the API we've decided on. Will undelete also return a project resource?

**Comment by jgeewax** [comment]
That's the request -- we'll see whether they actually do it....

**Comment by blowmage** [comment]
I haven't been able to get permissions to actually create/update/delete projects, so I am having a really hard time figuring out what the API behavior is. I am unsure if the state is updated immediately after calling `delete`/`undelete`. If it is I think the project object should call `reload!` when calling `delete`/`undelete` to mimic the requested behavior. (We'd simply remove the `reload!` call when the API behavior changes.) But I haven't been able to check that so I didn't implement it yet.

**Comment by jgeewax** [comment]
Woah -- meaning... you haven't tested the code against prod?

You should be able to use `gcloud auth login` and do all of these things (CRUD projects) with the oauth2 token that gets generated there. No?

**Comment by blowmage** [comment]
I have created my user credentials using `gcloud auth login` and can list all the projects I have permissions to. But I cannot make changes or create new projects. The error I get is `The caller does not have permission`. Even on projects I create from the web UI.

**Comment by jgeewax** [comment]
So you can't create projects on cloud.google.com ? That's.... Weird.

**Comment by blowmage** [comment]
Sorry, that was confusing. I can create projects on the web UI, but I can't update those projects from gcloud-ruby.

**Comment by jgeewax** [comment]
Is it an issue with your code (and the token?) or an issue with the API?

**Comment by blowmage** [comment]
AFAICT it's an issue with my permissions. I don't believe it's a problem with the code or the API.

**Comment by jgeewax** [comment]
The API isn't a whitelisted situation at all. Are you able to do it with gcloud-python (or -node)?

**Comment by blowmage** [comment]
That was my next step. I ran out of time yesterday. I'll try to do that this weekend or on Monday.

**Comment by blowmage** [comment]
@jgeewax said:

> The API isn't a whitelisted situation at all.

Are you sure? The [official docs](https://cloud.google.com/resource-manager/) says "To access this API, contact either your account manager or our sales team." And I've found [this issue comment](https://code.google.com/p/google-bigquery/issues/detail?id=285#c2) that says that Resource Manager _is_ whitelisted. Right now my account not being whitelisted makes the most sense.

> Are you able to do it with gcloud-python (or -node)?

I've used the python gcloud client and gotten the same behavior.

```
☣ [gcloud-python] $ python
Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gcloud import resource_manager
>>> client = resource_manager.Client()
>>> for project in client.list_projects():
...   print(project)
... 
<Project: u'Mike Moore gcloud test 123' (u'mike-moore-gcloud-test-123')>
>>> project = client.fetch_project('mike-moore-gcloud-test-123')
>>> project.name
u'Mike Moore gcloud test 123'
>>> project.name = 'Mike Moore Gcloud Test 123'
>>> project.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/resource_manager/project.py", line 203, in update
    data=data)
  File "gcloud/connection.py", line 337, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 The caller does not have permission (PUT https://cloudresourcemanager.googleapis.com/v1beta1/projects/quotebin-gcloud)
```

**Comment by jgeewax** [comment]
Fair point -- I'll ping someone to get you whitelisted...

**Comment by blowmage** [comment]
Thanks!

**Comment by quartzmo** [comment]
@jgeewax Me too, please!
