### ISSUE TITLE
Final review of Resource Manager API by Google Cloud team

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#360]
We need someone from the Google Cloud Resource Manager team to perform a review of the Resource Manager implementation in gcloud-ruby.

* [Code](https://github.com/GoogleCloudPlatform/gcloud-ruby/tree/resource-manager)
* [Documentation](http://blowmage.com/gcloud-ruby/docs/master/Gcloud/ResourceManager.html)

**Comment by blowmage** [comment]
@jgeewax Do you know anyone from the Resource Manager team who can review the ruby implementation?

**Comment by blowmage** [comment]
@jgeewax My account is whitelisted and I've been able to verify the implementation behaves correctly. Is there someone to look at the docs and implementation and give us feedback?

**Comment by blowmage** [comment]
@jgeewax Can we plan on releasing next week unless we hear from someone on the Google Cloud Resource Manager team? Say the 28th?

**Comment by rae42** [comment]
two comments:
- get and list are now available to all users
- we have also added get and setiampolicy methods (only accessible to whitelisted customers as create and delete)

**Comment by charvesf** [comment]
Do you need us to review the code as well? I've reached out to my team to see if there are any Ruby enthusiasts that can take a look.

**Comment by quartzmo** [comment]
@charvesf That would be great! But in case no one responds, even someone unfamiliar with Ruby can review our [`connection.rb`](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/resource-manager/lib/gcloud/resource_manager/connection.rb) file to see if we've misunderstood something, or missed an opportunity to add something useful.

@rae42 We will update the docs for the general availability of `get` and `list`. Will we see the get and setiampolicy methods soon in [the REST API docs](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects)?

**Comment by quartzmo** [comment]
@rae42 Looking at [APIs Explorer](https://developers.google.com/apis-explorer/#p/cloudresourcemanager/v1beta1/), I also noticed the new (?) Organization resource.

**Comment by blowmage** [comment]
@rae42/@charvesf: Thank you for helping us. A few of other quick questions...

1) We noticed a typo on the official docs. The [`filter` param](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter) example shows a value of "labels.color:red label.size:big", but best we can tell it should be "labels.color:red labels.size:big". How can we get that fixed?

2) Is there any way to filter on a value that includes spaces? For example, can we filter on a project name that is "My App"? If so, how do we format the filter value to do that?

3) The [API Explorer](https://developers.google.com/apis-explorer/#search/cloudresourcemanager/cloudresourcemanager/v1beta1/) shows more API endpoints than just getIamPolicy and setIamPolicy. Are these other endpoints also something the gcloud library should support?

**Comment by rae42** [comment]
@quartzmo get and setiampolicy will be in public docs in December. 
Organization resource is still in early Alpha with very few trusted testers. We probably don't need to include it yet.

**Comment by rae42** [comment]
@blowmage 
1) I will file a bug to get our docs updated
2) I tried name:"<some app name with space>" and it seemed to work
3) mentioned above, let's leave out the organization resource for now

**Comment by quartzmo** [comment]
@rae42 Just to be clear, if we release this next week, is it ok to include `projects.getIamPolicy` and `projects.setIamPolicy`? We will not include Organization.

**Comment by blowmage** [comment]
@rae42 I'm glad to hear that we should be able to filter on values with spaces in them. However, in practice this doesn't seem to work. I have a project with a space in the name, and I am unable to filter on it, even with quotes. More information in [this comment](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/363#issuecomment-145159556). Can we get a bug filed for this as well?

**Comment by rae42** [comment]
@quartzmo synced with our eng and doc writing team. We don't mind you including the iam methods. Even though the project public docs don't include them, the IAM documentation already talks about these  methods: https://cloud.google.com/iam/docs/managing-policies

**Comment by quartzmo** [comment]
@rae42 I'm trying to update [our docs on accessing Resource Manager](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/resource-manager/lib/gcloud/resource_manager.rb#L85-L89), but I'm a little unclear on what we should state. You [mentioned above](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/360#issuecomment-150050564) that "get and list are now available to all users", but the official docs still say:

> To access this API, contact either your account manager or our sales team.

I know everything is in motion, but if we say now that get and list are generally accessible, what do we say now about enabling the API?

**Comment by quartzmo** [comment]
@rae42 Is the limited functionality of the API (list/get) accessible to all User accounts by default? If so, can we say so?

**Comment by rae42** [comment]
@charvesf to double check it is true (get and list are accessible to all). If so you can talk about it. We will update our docs in the next iteration.

**Comment by quartzmo** [comment]
Great, thanks @rae42 for the quick response!

**Comment by charvesf** [comment]
Yes, get and list are open to all.

**Comment by quartzmo** [comment]
@charvesf And unlike other APIs, there is no need to "enable" Resource Manager API in the Developers Console, correct? It is enabled by default?

**Comment by charvesf** [comment]
That is not true. get and list are part of the Resource Manager API and the
API must be enabled to use them. By default, it is disabled.

**Comment by quartzmo** [comment]
@charvesf And for end users, it can only be enabled by contacting "either your account manager or our sales team" (per current docs)? And for some users, it may be enabled without the user also being whitelisted (for methods beyond get and list)? Just trying to nail this down, thanks for your patience!

**Comment by charvesf** [comment]
No worries, Chris. To use get/list, you only need to enable the API. If you
want to use the other methods, you must enable the API and contact your
account manager or our sales team to be whitelisted.

**Comment by quartzmo** [comment]
How does an end user enable the API? I couldn't find it in Developers Console, and the official docs say only: 

> To access this API, contact either your account manager or our sales team.

**Comment by charvesf** [comment]
In Developer Console, click "APIs & Auth" in the left navigation. Search
for "Cloud Resource Manager" and click to enable the API.

**Comment by quartzmo** [comment]
OK, sounds great! I don't personally see it there (see screenshot below), but I'll assume it will be visible to end users. Thanks again, I think we're almost ready for a final review, with updated docs and IAM Policy additions.

![developers_console](https://cloud.githubusercontent.com/assets/205445/10678862/31b2c0ce-78d2-11e5-984a-f1ca15fe8e61.png)

**Comment by charvesf** [comment]
Sorry, my mistake. Click APIs & Auth, then click APIs, then search for
Cloud Resource Manager.

**Comment by quartzmo** [comment]
Yes, @blowmage also pointed that out to me. Thanks @charvesf, I believe everything is clear now.

**Comment by blowmage** [comment]
@rae42 / @charvesf: The [code](https://github.com/GoogleCloudPlatform/gcloud-ruby/tree/resource-manager) and [documentation](http://blowmage.com/gcloud-ruby/docs/master/Gcloud/ResourceManager.html) have been updated. Can you take a look again and let us know if there is anything else that is should be added?

**Comment by blowmage** [comment]
@rae42 / @charvesf: We would like to deploy the Release Manager implementation on Wednesday. We have added IAM policy and permissions. Can you please revisit the [code](https://github.com/GoogleCloudPlatform/gcloud-ruby/tree/resource-manager) and [documentation](http://blowmage.com/gcloud-ruby/docs/master/Gcloud/ResourceManager.html) and let us know if you have any concerns? Thanks!

**Comment by blowmage** [comment]
@rae42 / @charvesf: Just a reminder that we are going to accept the code at EOB and cut a release unless we hear from you soon. Thanks!

**Comment by rae42** [comment]
The link to documentation seems to be down

**Comment by quartzmo** [comment]
@rae42 Sorry about that, we used @blowmage's gh-pages yesterday to look at docs from a different gcloud-ruby branch. I just deployed the latest [gcloud-ruby Resource Manager docs](http://quartzmo.github.io/gcloud-ruby/docs/master/Gcloud/ResourceManager.html) to my own fork.

**Comment by blowmage** [comment]
I've updated my URL to show the latest RM docs as well.

**Comment by blowmage** [comment]
Apologies for the confusion.

**Comment by quartzmo** [comment]
@rae42 @charvesf We're going to release our  0.5.0 Resource Manager milestone this morning. Any issues can be addressed with patch releases, or in our next minor release, which should follow this one fairly soon.

**Comment by rae42** [comment]
I took a quick read through the updated docs. LGTM. Thanks for publishing them

**Comment by quartzmo** [comment]
Thanks @rae42, we appreciate the help! Please feel free to open a new issue if anything occurs to you. I'll close this one.
