### ISSUE TITLE
Call `reload!` after deleting/undeleting a project

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#364]
A project object should reload itself when calls to delete or undelete are successful.

See https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/350#issuecomment-144866580

**Comment by jgeewax** [comment]
Is there a way to stop this from happening? Aka, fire and forget?

**Comment by blowmage** [comment]
Yes. You can call `Manager#delete` and `Manager#undelete`.

```ruby
resource_manager.delete "my-existing-project-123"
```

```ruby
resource_manager.undelete "my-deleted-project-456"
```
