### ISSUE TITLE
Verify filter prefix for labels

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#365]
The [official docs](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter) show the example `labels.color:red label.size:big`. Verify that projects can be filtered by both `labels` and `label`. If not, fix the docs on gcloud-ruby and submit a doc fix to the Google Cloud docs.

**Comment by blowmage** [comment]
I've verified that `label` is not supported by the filter option. Correcting the ruby docs now.

@jgeewax How do we submit an issue on the [official docs](https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list#body.QUERY_PARAMETERS.filter) to get this corrected?

**Comment by jgeewax** [comment]
There should be a button somewhere on the page.... ?

**Comment by quartzmo** [comment]
I can't find one. But there is a rating widget with stars in the upper right corner!
