### ISSUE TITLE
Manage Bucket CORS with block-based DSL

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#375]
Support setting and updating a bucket's CORS settings with a block-based DSL. This issue was extracted from #273.

- [ ] Allow setting CORS using the DSL during bucket creation: (`add_rule` method signature is just a suggestion)

```ruby
storage.bucket_create "new_todo_bucket" do |cors|
  cors.add_rule 300, [ "http://example.org",
                       "https://example.org" ],
                [ "*" ],
                [ "Content-Type" ]
end
```

- [x] Allow the CORS settings on an existing bucket to be set using a DSL: (`add_rule` method signature is just a suggestion)

```ruby
bucket.cors do |cors|
  cors.add_rule 300, [ "http://example.org",
                       "https://example.org" ],
                [ "*" ],
                [ "Content-Type" ]
end
```

- [x] In the update method described in #279, I think it would feel natural to also support a nested block `cors` update, like so:

```ruby
bucket.update do |b|
  b.website_main = "index.html"
  b.website_404 = "not_found.html"
  b.cors do |cors|
     # possible method signature, not definite yet
     cors.add_rule 300, [ "http://example.org", "https://example.org" ], [ "*" ], [ "Content-Type" ] 
  end
end
```

**Comment by quartzmo** [comment]
After reading [Troubleshooting CORS-Related-Problems](https://cloud.google.com/storage/docs/cross-origin#Troubleshooting%20CORS-Related-Problems), I think the best signature for the proposed `add_rule` method would *require* `origin` and `method` arguments, but make the `response_headers` and `max_age` arguments optional, since they are not needed for simple use cases. These options will default to none and `1800` seconds, respectively. This default for `max_age` is based on the following statement, from the above document; but the value will be sent in the request, just in case.

> The default setting for <MaxAgeSec> is 1800 seconds (30 minutes).

**Comment by quartzmo** [comment]
Thus, update examples:

Rule for requests that do *not* require pre-flight.

```ruby
bucket.cors do |cors|
  cors.add_rule [ "http://example.org", "https://example.org" ], [ "GET", "POST" ]
end
```

Strings as well as arrays should be supported.

```ruby
bucket.cors do |cors|
  cors.add_rule "http://example.org", "GET"
end
```

Rule for requests that require pre-flight.

```ruby
bucket.cors do |cors|
  cors.add_rule "http://example.org", 
                "*", 
                response_headers: ["X-My-Custom-Header", "X-Another-Custom-Header"], 
                max_age: 300
end
```

The `response_headers` option should also accept a single string.

**Comment by blowmage** [comment]
I'm :+1: for this approach.

**Comment by quartzmo** [comment]
The service does not appear to validate the values passed in CORS rules. Responsibility seems to fall entirely on the user.

```sh
irb(main):032:0> b2.cors = [{"origin"=>["BAD"],"method"=>["BAD"]}]
=> [{"origin"=>["BAD"], "method"=>["BAD"]}]
irb(main):033:0> b2 = storage.bucket b2.name
=> #<Gcloud::Storage::Bucket:0x007ff6be0dfba8 ...>>
irb(main):034:0> b2.cors
=> [{"origin"=>["BAD"], "method"=>["BAD"]}]
```


Should the builder validate arguments in the same way that [Bigquery::Dataset::Access does](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/bigquery/dataset/access.rb#L410-L438)? For example, the `method` value has these known valid values:

> An HTTP method supported in this configuration. Valid values are GET, HEAD, PUT, POST, and DELETE.

The validations are pretty obvious, but please add to or correct them if you can:

* `origin` - possibly wildcarded URL with or without scheme or port; or `*`
* `method` - GET, HEAD, PUT, POST, or DELETE; or `*`
* `response_headers` - HTTP header regex
* `max_age` - non-negative integer

Or is this overkill?

**Comment by blowmage** [comment]
I wouldn't go overboard validating values. I think we want to pass values through untouched as much as possible. For example, the docs may be out of date and `PATCH` is also supported, even though it isn't in the list.

**Comment by quartzmo** [comment]
@blowmage OK, makes sense.
