### ISSUE TITLE
Documentation Issue with Storage::File#url 

### ISSUE THREAD

**Issue by openkava** [GoogleCloudPlatform/gcloud-ruby#377]
the file.url() is not correct   , if it not mean to be used as   url which can be view in web browser ,then  I sugguest add public url in thei class .

**Comment by quartzmo** [comment]
Thank you @openkava, you are right that the [current documentation](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.0/lib/gcloud/storage/file.rb#L95) for Storage::File#url could be much improved. I am working on some other things in Storage this week so it is a perfect time to fix it. I will also look for and fix the docs for similar `url` methods elsewhere.

**Comment by quartzmo** [comment]
@openkava thanks again. We have renamed the old method to prevent confusion, and added a new method, `File#public_url`, for your use case. This change is on schedule to be released this week in a new version of the library.
