### ISSUE TITLE
Rails tutorails with gem "gcloud"

### ISSUE THREAD

**Issue by sajjadmurtaza-ror** [GoogleCloudPlatform/gcloud-ruby#384]
Is there any source where i can learn rails with gem "gcloud"

**Comment by blowmage** [comment]
Hi @sajjadmurtaza-ror, thanks for the question. The Google Cloud's [Getting started with Ruby](https://cloud.google.com/ruby/) has an [example app](https://cloud.google.com/ruby/getting-started/hello-world) that uses `gcloud` in a rails app. The tutorial uses named branches, so the datastore service is added in the [2-cloud-datastore](https://github.com/GoogleCloudPlatform/getting-started-ruby/tree/2-cloud-datastore) branch, and storage service is added in the [3-cloud-storage](https://github.com/GoogleCloudPlatform/getting-started-ruby/tree/3-cloud-storage) branch. We'd love to know if this what you are looking for.

**Comment by sajjadmurtaza-ror** [comment]
@blowmage you are great. Its awesome.
But i have lot of question about Gcloud::Datastore. Because am new for it.
an i ask i you don't mind.

**Comment by jgeewax** [comment]
The best place for general questions like this might be StackOverflow.com
-- feel free to use that for high-level questions! :)

**Comment by sajjadmurtaza-ror** [comment]
Actually the Gcloud::Datastore community is not in huge number. Anyway thanks.

**Comment by blowmage** [comment]
Feel free to ask on StackOverflow or email me directly. Thanks!
