### ISSUE TITLE
Pub/Sub Topic Policy is returning nil

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/gcloud-ruby#395]
Looks like this isn't needed:
https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/d7870d074645a9b3b38c9d8dda133b60a8b66def/lib/gcloud/pubsub/topic.rb#L427

Here is what I get:
```
irb(main):051:0* resp.data
=> #<Google::APIClient::Schema::Pubsub::V1::Policy:0xe7fb44 DATA:{"etag"=>"BwUiutJSWn8=", "bindings"=>[{"role"=>"roles/viewer", "members"=>["serviceAccount:404066594503-j4825a3hq5k361sqvill049gc72qt3uf@developer.gserviceaccount.com"]}]}>
irb(main):052:0> resp.data["policy"]
=> nil
irb(main):053:0> resp.data.to_hash
=> {"etag"=>"BwUiutJSWn8=", "bindings"=>[{"role"=>"roles/viewer", "members"=>["serviceAccount:404066594503-j4825a3hq5k361sqvill049gc72qt3uf@developer.gserviceaccount.com"]}]}
irb(main):054:0> 
```

**Comment by blowmage** [comment]
Hi @jeffmendoza, thank you for opening this issue. It certainly looks like the IAM policy data structure has changed. We have been looking deeper into this and there may be even more changes as a result.

**Comment by blowmage** [comment]
This was closed when the PR was accepted, but there are more changes coming that will relate to this. Thanks again!
