### ISSUE TITLE
Pub/Sub Topic auto-create is confusing

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#401]
One of the issues with the current Pub/Sub design is the behavior of auto-creating topic objects. Currently, it is possible for the topic to create itself while publishing:

```ruby
topic = gcloud.pubsub.topic("not-yet-created")
topic.publish "Some message" # Topic is created in this call
```

A more verbose version of the same code is:

```ruby
topic = gcloud.pubsub.topic("not-yet-created", autocreate: true)
topic.publish "Some message" # Topic is created in this call
```

Having the creation occur on `Topic#publish` instead of `Project#topic` is confusing. Along with the proposed `Project#publish` in #400, we also propose streamlining the auto-create functionality by making the following changes:

* Set the default behavior for `autocreate` to `false`. The current default value is `true`.
* Create the record on the method that the `autocreate` option is specified on:

```ruby
topic = gcloud.pubsub.topic("not-yet-created", autocreate: true) # Topic is created in this call
topic.publish "Some message" # Message is published in this call
```

This will change performance, but `Project#publish` as defined in #400 will maintain existing performance. But the behavior is more inline with where we believe more developers expectations are.

**Comment by blowmage** [comment]
@stephenplusplus @tmatsuo Thoughts?

**Comment by blowmage** [comment]
@jeffmendoza Thoughts?

**Comment by jeffmendoza** [comment]
I like both of these changes. Defaulting autocreate to false seems like the more typical use case. Using `autocreate: true` to create then and there sounds great as well. Now we need one on `topic.subscription "name" autocreate: true` to automatically create a sub.

**Comment by tmatsuo** [comment]
LGTM

**Comment by blowmage** [comment]
@jeffmendoza The problem with using `autocreate` for a subscription is that a subscription is more than just the subscription name and the topic name. It can also include a `deadline` and `endpoint` configuration. And once the subscription is created it cannot be changed. The subscription would have to be deleted and recreated, and all pending messages would be lost. This is why we have avoided `autocreate` on all subscriptions.

**Comment by blowmage** [comment]
Here is the situation I am worried about for auto-creating Subscription:

```ruby
sub = gcloud.pubsub.subscription "existing-sub",
                                 topic: "my-topic",
                                 deadline: 30, 
                                 endpoint: "https://example.com/push",
                                 autocreate: true
sub.topic #=> "other-topic"
sub.deadline #=> 90
sub.endpoint #=> nil
```

I worry that users will continue to be confused by this design choice. Especially as misleading/confusing as the current auto-create behavior seems to be. So even though it is more explicit, I think it best that the code used to retrieve or create a subscription continues to look something like this:

```ruby
sub = gcloud.pubsub.subscription "my-sub"
sub ||= gcloud.pubsub.subscribe "my-topic", "my-sub",
                                deadline: 30, 
                                endpoint: "https://example.com/push"
```

**Comment by jeffmendoza** [comment]
So, to do both:
```ruby
topic = gcloud.pubsub.topic "my-topic", autocreate: true
sub = topic.subscription "my-sub"
sub ||= topic.subscribe "my-sub",
                                deadline: 30, 
                                endpoint: "https://example.com/push"
```

**Comment by blowmage** [comment]
Yep. But subscription names are unique within your project, so if the subscription already exists you likely don't need to also ensure that the topic does as well. What I want to do in addition to what was outlined above is add `Project#subscribe` with the `autocreate` option. With that method I think it would make much more sense to have the following:

```ruby
sub = gcloud.pubsub.subscription "my-sub"
sub ||= gcloud.pubsub.subscribe "my-topic", "my-sub",
                                deadline: 30, 
                                endpoint: "https://example.com/push",
                                autocreate: true # auto-create topic if needed
```

The `Project#subscribe` would still raise an error if the subscription name was already taken, just as `Topic#subscribe` does now.

**Comment by blowmage** [comment]
In #402 the auto-create behavior has moved to the `Project#topic` method, and the newly added `Project#publish` and `Project#subscribe` methods. Auto-creation of topics happens in those methods, and not later on in `Topic#publish` or `Topic#subscribe`. Hopefully this lessens the complexity of this feature by removing confusion about when a topic is created.
