### ISSUE TITLE
DelegateClass not found

### ISSUE THREAD

**Issue by jondot** [GoogleCloudPlatform/gcloud-ruby#403]
Hi guys,
Looks like there is a `require 'delegate'` missing, so that the standard library `DelegateClass` is not found when running a sample.
Any idea how the tests pass? anything I'm missing?

Thanks

**Comment by blowmage** [comment]
Hey @jondot, thanks for opening this issue!

You are absolutely right, we should `require "delegate"` whenever `DelegateClass` is used. It is obviously loaded by one of gcloud's dependencies, but gcloud's usage and dependency should be explicit.

I am unable to reproduce this, however. When I run `$bundle exec rake test` (or `$rake test` within a gemset) everything passes for me. Can you post what command you are running and the output it gives?

**Comment by jondot** [comment]
Yep. I think the way to reproduce is to run without running bundler. So I'm guessing you're right - in this case some of `gcloud-ruby`'s deps do that.

**Comment by blowmage** [comment]
We will definitely fix this, but it would be helpful if you could share your output. Either way, thanks again for opening the issue!
