### ISSUE TITLE
Query namespace and kind

### ISSUE THREAD

**Issue by jondot** [GoogleCloudPlatform/gcloud-ruby#404]
Hi guys,
Is there a way to specify a namespace for a query (like with the Node variant of gcloud)? I didn't find such a thing anywhere in the official docs.

Thanks

**Comment by blowmage** [comment]
Hey again @jondot. I've looked through the code and gcloud-ruby is not exposing the ability to specify namespace on a query. I'm confident we can add this and get it included in this week's release however. Here is what I was thinking:

```ruby
require "gcloud"

gcloud = Gcloud.new
dataset = gcloud.datastore
query = Gcloud::Datastore::Query.new
query.kind("List").where("active", "=", true)
active_lists = dataset.run query, namespace: "custom-ns"
```

Would that work for you? Or would you rather see a different design?

Thanks for opening this issue!

**Comment by jondot** [comment]
Yes, that should be great. This is what I hacked out myself just to get some data flowing and to verify that this is possible.
Thanks!

**Comment by jgeewax** [comment]
Is there a way we can throw in some hierarchy here so that people can pass around a namespace object that knows how to run queries? 

That is, the code might look like...

```ruby
require "gcloud"
gcloud = Gcloud.new
dataset = gcloud.datastore
namespace = dataset.namespace "mynamespace"
query = Gcloud::Datastore::Query.new
query.kind("List").where("active", "=", true)
active_lists = namespace.run query
```

Or is that not very ruby-esque ?

**Comment by jondot** [comment]
I think the namespace object you are referring to is a mirror of the protobuf PartitionId, in addition @blowmage suggested something that will be mirroring the API for gcloud Java and Node drivers, at least these were the ones we have evaluated.

**Comment by blowmage** [comment]
IMO its neither more or less ruby-esque that the previous example, just different. I'm somewhat on the fence about adding a separate `Namespace` class, but I'll think on it.

It looks like gcloud-node allows a default namespace to be set on the dataset object, so all queries run on the dataset will have the namespace applied. So it looks like you create separate Dataset instances with different default namespaces.

**Comment by blowmage** [comment]
Since we are discussing Datastore, I have had a thought on some expanded functionality that namespace might fit into very well. Currently we create a separate Query object and pass that to Dataset. What if we allow the Query to be built by chaining methods instead? So this:

```ruby
require "gcloud"

gcloud = Gcloud.new
dataset = gcloud.datastore
query = Gcloud::Datastore::Query.new
query.kind("List").where("active", "=", true)
active_lists = dataset.run query, namespace: "custom-ns"
```

Could also be expressed as this:

```ruby
require "gcloud"

gcloud = Gcloud.new
dataset = gcloud.datastore
active_lists = dataset.query("List").where("active", "=", true).namespace("custom-ns").run
```

Thoughts?

**Comment by jondot** [comment]
According to the docs namespaces were created to support multitenantship, so I guess the use cases should support that as well. I imagine a case where I have my queries safely tucked somewhere, and then I just criss-cross between tenants when needed, with the same query object.

When I think about that, then the first snippet is what I would feel most comfortable with.

I must also say, that when namespace is not use as a multi-tenantship mechanism (say as a mechanism to separate dev/prod/qa data), which might be considered a misuse, then there is a strong motivation not to be bothered with specifying the namespace each time and "configure" it within a connection or a dataset.

**Comment by quartzmo** [comment]
Based on my understanding (perhaps incomplete) of namespaces as a [mechanism to support multitenancy](https://cloud.google.com/appengine/docs/java/multitenancy/multitenancy), I think that we should allow the namespace to be set at a high level, then forgotten. Here is the Java example from that guide for setting per-user namespaces:

```java
if (NamespaceManager.get() == null) {
  // Assuming there is a logged in user.
  namespace = UserServiceFactory.getUserService().getCurrentUser().getUserId();
  NamespaceManager.set(namespace);
}
```

I think @jgeewax's example best supports this.

As for @jondot's suggestion that Queries might be stored for reuse across namespaces, it would be good to support that, but I do consider it secondary.  I see gcloud-node accepting the option in both `Dataset` and `Query` constructors, which still doesn't support Query reuse across namespaces, does it?. The guide above simply warns us not to do it:

>  By default, the datastore uses the current namespace setting in the namespace manager for datastore requests. The API applies this current namespace to Key or Query objects when they are created. Therefore, you need to be careful if an application stores Key or Query objects in serialized forms, since the namespace is preserved in those serializations.

I also +1 what @jondot just said about the chained method example smelling wrong. I can try to elaborate on that if anyone wants to pursue it.

**Comment by jondot** [comment]
@quartzmo I just read the node implementation, and it looks like they do store a namespace with a query, which is upsetting. I do feel that based on multi tenancy experience, most queries will be the same, and tenants will change.

With the Ruby implementation I definitely see it as an advantage to be able to just keep queries and re-run them when needed with a different tenant each time around.

I also like the Java example, which to me demonstrate a way to scope a namespace at the request level. This would also be great for a rack middleware. For that, I'd build some kind of context that includes contextual information that includes namespace. This same context I guess would also include auth information; so I see no obvious reason to crown a special NamespaceManager (not sure why the Java guys did that?) - I do wish to learn why that was done though..?

**Comment by quartzmo** [comment]
@jondot Will @jgeewax's proposal cover both of these use cases? If you "roll your own" NamespaceManager to create and set a Namespace instance for each tenant in Rack middleware, and use that Namespace instance to run the stored queries (which themselves have no knowledge of namespace), is everything covered?

**Comment by blowmage** [comment]
@jondot I agree with your line of reasoning. Adding an optional `namespace` option on `Dataset#run` has the least amount of surface change on the ruby Dataset API, and allows for the most flexibility. If that is available I can also see supporting a namespace on a Query and Dataset, but the namespace "closest to" the `run` invocation should be used. (`namespace` option on `#run` > `Query#namespace` > `Dataset#namespace`)

**Comment by quartzmo** [comment]
I think the Rack middleware use case is a very strong one. @jondot Do you think you could write up an api usage example/proposal in middleware and post it here?

**Comment by jondot** [comment]
@quartzmo I believe right now (based on my use case) @blowmage 's approach is most reasonable. @jgeewax 's approach looks like a scoped dataset. so in that code sample I would:

```
require "gcloud"
gcloud = Gcloud.new
users = gcloud.datastore
google_users = users.namespace "Google"
query = Gcloud::Datastore::Query.new
query.kind("List").where("active", "=", true)
active_lists = google_users.run query
```

Which is just naming things differently, however it makes explicit that `namespace` is just a modifier that builds a new scope.

To conclude - this approach is less generic than what @blowmage suggests, but it does cover the need. I would be less comfortable with it since it feels a bit narrow and recursive.

**Comment by quartzmo** [comment]
@jondot We will be happy to go with @blowmage's approach (an option on `run` as in your pr #406) if it works best for you. Let's continue discussion on your PR.

**Comment by jondot** [comment]
@quartzmo one more question - I'm running an experiment using GCE to talk to data store, we're seeing an issue with performance (latency of queries) - know anyone that can help out?
Thanks

**Comment by quartzmo** [comment]
@jondot: @jgeewax may be able to look into that.

**Comment by jgeewax** [comment]
Might be something to bring up on gcd-discuss@googlegroups.com ?
