### ISSUE TITLE
Create new Index object

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#414]
Indexes are searchable collections of documents.

```ruby
require "gcloud"

gcloud = Gcloud.new
search = gcloud.search

new_index = search.index "products"
```

**Important**: Indexes cannot be created, updated, or deleted directly on the server: they are derived from the documents which are created “within” them. The cannot even be retrieved except by `indexes.list` in the REST API.

Personally, I find it very easy to mistake this method for a lookup/retrieval, but if we follow the [implementation in gcloud-python](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/search/client.py#L96-L105), it only initializes an `Index` value object that holds a reference to the "Client" so that it can execute searches. Indeed, the REST API does not offer [`indexes.get`](https://cloud.google.com/search/reference/rest/v1/projects/indexes).

**Comment by jgeewax** [comment]
This will be changed in the API at some point (before it becomes generally available to to the public), so... eventually we'll have this as a thing...

**Comment by blowmage** [comment]
If the indexes are going to CRUD in the future then I think it would be wise to make the ruby API behave like they are connecting to a CRUD service. In #421 we simulate a `get` API by performing a list with the prefix, and then returning the index that matches the id exactly. This is not be as performant as a real `get`, but it does allow us to build the ruby API as if it were there.
