### ISSUE TITLE
Authentication question

### ISSUE THREAD

**Issue by malachheb** [GoogleCloudPlatform/gcloud-ruby#423]
it's possible to use a pkcs12 certificate (file.p12) for Authentication ?

**Comment by jgeewax** [comment]
I don't think so -- I think you can only use a JSON keyfile (which you can get from the Cloud Console).

**Comment by malachheb** [comment]
thinks for your quick reply, 
in fact I think it's possible to use a .pem key but not a pkcs12

```
 hash = {
   "token_credential_uri" => "https://accounts.google.com/o/oauth2/token",
   "audience" =>  "https://accounts.google.com/o/oauth2/token",
   "client_email" => "xx@developer.gserviceaccount.com",
   "private_key" => "file.pem"
 }
 gcloud = Gcloud.new("sample-data", hash)
```

**Comment by quartzmo** [comment]
@malachheb Can I close this issue?

**Comment by malachheb** [comment]
@quartzmo  yes
