### ISSUE TITLE
Investigate using gRPC for APIs that support it?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#430]
Any API that supports gRPC should also support JSON+REST, so we should first check if gRPC is available, if it is, use it, if not, fall back to JSON+REST.

**Comment by blowmage** [comment]
We have an issue generating the ruby protobuf source code used to call APIs using gRPC. This is a bit of a blocker. google/protobuf#1048

**Comment by jgeewax** [comment]
Any chance you guys can poke around at the latest version of grpc?

> So we've created our 0.13 working branch today, and I've released 0.13.0.pre1 Ruby packages out from it, alongside pre-compiled gems for Linux, Windows and MacOS, 32 and 64 bits (where applicable): https://rubygems.org/gems/grpc/versions
> 
> Since this is a `pre` version, you won't be able to install it with a simple gem install grpc. But you can use the --pre flag to grab it and test it if you need a gem install. Otherwise, you can also specify 0.13.0.pre1 as your gemspec dependency.
> 
> It's also dependent on google-protobuf which is also a native gem. We'll be released binary packages for it too probably tomorrow.

**Comment by quartzmo** [comment]
@jgeewax Great news. Thanks for the heads up!

**Comment by blowmage** [comment]
Fantastic! I'm all over this. Hope to update with good news soon!

**Comment by blowmage** [comment]
Quick update, I have the prerelease gem in gcloud-ruby and can make calls with it. Unfortunately, it is causing a segfault when running the acceptance tests. But this only happens on my gcloud-ruby WIP branch; I can't get a clean reproduction of the segfault. So progress is slow going, but encouraging.

**Comment by blowmage** [comment]
We are nearing completion of implementing GRPC in gcloud-ruby. Closing.
