### ISSUE TITLE
Add cloud logging support

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcloud-ruby#438]
We've had a few customers ask about logging to google cloud from Ruby applications.  It would be great if we could support cloud logging.  

https://cloud.google.com/logging/docs/api/

We should make sure to work with the cloud logging team (they will have feedback on which API to use).

**Comment by quartzmo** [comment]
@JustinBeckwith Great to hear you can report interest in this, because @blowmage has been pushing for us to support it, and afaik it is the next new service that we will tackle.

**Comment by JustinBeckwith** [comment]
Sweet.  You'll want to chat with @andreweames on the logging team - let me know how I can help!

**Comment by quartzmo** [comment]
@JustinBeckwith We are starting work today on support for Cloud Logging (v2beta1) in gcloud-ruby! 

I'm closing this original issue, as it has been replaced by finer-grained ones in the [0.7.0 milestone](https://github.com/GoogleCloudPlatform/gcloud-ruby/milestones/0.7.0%20-%20Logging).

/cc @andreweames

**Comment by JustinBeckwith** [comment]
Great news!

**Comment by quartzmo** [comment]
@JustinBeckwith We are really excited to get after this one. We have issues for Ruby Logger compatibility (#505) and for some docs demonstrating Rails integration (#506). If there are any additional issues you can suggest, please do so!
