### ISSUE TITLE
Generate docs to gcloud-common JSON

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#452]
In order to leverage a shared site design for all gcloud projects, per [gcloud-common #33](https://github.com/GoogleCloudPlatform/gcloud-common/issues/33), Ruby API documentation and guides need to be generated to a common JSON format. Currently there is no spec, just this early-stage [example](https://gist.github.com/callmehiphop/f5f7e51de2b0d0d20fde).

The target location for the JSON documents will be specified in [gcloud-common #42](https://github.com/GoogleCloudPlatform/gcloud-common/issues/42).

The most likely solution requires switching from RDoc to [YARD](https://github.com/lsegal/yard), and converting all existing API documentation to use YARD's [Tags](http://www.rubydoc.info/gems/yard/file/docs/Tags.md).

This issue closes #191, which will no longer be needed with a single site.

**Comment by quartzmo** [comment]
@callmehiphop @stephenplusplus Can close this issue as done, based on [our current JSON output](http://googlecloudplatform.github.io/gcloud-ruby/versions/master.json)? We would close it with the understanding that (as discussed today with @jgeewax) we will need to continue to do work as needed to keep up with the ongoing development of the custom JSON format. Or do you see more work that we can do right now?

Please note that (as @blowmage explained [on gcloud-common #42](https://github.com/GoogleCloudPlatform/gcloud-common/issues/42#issuecomment-168091176)) we are currently building our json to the following path: `/gcloud-ruby/versions/<version>.json`, as in: `/gcloud-ruby/versions/master.json`.

**Comment by stephenplusplus** [comment]
It's probably safe to close. We can keep talking through the specifics in the other various issues we have.

**Comment by quartzmo** [comment]
Thanks @stephenplusplus!
