### ISSUE TITLE
Convert gh-pages doc site to JSON-based Angular app

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#454]
Once a new version of the [gcloud-node gh-pages](https://googlecloudplatform.github.io/gcloud-node) Angular [app](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/docs/site/home.js) is available, and all API docs generate JSON for it, convert the [gcloud-ruby gh-pages](https://googlecloudplatform.github.io/gcloud-ruby) site to the new architecture.

This issue depends on [gcloud-common #33](https://github.com/GoogleCloudPlatform/gcloud-common/issues/33).

**Comment by quartzmo** [comment]
@callmehiphop Will there be a separate gcloud-common issue for delivering a new version of the gcloud-node Angular app that works with the new shared JSON format?

**Comment by callmehiphop** [comment]
There's currently a PR open on gcloud-common (https://github.com/GoogleCloudPlatform/gcloud-common/pull/34) but I haven't pushed anything to it yet.

**Comment by quartzmo** [comment]
Closing this issue, since distribution of the Angular app is covered by [gcloud-common PR #35](https://github.com/GoogleCloudPlatform/gcloud-common/pull/35).
