### ISSUE TITLE
Generate docs to static HTML using gcloud-yard template

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#466]
We may need a YARD template, similar to the gcloud-rdoc template used for the current RDoc formatted documentation. This would help us bridge the gap between generating HTML documentation files that we do now, and moving to the JSON-backed angular application sometime in the future. Tags before the YARD conversion would use gcloud-rdoc, and tags after the conversion would use gcloud-yard.

**Comment by quartzmo** [comment]
@blowmage I agree this would be great, as it would allow us to merge our YARD branch into master without having to wait on the Angular app. How much work do you think it would be?

**Comment by blowmage** [comment]
¯\_(ツ)_/¯

**Comment by blowmage** [comment]
:laughing: I'm not sure how much time it would take, but I bet it can be done by the time the YARD conversion is merged to master.

**Comment by quartzmo** [comment]
I think it's a good idea, and will pay off in terms of the time it saves us maintaining the branch.

**Comment by blowmage** [comment]
This is complete.
