### ISSUE TITLE
[Documentation Issue] Authentication page needs to be updated to reflect the new Credentials UI

### ISSUE THREAD

**Issue by vsubramani** [GoogleCloudPlatform/gcloud-ruby#472]
The Credentials UI in Google Developers Console has been updated. Some of the things to be updated:

-The nav hierarchy has changed. The phrases are different, but still recognizable with the old hierarchy.
-New credentials wizard has been added to help guide the users to the right credential type.

Please update the Getting Started -> Authentication in gcloud-ruby to reflect these changes.

**Comment by blowmage** [comment]
Thanks for the issue @vsubramani!
