### ISSUE TITLE
Add coverage reports to travis build

### ISSUE THREAD

**Issue by silvolu** [GoogleCloudPlatform/gcloud-ruby#49]

**Comment by blowmage** [comment]
Do you want to use [Coveralls](https://coveralls.io) for this?

**Comment by silvolu** [comment]
Yeah, that's how we did it in the other gcloud projects.

**Comment by blowmage** [comment]
Do you want the coverage for the unit tests, regression tests, or a combination of both?

**Comment by silvolu** [comment]
I would add both; that is at least what we do in the other projects.

**Comment by blowmage** [comment]
I've got a branch that _should_ work, but I'd like to test it to make sure. What is needed to configure travis to work with coveralls?

**Comment by silvolu** [comment]
On coveralls, you need to sign in and enable access to the repo; I've already done it for gcloud-ruby, but if you want to try on your fork, you'll have to enable access to it.
