### ISSUE TITLE
Replace optional params with yielded object?

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#490]
We have a couple methods in Storage that have a long list of optional parameters.

* [`Project#create_bucket`](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Storage/Project.html#method-i-create_bucket)
* [`Bucket#create_file`](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Storage/Bucket.html#method-i-create_file)

About half of these parameters could be removed if we yielded the object to be created before the API call was made. This means that instead of making a call like this:

```ruby
require "gcloud"

gcloud = Gcloud.new
storage = gcloud.storage

bucket = storage.create_bucket "my-bucket",
                               location:       "US",
                               logging_bucket: "example-logs-bucket",
                               logging_prefix: "log_object_prefix",
                               storage_class:  "NEARLINE",
                               versioning:     true,
                               website_main:   "index.html",
                               website_404:    "404.html" do |c|
  c.add_rule ["http://example.org", "https://example.org"],
             "*",
             response_headers: ["X-My-Custom-Header"],
             max_age: 300
end
```

We could make a call like this instead:

```ruby
require "gcloud"

gcloud = Gcloud.new
storage = gcloud.storage

bucket = storage.create_bucket "my-bucket" do |b|
  b.location       = "US"
  b.logging_bucket = "example-logs-bucket"
  b.logging_prefix = "log_object_prefix"
  b.storage_class  = "NEARLINE"
  b.versioning     = true
  b.website_main   = "index.html"
  b.website_404    = "404.html"
  b.cors do |c|
    c.add_rule ["http://example.org", "https://example.org"],
               "*",
               response_headers: ["X-My-Custom-Header"],
               max_age: 300
  end
end
```

I think the latter call is a significant improvement. And functionally equivalent. All data is sent on the single API call to create the resource. And this approach is used in [`Bucket#update`](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Storage/Bucket.html#method-i-update) and [`File#update`](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Storage/File.html#method-i-update) so it should be familiar to users. But this would break the existing API. What do you think? Is this a change we should make?

**Comment by quartzmo** [comment]
Are there other methods with long parameter lists that could be improved in this way in the other services?

**Comment by blowmage** [comment]
The only other candidate I have found so far is BigQuery's [`Project#create_dataset`](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Bigquery/Project.html#method-i-create_dataset). Where this:

```ruby
require "gcloud"

gcloud = Gcloud.new
bigquery = gcloud.bigquery

dataset = bigquery.create_dataset "my_dataset",
                                 name: "My Dataset",
                                 description: "This is my Dataset" do |access|
 access.add_writer_user "writers@example.com"
end
```

Could be replaced with:

```ruby
require "gcloud"

gcloud = Gcloud.new
bigquery = gcloud.bigquery

dataset = bigquery.create_dataset "my_dataset" do |ds|
  ds.name = "My Dataset",
  ds.description = "This is my Dataset" do |access|
  ds.access do |access|
    access.add_writer_user "writers@example.com"
  end
end
```

But there might be more. I haven't looked too deeply until I got some feedback on the idea first.

**Comment by quartzmo** [comment]
OK, great. Not sure how to prioritize this but it's something we definitely want to address before 1.0. (I wonder if we need an issue label for things required for 1.0?)
