### ISSUE TITLE
Support PUBSUB_EMULATOR_HOST environment variable

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#491]
gcloud-ruby should support the ~~`PUBSUB_HOST`~~ `PUBSUB_EMULATOR_HOST` environment variable and connect to service specified in it. This will enable connecting to an emulator running locally, similar to how the Datastore emulator works.

See GoogleCloudPlatform/gcloud-common#48

**Comment by quartzmo** [comment]
I believe the correct variable should be `PUBSUB_EMULATOR_HOST`, per the official docs' [Setting environment variables](https://cloud.google.com/pubsub/emulator#env). gcloud-node also [now uses](https://github.com/GoogleCloudPlatform/gcloud-node/blob/v0.29.0/lib/pubsub/index.js#L592-L594)  `PUBSUB_EMULATOR_HOST`.

**Comment by quartzmo** [comment]
See GoogleCloudPlatform/gcloud-node#1125 for the complete gcloud-node change for this variable name.

**Comment by quartzmo** [comment]
@dlorenc Be aware that in our next release, the gcloud-ruby Pub/Sub client will be using gRPC instead of Rest.

@hbchai commented that [the Pub/Sub emulator also supports gRPC](https://github.com/GoogleCloudPlatform/gcloud-common/issues/48#issuecomment-178270491). (I haven't tested it yet.)

**Comment by dlorenc** [comment]
Thanks for the update!

**Comment by dlorenc** [comment]
Any updates here?

**Comment by quartzmo** [comment]
@dlorenc We are still working on #314.

@blowmage Do you think we can add this issue to the Datastore v1beta3/GRPC milestone? Do you have any time now to work on it?

**Comment by blowmage** [comment]
If we get this implemented then we may want to put it in a pout release before Dataset/GRPC, since we don't know when that will be ready to be released.
