### ISSUE TITLE
ResourceDescriptor type

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#503]
See [MonitoredResourceDescriptor](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/monitoredResourceDescriptors/list#MonitoredResourceDescriptor).

**Comment by blowmage** [comment]
Reopening because we have discovered we can't use the Resource class for both Resource and ResourceDescriptor.
