### ISSUE TITLE
API Compatibility with Ruby Logger

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#505]
See the Ruby Logger [docs](http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html) for the API.

**Comment by blowmage** [comment]
I think the [Logger API](http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html) will be sufficient for normal ruby usage. But we may consider an additional Logger implementation for rails integration, to automatically add the HttpRequest information when available. I haven't looked to deeply at that yet.

One difference between Google Cloud Logging and the Ruby Logger is the types of severity. I think we should map the following ruby severities to Google Cloud. Ruby code won't be attempting to log to the unmatched severities, so we may not need to support them. But if we do, we should make it clear in the documentation that those methods are not part of the Ruby Logger API.

| Ruby Logger | Google Cloud |
| ----------- | ------------ |
| unknown     | DEFAULT      |
| debug       | DEBUG        |
| info        | INFO         |
|             | NOTICE       |
| warn        | WARNING      |
| error       | ERROR        |
| fatal       | CRITICAL     |
|             | ALERT        |
|             | EMERGENCY    |

We don't have the same formatting concerns, so we might consider not implementing the `formatter` attribute as [shown in the description here](http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html). Some documentation seems to be missing, so the `formatter` attribute might be part of [Logger::Formatter](http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger/Formatter.html). Either way, I think we can leave it out.

[Log4R](http://log4r.rubyforge.org) is an older, mostly compatible API compatible implementation. It offers more customization on how logs are written and formatted. Where the standard library Logger and Log4R overlap looks like where we should focus on.

**Comment by quartzmo** [comment]
Out of `CRITICAL`, `ALERT`, and `EMERGENCY`, is `CRITICAL` the most appropriate match for `fatal`, or did `fatal` just land on the first in the list?

> Where the standard library Logger and Log4R overlap looks like where we should focus on.

By the above, you mean that the overlap describes an API that omits standard library Logger's formatting functionality? If so, sounds good to me.

**Comment by blowmage** [comment]
I think the Ruby Logger's `datetime_format` falls into the same category as `formatter`. Not needed for Google Cloud, so it should be left off.

If we have those methods, we might consider either documenting that they are there only for compatibility, or possibly not documenting them. Either way, any ruby code that calls them would be calling a "no op" method.
