### ISSUE TITLE
Logging Guide, and README and OVERVIEW examples

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#513]
Add Logging examples to the list of services covered by gcloud on README and OVERVIEW.

**Comment by quartzmo** [comment]
Added Guide (logging.rb docs) to issue title.

**Comment by quartzmo** [comment]
@JustinBeckwith We are trying to provide a realistic Ruby example for Cloud Logging [entries.write](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/write).  Can you suggest which [monitored resource](https://cloud.google.com/logging/docs/api/introduction_v2#monitored_resources) would be appropriate? Below is the current list from [monitoredResourceDescriptors.list](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/monitoredResourceDescriptors/list), with the required `label` keys in the parentheses.

```sh
gce_instance (instance_id, zone)
gae_app (module_id, version_id)
cloudsql_database (database_id, region)
gce_disk (disk_id, zone)
vpn_gateway (gateway_id, region)
api (service, version, method, location)
global ()
dataflow_step (job_id, step_id)
app_script_function (invocation_type, function_name)
dataproc_cluster (cluster_id, zone)
bigquery_resource ()
container (cluster_name, namespace_id, instance_id, pod_id, container_name, zone)
http_load_balancer (forwarding_rule_name, url_map_name, target_proxy_name, backend_service_name, zone)
gce_target_pool (target_pool_id, zone)
gce_firewall_rule (firewall_rule_id)
gce_forwarding_rule (forwarding_rule_id, region)
gce_network (network_id)
gce_route (route_id)
gce_reserved_address (reserved_address_id)
gce_autoscaler (autoscaler_id, zone)
gce_backend_service (backend_service_id)
gce_health_check (health_check_id)
gce_url_map (url_map_id)
gce_project (project_id)
gce_snapshot (snapshot_id)
gce_target_http_proxy (target_http_proxy_id)
gce_target_https_proxy (target_https_proxy_id)
gce_target_http_instance (target_http_instance_id, zone)
logging_log (name)
logging_sink (name)
metric (name)
testservice_matrix (matrix_id)
```

**Comment by JustinBeckwith** [comment]
Probably a better question for @mr-salty

**Comment by quartzmo** [comment]
@mr-salty For purposes of a documentation example, can you suggest a realistic [monitored resource](https://cloud.google.com/logging/docs/api/introduction_v2#monitored_resources) type that a Ruby application developer might reference when [writing log entries](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/write) using the Cloud Logging API?

**Comment by quartzmo** [comment]
We decided the safest choice of monitored resource type for [a user-generated log entries example](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/logging.rb#L240-L242) was `"gae_app"`. But we can always change it, just let us know.

**Comment by mr-salty** [comment]
gce_instance is another possibility but I think gae_app is fine as well.
