### ISSUE TITLE
Document storage

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-ruby#53]
I'd like to use this for uploading files to google cloud storage and notice there's some code hanging around for it but it's not documented in the README or [the docs](http://googlecloudplatform.github.io/gcloud-ruby/docs/). Perhaps storage is not yet feature complete, so also wondering on ETA for it. Thanks! :+1:

**Comment by blowmage** [comment]
Storage is in active development, and is able to create/delete buckets and upload/download files now. The [documentation](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Storage.html) is a bit rough ATM but will be improved shortly as well. If you have any questions feel free to ask.

**Comment by ryanseys** [comment]
Thanks, I'll take a look.
