### ISSUE TITLE
Cloud datastore find entities exclude_from_indexes is set to true

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/gcloud-ruby#537]
If I retrieve an entity from a local gcd-emulator using Gcloud::Datastore with the find method as follows:
```ruby
require 'gcloud/datastore'
dataset = Gcloud.datastore

key = Gcloud::Datastore::Key.new('Person', 4697113673859072)
key.parent = Gcloud::Datastore::Key.new('AccountPerson', 5742310809665536)
entity = dataset.find(key)
```
the _exclude_indexes is set to true for all properties.

Example:
```ruby
@_exclude_indexes={"name"=>true}
```
If I change the value of a property on the entity and save it back to the datastore:
```ruby
entity['name'] = 'different'
dataset.save entity
```
I can no longer query for the entity as all properties have been set to unindexed.

**Comment by blowmage** [comment]
Thanks for the issue @bmclean, are you seeing this behavior against the Google Cloud Datastore service as well? Or is it just on the gcd-emulator?

**Comment by bmclean** [comment]
This problem occurs against the actual Google Cloud Datastore service as well.

**Comment by bmclean** [comment]
Once all of the properties have been set to unindexed, if I perform the find command again the @_exclude_indexes has all properties set to False. The @_exclude_indexes seem to be inverted.

**Comment by bmclean** [comment]
I think the problem is in the update_exclude_indexes! method within entity.rb:
```ruby
def update_exclude_indexes! entity #:nodoc:
  @_exclude_indexes = {}
  Array(entity.property).each do |property|
    @_exclude_indexes[property.name] = property.value.indexed
    unless property.value.list_value.nil?
      exclude = Array(property.value.list_value).map(&:indexed)
      @_exclude_indexes[property.name] = exclude
    end
  end
end
```
The property.value.indexed refers to whether the property is indexed or not.
```ruby
<Gcloud::Datastore::Proto::Property name: "name", value: <Gcloud::Datastore::Proto::Value string_value: "different", indexed: true>>
```
However, it gets set as the value for the excluded_index.

**Comment by blowmage** [comment]
I spent some time looking at this over the weekend. I hope to have an update on this later today. Thanks for your patience.

**Comment by bmclean** [comment]
Hi @blowmage, is there anything else I can do to help?

**Comment by bmclean** [comment]
I walked through the code starting from:
`entity = dataset.find(key)`
Within the find method in lib/gcloud/datastore/dataset.rb:
`find_all(key).first`
Within the find_all method in lib/gcloud/datastore/dataset.rb:
`entities = to_gcloud_entities response.found`
Within the to_gcloud_entities method in lib/gcloud/datastore/dataset.rb it iterates over the entities calling:
`Entity.from_proto result.entity`
Within the self.from_proto in lib/gcloud/datastore/entity.rb:
`entity.send :update_exclude_indexes!, photo`

This line of code within the update_exclude_indexes! method:
`@_exclude_indexes[property.name] = property.value.indexed`
takes the property.value.indexed (which is correctly set as true) and sets it as the value of the _exclude_index (meaning that index is now excluded).
Does the value just need to be inverted?
`@_exclude_indexes[property.name] = !property.value.indexed`
