### ISSUE TITLE
Block is not called with arg(s) as doc'd

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#546]
The last doc example for [`Entity#exclude_from_indexes!`](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.6.1/lib/gcloud/datastore/entity.rb#L246) shows the method passing the property value(s) as a parameter to the block argument, but I do not see this [in the code](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.6.1/lib/gcloud/datastore/entity.rb#L249):

The example:

```ruby
entity["age"] = 21
entity.exclude_from_indexes! "age" do |age|
   age > 18
end
```

**Comment by blowmage** [comment]
[That method](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.6.1/lib/gcloud/datastore/entity.rb#L249) simply stores the block as a Proc object to be used for that field name. The value is [passed to the Proc object here](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.6.1/lib/gcloud/datastore/entity.rb#L294-L295), but this happens after all the field values are stored and right before saving.

**Comment by quartzmo** [comment]
Now I understand it! Thank you for linking that together for me.
