### ISSUE TITLE
Logging List#all

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#561]
The Logging List objects should have the `#all` method, similar to [other List objects](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Search/Index/List.html#method-i-all).

**Comment by blowmage** [comment]
Calling `#all` on log entries will run forever, so I wonder if this is a good idea or not...

**Comment by quartzmo** [comment]
I don't think we should feel compelled to add an `all` method to every List implementation. Currently I only see 5 such methods in the 18 List classes.

```
        gcloud-ruby  (5 usages found)
            lib/gcloud/dns/record  (1 usage found)
                list.rb  (1 usage found)
                    (61: 9) def all
            lib/gcloud/resource_manager/project  (1 usage found)
                list.rb  (1 usage found)
                    (58: 9) def all
            lib/gcloud/search/document  (1 usage found)
                list.rb  (1 usage found)
                    (50: 9) def all
            lib/gcloud/search/index  (1 usage found)
                list.rb  (1 usage found)
                    (55: 9) def all
            lib/gcloud/search/result  (1 usage found)
                list.rb  (1 usage found)
                    (57: 9) def all
```

**Comment by blowmage** [comment]
But I'm so consistently in favor of consistency...

**Comment by quartzmo** [comment]
In that case, we need an issue or issues to add `all` to the 13 List classes that are missing it.

**Comment by blowmage** [comment]
Don't encourage my foolish consistency... :)
