### ISSUE TITLE
Paginating Log Entries must include selection criteria

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#566]
According to the [v2beta1 REST docs](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/list#body.request_body.FIELDS.page_token), paginating entries must include the `projectIds`, `filter`, and `orderBy` parameters. These values are not sent when paginating log entries using `Entry::List#next`.

**Comment by quartzmo** [comment]
To be clear, in my reading `filter` and `orderBy` are not required fields, but "must be the same as in the previous request", meaning that if they are null in the first request, they must remain null.

**Comment by quartzmo** [comment]
It looks like `Project#entries` declares a default value of `nil` for `projects`, which is inconsistent with "required" in [the doc for `projectIds`](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/list#body.request_body.FIELDS.project_ids).

**Comment by quartzmo** [comment]
Never mind, I understand now, the minimum requirement for a projectId is satisfied the enclosing project.
