### ISSUE TITLE
Get final review of Datastore API by GCD team from Google

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#57]
Datastore stuff we probably need to have covered:

We should be able to...

- [x] get an entity (or set of entities) by key
- [ ] ~~run a GQL query~~
- [x] build a query using operations like `.filter()`, `.order()`, etc
- [x] iterate over items in a query (including multiple pages)
- [x] delete an entity (or set of entities)
- [x] update properties on an entity using ruby-ish semantics 
- [x] save an entity (update)
- [x] perform an operation (or set of operations) inside a transaction using ruby-ish semantics
- [x] manually roll-back a transaction

We may have more to add...

**Comment by jgeewax** [comment]
@blowmage : Added a checklist at the top here.. if these things aren't done, can we create issues to track their progress? I'd consider all of these "necessary" to call our Datastore code "stable".

Are there any things that should be on this list which I'm forgetting? I just took a rough pass at this...

**Comment by blowmage** [comment]
This is a great set of features and gives me some ideas for how to improve the documentation.

The only feature not in the current implementation is running a GQL query. I was told GQL was being phased out and we weren't going to support it in gcloud-ruby. @silvolu can probably explain it better than I.

**Comment by silvolu** [comment]
It's never on the roadmap, and my understanding was that we would not do it. More than being phased out, it's never been included in project. In previous reviews from the Datastore team, the absence of GQL was not mentioned.

**Comment by jgeewax** [comment]
@blowmage : Can you open issues for anything that's remaining and then close this issue?
