### ISSUE TITLE
Add support for Cloud Vision and Translate

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/gcloud-ruby#576]
I would like to do a talk at RailsConf that uses Cloud Vision and Translate APIs. Can those be added sometime in the next month?

**Comment by quartzmo** [comment]
@blowmage and I would really love to see this happen. It would be so fantastic to have this exposure through RailsConf. We were not going to start on these services for about a month, but can you give us a few days to see if we can juggle things around? When is your absolute deadline for delivery (provided that we could do up-front planning with you, and commit earlier to the API details required for your talk)?

**Comment by thagomizer** [comment]
RailsConf is May 4th. Ideally I'd have the code done and ready to test by April 25th. I don't think there will be much code so give me a day or two before that?

Vision seems to only have one REST endpoint that I can find in the docs (https://cloud.google.com/vision/reference/rest/). Translate is less important since I only have one example for it in the talk. I'll be using the BigQuery APIs as well. 

If you want to see the abstract for the talk ping me at thagomizer @ google.com and I'll share the doc with you.

**Comment by quartzmo** [comment]
@thagomizer You're right about Vision only having one method on a single resource, but there is a lot of surface area in [images.annotate](https://cloud.google.com/vision/reference/rest/v1/images/annotate). Give us until Monday afternoon to do a spike on it to make sure there are no blocking issues, and to discuss some other deliverables. I'll email you now for the abstract.

**Comment by quartzmo** [comment]
@thagomizer I read the abstract, what a great, fun idea! If the video of the talk catches on, I think it will succeed in getting a lot of people excited to try out Vision via gcloud-ruby.

**Comment by blowmage** [comment]
Vision was added in 0.10.0 and Translate was added in 0.8.0.
