### ISSUE TITLE
Code highlighting style in markdown does not match gcloud-common site

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#583]
@jgeewax [wrote](https://github.com/GoogleCloudPlatform/gcloud-common/pull/102#issuecomment-196584874):

> Btw looks like syntax highlighting on the overall docs (
https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/resourcemanager)
doesn't have the grey background? is that on purpose?

The API-level code examples (grey background) are rendered in the Angular app with [highlightjs](https://highlightjs.org/), which has Ruby syntax support. The "overview" code examples are fenced code blocks in markdown that we process at the time we build the JSON, using Pygments. As I [commented here](https://github.com/GoogleCloudPlatform/gcloud-common/pull/65#issuecomment-183401939), Pygments is *much* more popular in our community, and we think it does a better job-- but for the sake of consistency we should probably process our markdown so that highlightjs can work with it.

**Comment by blowmage** [comment]
I think it would be easier to get pygment's CSS to match highlightjs' CSS.

**Comment by quartzmo** [comment]
Here is a comparison of Ruby highlighting:

With [Highlight.js](https://highlightjs.org/):

![ruby-highlightjs](https://cloud.githubusercontent.com/assets/205445/13797363/a012b67e-ead2-11e5-8b51-efc82b50c4f1.png)

With [Pygments](http://pygments.org/):

![ruby-pygments](https://cloud.githubusercontent.com/assets/205445/13797365/a7831700-ead2-11e5-9f47-6fe573d9f2eb.png)

I think the Pygments highlighting is much nicer than that of Highlight.js for Ruby, and suspect it may be a better choice for other languages as well. However, for consistent Pygments highlighting in the gcloud-ruby site, all code examples would need to be processed when the JSON is generated, not afterward, so it may not be compatible with the broader goals of publishing API docs in JSON.
