### ISSUE TITLE
Pub/Sub Get/Set/Test Project IAM

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#588]
It is possible to work with IAM policies and permissions for topics and subscriptions, but not the project. For instance, there is no way to check for permissions for creating a topic, since that is done on the project. We should allow _all_ roles to be get/set and tested on a Pub/Sub project.

**Comment by quartzmo** [comment]
@blowmage I implemented this using gRPC. But when I try to get the Policy for the current project, I get this error:

```sh
irb(main):002:0> policy = pubsub.policy
Gcloud::InvalidArgumentError: 3:This service cannot be used to manage the permissions of resources of type project. Please find the appropriate service to do so. See https://cloud.google.com/iam/docs/#supported_cloud_platform_services.
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/project.rb:517:in `rescue in policy'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/project.rb:512:in `policy'
	from (irb):2
```

**Comment by blowmage** [comment]
Right. The Pub/Sub service allows only Topic and Subscription to get/set an IAM Policy, and testing permissions. That is why the current Pub/Sub implementation does not have policy implemented on Project. Users would have to use either the IAM service, or Cloud Resource Manager, to manage a project's policy. I was hoping that the move to gRPC would allow these calls to be made on the IAM service, but this turned out not to be the case.
