### ISSUE TITLE
Generate docs on successful Travis-CI build

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#59]
We want the docs in the gh-pages branch to be updated on a successful build of the master branch.

We are running the build for each commit against multiple versions of Ruby, and while there are hooks for a successful individual build, there is no hook yet for a total successful build. We don't want to generate the docs for each version of Ruby, just once for the commit. The solution needs to take this into account.

The implementation should use the `GH_OAUTH_TOKEN`, `GH_OWNER`, and `GH_PROJECT_NAME` environment variables for updating the gh-pages branch. The implementation should also commit the updated docs using `"travis-ci" <travis@travis-ci.org>`.

We would prefer this is implemented as a rake task instead of a bash script.

**Comment by jgeewax** [comment]
I believe this is all completed, right?

**Comment by blowmage** [comment]
No, there are complications with Travis that were never resolved. Still too buggy.

**Comment by jgeewax** [comment]
OK, what can we do to sort this out?

**Comment by blowmage** [comment]
I couldn't get this to work reliably, so I set it aside. I'll look at it again, perhaps some fresh eyes will help.

I suspect this may be better handled as a third party integration with Travis than as part of the script running on Travis. I've seen somewhat erratic behavior in my tests for doing this in the script. Another complication is that the post/success hook fires on Travis for every version of ruby, but we only want to build the docs once. That makes it impossible to know if the build was successful for every version of ruby.

We have the same issues for generating and pushing the new gem to rubygems.org, which is also a manual process right now.

**Comment by jgeewax** [comment]
That's weird. The gcloud-node and gcloud-python guys have this all under control. Maybe @ryanseys can help ?

**Comment by blowmage** [comment]
The travis documentation build seems to be working as of f1a92ea7b542950ba83c31b79c896b847cec936d.
