### ISSUE TITLE
Does gcloud-ruby include IAM support for all services currently supporting it?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#591]
Gcloud should support IAM wherever possible.

There is a list of IAM [Supported Cloud Platform services](https://cloud.google.com/iam/#supported_cloud_platform_services), but we should also examine the docs for any services in gcloud-ruby that are not listed, just to double-check for recently-added IAM resources.

/cc @jgeewax

**Comment by quartzmo** [comment]
It looks like we should be able to offer IAM management for the resources listed below. @blowmage will follow up with specific issues.

##### Logging resources

The Logging [access control documentation](https://cloud.google.com/logging/docs/access-control) states: "Stackdriver Logging uses Google Cloud IAM roles to control access to logging resources." Since the Logging API does not document get/set/test IAM methods, we will try to implement these using the top-level `google.iam.v1` endpoint.

##### Pub/Sub Project resource

With out soon-to-be-released transition to gRPC, the top-level [google.iam.v1](https://cloud.google.com/pubsub/reference/rpc/google.iam.v1) endpoint should make it possible to get/set/test IAM configuration for `Project`, which did not expose these verbs with REST.

**Comment by blowmage** [comment]
Here are the issues added for this: #592, #593, #594, #595.
