### ISSUE TITLE
Update Datastore examples with snippets for cloud.google.com

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#601]
For consistency with GoogleCloudPlatform/gcloud-common#105, update all Datastore API doc examples to use the Ruby snippet examples for cloud.google.com/datastore. Hopefully, all examples can be adapted from [gcloud-node samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/datastore/concepts.js).

Since the snippets have not yet been created for Ruby, I am thinking that we should write them first as API docs, so that they can be included in the gcloud-ruby update for Datastore v1beta3 (PR #600). This means merging the examples in gcloud-ruby before they are accepted into [GoogleCloudPlatform/ruby-docs-samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples), at the risk of some rework if changes are requested later.

/cc @pcostell

**Comment by quartzmo** [comment]
@pcostell Status update: With PR #621, I added all but a couple of the requested snippets, including the [GQL examples](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/datastore/lib/gcloud/datastore/gql_query.rb#L32-L34), to gcloud-ruby API docs. I am now preparing a PR to add them as tested code to [GoogleCloudPlatform/ruby-docs-samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples).

**Comment by pcostell** [comment]
Thanks for the update @quartzmo.

/cc @WalterHub
