### ISSUE TITLE
Test GRPC Datastore against updated emulator

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#604]
The updated emulator can be downloaded [here](https://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip).

**Comment by quartzmo** [comment]
As @jgeewax [noted](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/610#issuecomment-206319556) in #610, it is vital that our emulator support handles error conditions clearly, in order to minimize user frustration while attempting to connect to the emulator.

**Comment by quartzmo** [comment]
Updates to our emulator support should permit [insecure access](http://www.grpc.io/docs/guides/auth.html#ssl-tls-for-server-authentication-and-encryption-ruby), without custom work of the sort that @bmclean [helpfully provided](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/610#issuecomment-205062500).
