### ISSUE TITLE
Document usage with Datastore emulator

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#615]
As [reported](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/610#issuecomment-205424753) by @samkelly:

> would also be great if the documentation specifically talks about there even being an emulator and how to connect to it from ruby -- was sort of buried

Currently the only documentation is in [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/CONTRIBUTING.md#local-datastore-devserver). It uses the earlier name "Datastore Devserver", and does not link to [usage instructions](https://cloud.google.com/datastore/docs/tools/datastore-emulator) for the emulator.

**Comment by samkelly** [comment]
Yes, fun fact I originally had a separate project set up server side just to run my datastore tests /facepalm

**Comment by quartzmo** [comment]
@samkelly also [suggested](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/610#issuecomment-206956064):

> Maybe when there is a datastore error, gcloud_ruby should suggest looking at the emulator log
