### ISSUE TITLE
Support direct execution of GQL

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#616]
Because the [GQL reference](https://cloud.google.com/datastore/docs/apis/gql/gql_reference) is included in the official Datastore documentation (and @pcostell has requested some GQL snippets as part of #601), we should allow the direct execution of GQL queries for clients who wish to use it.

I recommend that we implement this as soon as possible, in order to include usage examples in #601.

**Comment by pcostell** [comment]
Just a heads up that most of the other gcloud libraries don't support GQL, so I wouldn't block the v1beta3 version of the library on this (but definitely a nice to have, so if you have time while the proto library gets a new gem, this is awesome!)

**Comment by quartzmo** [comment]
@pcostell Agreed. Although I added this to the milestone, and we don't expect it to take too much time, neither this issue nor #601 will block our v1beta3 release.

**Comment by samkelly** [comment]
I would also like to see this

**Comment by blowmage** [comment]
@samkelly You are in luck! #600 was just updated with GQL support.

**Comment by blowmage** [comment]
This was implemented and will be released with the v1beta3 support. Closing.

**Comment by quartzmo** [comment]
@pcostell I noticed that the page https://cloud.google.com/datastore/docs/apis/gql/gql_reference still states:

> Note: Google Cloud Client Library for Java supports GQL, but other Google Cloud client libraries do not.

**Comment by pcostell** [comment]
Thanks for catching this -- I'll file a bug internally.
