### ISSUE TITLE
Support setting ReadOptions

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#618]
An example requested in #601 demonstrates setting eventual consistency in [ReadOptions](https://cloud.google.com/datastore/reference/rpc/google.datastore.v1beta3#google.datastore.v1beta3.ReadOptions). We do not currently expose `ReadOptions` in either `lookup` or `run_query`.

Should we support setting `ReadOptions` in gcloud-ruby?

/cc @pcostell @jgeewax

**Comment by quartzmo** [comment]
@blowmage @pcostell @jgeewax I have finished all of the code example snippets requested in #601, except for `eventual_consistent_query`, which depends on this feature. Thoughts?

**Comment by blowmage** [comment]
I would like to know this as well. 😄

**Comment by quartzmo** [comment]
From the [example on cloud.google.com/datastore](https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency#datastore_read_policy), it appears that only gcloud-java and gcloud-golang support this currently.

**Comment by pcostell** [comment]
We should support setting it (it's in the API after all!).

In the meantime though, it would be ok for the snippets to just be a comment that says "gcloud-ruby doesn't currently support setting read options."

**Comment by quartzmo** [comment]
@pcostell Thanks, sounds good.

**Comment by blowmage** [comment]
We can probably get this implemented before the next release.

**Comment by blowmage** [comment]
So the way I read this we can implement this with minimal changes to the public API by modifying `Dataset#lookup` and `Dataset#run` to add a `consistency` optional argument that can be either `:strong` or `:eventual`. The ruby code will take care of setting the transaction since it manages that anyway. Thoughts?

**Comment by blowmage** [comment]
```ruby
require "gcloud"

gcloud = Gcloud.new
dataset = gcloud.datastore
query = dataset.query("List").
  where("active", "=", true)
active_lists = dataset.run query, consistency: :eventual
```

**Comment by pcostell** [comment]
Seems reasonable. One thing to note is that when you set the consistency
you can only go down (so you can make a strongly consistent (ancestor)
query eventually consistent, but you can't force an eventually consistent
query to be strongly consistent.

**Comment by blowmage** [comment]
@pcostell Can you set eventual consistency if you don't have a transaction?

**Comment by pcostell** [comment]
Yes (Lookup and RunQuery with ancestor are both strongly consistent, regardless of transaction). In fact, inside of a transaction you can't set the ReadConsistency -- it has to be strong.

**Comment by quartzmo** [comment]
Here's the snippet, which is realistic in that otherwise the ancestor query would be strongly consistent:

```ruby
gcloud = Gcloud.new
datastore = gcloud.datastore

ancestor_key = Gcloud::Datastore::Key.new "TaskList", "default"

query = datastore.query("Task").
        ancestor(ancestor_key)

tasks = datastore.run query, consistency: :eventual
```

**Comment by blowmage** [comment]
Oh, I think I understand now. So when a lookup or query is ran _inside_ a transaction we should set the ReadOptions's `transaction`, but when a lookup or query is ran _outside_ of a transaction we can allow ReadOptions's `read_consistency` to be set?

**Comment by pcostell** [comment]
correct!

**Comment by blowmage** [comment]
Got it. I'll do my best to have a PR by EOB today.

**Comment by quartzmo** [comment]
Cool, thanks @blowmage!

**Comment by blowmage** [comment]
@quartzmo How cool would it be if we allowed that code snippet to be this?

```ruby
gcloud = Gcloud.new
datastore = gcloud.datastore

query = datastore.query("Task").
        ancestor("TaskList", "default")

tasks = datastore.run query, consistency: :eventual
```

**Comment by quartzmo** [comment]
I think changing `Query#ancestor` to accept `kind` and (`name`|`id`) in addition to key and entity is something to look at in a separate issue, because we might find a lot of places where it might be done.

**Comment by blowmage** [comment]
But it would be cool, right? 😉

**Comment by quartzmo** [comment]
Well sure! It is the mission of Ruby APIs everywhere to go above and beyond.
