### ISSUE TITLE
stub / development / testing mode for storage engine

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/gcloud-ruby#624]
What is the current best-practice for stubbing google cloud storage in development and testing mode? Would like to avoid having to set up credentials server side for this if I can. Is there some sort of emulator?

**Comment by blowmage** [comment]
Hi @samkelly, the only services that have [emulators](https://cloud.google.com/sdk/gcloud/reference/beta/emulators/) right now are Datastore and Pub/Sub. I don't know if Storage is being considered for an emulator or not. If it were available I would use it though. :smile:

For development I've always created an extra Google Cloud project and used the live service. For developer testing I would consider the gcloud-ruby API to be the edge of your application and I would mock that. For acceptance tests I would call another extra live service specific to integration tests, similar to the development service.

But that's just how I've done it. I'm interested in hearing how others approach this as well.

**Comment by samkelly** [comment]
OK, in that case I am probably going to set up a separate storage bucket for testing and another one for development. I'll have rspec automatically clear it out when its done running.

If someone wanted to take the time to do it, it might be cool to add this as a feature to gcloud-ruby. Run a method that stubs cloud storage -- specify a local directory that will act as the "cloud", redirect all uploads and downloads to Ruby file methods that read/write from this directory. If I had the time I'd write it but alas I'm on a deadline :/

**Comment by quartzmo** [comment]
@samkelly I have always pictured this happening at a higher level. For example, if you are using Paperclip to manage file storage, then you can configure it to use your actual cloud storage solution only in production. [By default it uses the filesystem](https://github.com/thoughtbot/paperclip#understanding-storage). This layer of indirection on top of a cloud storage solution saves all of the storage libraries from the need to implement this feature, and feels like the right place to do it, since Paperclip is closer to Rails and its configuration.

**Comment by samkelly** [comment]
@quartzmo depending on the cloud storage use case, this still might be very useful for some people if manipulating cloud storage files is central to the application.

**Comment by BKSpurgeon** [comment]
If i want to test things on my local file system using amazon's S3 service, you can use -  [Minio](https://min.io/) - replicates the Amazon API, the only downer is that I don't think it works with Google. There might be an equivalent out there which does the same thing. Or perhaps you could use minio with google subject to some limitations: https://github.com/minio/minio/blob/master/docs/gateway/gcs.md
