### ISSUE TITLE
Handling file uploads to cloud storage

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/gcloud-ruby#625]
Does gcloud-ruby have the ability to created signed upload urls that are handled by app engine, such as gcloud-php's createUploadUrl?

If not, I may run a separate PHP app just to handle file uploads to cloud storage, since it was much cheaper for me to use this feature when my app was still in PHP.

**Comment by blowmage** [comment]
You can create a signed URL using [`Gcloud::Storage::File#signed_url`](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.7.2/gcloud/storage/file?method=signed_url-instance).

I don't understand how the PHP library creates a signed URL that will be used by appengine though. I've looked through the [PHP code](https://github.com/GoogleCloudPlatform/gcloud-php/blob/master/src/Storage/Object.php) and I don't see a function for creating a signed URL. Can you post more details about what you are currently getting from the PHP library and how appengine is handling it?

**Comment by samkelly** [comment]
This method is outlined here: https://cloud.google.com/appengine/docs/php/googlestorage/user_upload

**Comment by samkelly** [comment]
FYI my solution was to create a php microservice module within my app that runs on normal app engine rather than on a managed VM. I used message passing between the two services to coordinate the upload.

**Comment by quartzmo** [comment]
@samkelly Thanks for the link to the App Engine PHP docs on direct upload. I was unaware of this feature and it is very interesting. It appears to me to be a feature that depends on App Engine:

>  App Engine then uses a specific upload service to handle the post and write the file to Google Cloud Storage. When the file write is complete, App Engine notifies your app that the upload is complete.

... meaning that gcloud-ruby cannot offer this feature. I think your solution, although not a simple one, seems good.

**Comment by samkelly** [comment]
We also now know from this experiment that it is possible to have a managed vm parent app with an app engine child module :)

**Comment by blowmage** [comment]
So, looking at the [URL provided](https://cloud.google.com/appengine/docs/php/googlestorage/user_upload), it allows a web user to POST the files directly to the Storage service. This can also be accomplished with a [signed URL](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.7.2/gcloud/storage/file?method=signed_url-instance). The signed URL will need permissions to accept POST requests and the upload form can use that as the target.

There are some caveats however. You should set the signed URL's expiration to be as soon as possible, which makes it hard to set it in the HTML that is returned to the user. You just never know how long a user will take to fill out the form and submit it. So a very common approach is to use JavaScript to detect when the form is actually submitted and make an XHR request back to the server to generate the signed URL. Then the JavaScript changes the form to POST to the signed URL that is returned from the XHR request and allows the form submission to continue.

Most (all?) of the popular file upload JS libraries allow for this sort of customization. I assume that is what the AppEngine PHP tool is doing, but I'm having a hard time finding the code for it.

**Comment by samkelly** [comment]
@blowmage in that case, could you give me a high level overview of high to do this? I don't see anything in the linked documentation about having a signed URL accepted POST requests, how to detect the uploaded file name, etc

**Comment by samkelly** [comment]
@blowmage looks like if I have an existing file in cloud storage, I can get a signed url (that uses PUT) for that file. Maybe if I POST to this I can upload data to overwrite this file? If so, what should I name the file field?

**Comment by blowmage** [comment]
@samkelly Take a look at the JQuery File Upload example for [uploading directly to S3](https://github.com/blueimp/jquery-file-upload/wiki/upload-directly-to-s3) from a rails app. You cal follow that approach to upload directly to Google Cloud Storage with some modifications. In the controller `create` action you will create an empty document and create a signed URL allowing a POST action to be called on it, and return the signed URL in the JSON. In the `fileUpload` JavaScript you'll update the form's `action` with the signed URL instead of updating the form's `key`, `policy`, and `signature` inputs (which you don't need).

FWIW, these questions are better asked on StackOverflow instead of on GitHub issues. Just use the `gcloud-ruby` tag and we'll see it.

**Comment by samkelly** [comment]
@blowmage thanks!

**Comment by jgeewax** [comment]
@blowmage : Should we add an example to our docs of how to do this?

**Comment by blowmage** [comment]
Yeah, we are discussing this. Another option for uploading directly to Storage is the [POST Object](https://cloud.google.com/storage/docs/xml-api/post-object) API, and we're discussing adding a Policy object and possibly a side gem to add some view helpers to Rails to make that easier to use.

**Comment by samkelly** [comment]
That would be very nice. BTW I mispoke earlier when I said that createUploadUrl is in gcloud-php. In fact, it is built into the app engine sdk: https://github.com/GoogleCloudPlatform/appengine-php-sdk/blob/master/google/appengine/api/cloud_storage/CloudStorageTools.php
