### ISSUE TITLE
How to support DISTINCT query using gRPC Query?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#628]
In #601, in the section for Queries (not GQL), there is a request for a `DISTINCT` example, with identifier `distinct_query `. (Note that this is not the same as `DISTINCT ON`, the [difference is discussed in the GQL reference](https://cloud.google.com/datastore/docs/apis/gql/gql_reference#clauses).)

```sql
SELECT DISTINCT type, priority FROM Task ORDER BY type, priority
```
However, the current gRPC API only appears to support [`Query.distinct_on `](https://cloud.google.com/datastore/reference/rpc/google.datastore.v1beta3#google.datastore.v1beta3.Query). Is it possible to somehow execute a `DISTINCT` query using `Query`?

(Also note, as far as I can tell, this snippet is not yet included in the cloud.google.com/datastore docs.)

**Comment by blowmage** [comment]
@quartzmo what was the `DISTINCT ON` example GQL query?

**Comment by quartzmo** [comment]
@blowmage In #601, in the section for Queries (not GQL), the request for a `DISTINCT ON` example:

```sql
SELECT DISTINCT ON (type) type, priority FROM Task ORDER BY type, priority 
```

**Comment by blowmage** [comment]
Okay, big post coming. The GQL support is coming with GRPC, so the objects shown below are the ones generated by google-protobuf for the v1beta3 version of Datastore.

When you run a GQL query you get a query object in the response. This is useful for paginating results. But this also gives us a target for matching the GQL with a Query.

The GQL query `SELECT DISTINCT ON (type) type, priority FROM Task ORDER BY type, priority` returns the following Query object:

```ruby
<Google::Datastore::V1beta3::Query: projection:
[<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">>,
<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">>], kind:
[<Google::Datastore::V1beta3::KindExpression: name: "Task">], filter: nil,
order: [<Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">, direction:
:ASCENDING>, <Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">, direction:
:ASCENDING>], distinct_on: [<Google::Datastore::V1beta3::PropertyReference:
name: "type">], start_cursor: "", end_cursor: "", offset: 0, limit: nil>
```

Whereas the GQL Query `SELECT DISTINCT ON (type, priority) type, priority FROM Task ORDER BY type, priority` returns the following Query object.

```ruby
<Google::Datastore::V1beta3::Query: projection:
[<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">>,
<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">>], kind:
[<Google::Datastore::V1beta3::KindExpression: name: "Task">], filter: nil,
order: [<Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">, direction:
:ASCENDING>, <Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">, direction:
:ASCENDING>], distinct_on: [<Google::Datastore::V1beta3::PropertyReference:
name: "type">, <Google::Datastore::V1beta3::PropertyReference: name:
"priority">], start_cursor: "", end_cursor: "", offset: 0, limit: nil>
```

As expected, the only difference are the values in `distinct_on`. This is identical to the Query object returned from the `SELECT DISTINCT type, priority FROM Task ORDER BY type, priority` GQL query.

```ruby
<Google::Datastore::V1beta3::Query: projection:
[<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">>,
<Google::Datastore::V1beta3::Projection: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">>], kind:
[<Google::Datastore::V1beta3::KindExpression: name: "Task">], filter: nil,
order: [<Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "type">, direction:
:ASCENDING>, <Google::Datastore::V1beta3::PropertyOrder: property:
<Google::Datastore::V1beta3::PropertyReference: name: "priority">, direction:
:ASCENDING>], distinct_on: [<Google::Datastore::V1beta3::PropertyReference:
name: "type">, <Google::Datastore::V1beta3::PropertyReference: name:
"priority">], start_cursor: "", end_cursor: "", offset: 0, limit: nil>
```

This demonstrates that `SELECT DISTINCT a, b, c` is identical to `SELECT DISTINCT ON (a, b, c) a, b, c`, as stated in the [official docs](https://cloud.google.com/datastore/docs/apis/gql/gql_reference#clauses). Now we just have to create a gcloud-ruby Query object that matches the protobuf objects. When we do that we find that the following are equivalent:

The GQL `SELECT DISTINCT ON (type) type, priority FROM Task ORDER BY type, priority` is the same as:
```ruby
gcloud.datastore.query("Task")
  .select("type", "priority")
  .order("type").order("priority")
  .group_by("type")
```

The GQL `SELECT DISTINCT type, priority FROM Task ORDER BY type, priority` is the same as:
```ruby
gcloud.datastore.query("Task")
  .select("type", "priority")
  .order("type").order("priority")
  .group_by("type", "priority")
```

So to emulate a `DISTINCT` query, we just need to make sure the properties in `select` are the same in `group_by`. If they are different we have a `DISTINCT ON`.

**Comment by quartzmo** [comment]
Wow, incredible research @blowmage.

Here is the current snippet for `distinct_on_query`. 

```ruby
  # [START distinct_on_query]
  query = datastore.query("Task").
          distinct_on("type", "priority").
          order("type").
          order("priority")
  # [END distinct_on_query]
```

A couple of style questions for you:

1. Should I use `group_by` instead of its `distinct_on` alias? (As far as the gRPC API is a model, the [latest release notes](https://cloud.google.com/datastore/release-notes#april_2016) state "Field group_by is now distinct_on.")

1. Which should come first, order or distinct?

**Comment by blowmage** [comment]
If you want to match the GQL you should also add those properties to `select`. The order doesn't matter. 

I would stick with `group_by`, because so far we prefer to use the Ruby norms and Enumerable has `group_by`. But we can swap which is the method and which is the alias if you wish.

**Comment by quartzmo** [comment]
OK, sounds good. Thanks again for figuring this out!
