### ISSUE TITLE
Feature request: datastore delete using key only

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#633]
Current code expect an entity and then does `entity.key`

**Comment by quartzmo** [comment]
@timanovsky Have you tried deleting by passing the key? It should work.

**Comment by timanovsky** [comment]
`Dataset` can indeed handle both, but not `Transaction`.

Best regards,
Alexey Timanovsky.

**Comment by quartzmo** [comment]
@timanovsky Thanks for the clarification. I see the issue now. I agree that `Transaction` should support the same API as `Dataset`.

**Comment by blowmage** [comment]
This is a bug, I should accept either an Entity or a Key. Thanks for letting us know about it.
