### ISSUE TITLE
Remove search API ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#634]
Looks like we're phasing search into a different API surface eventually, but won't be continuing the private alpha as planned. Can we chop search out of gcloud-ruby?

**Comment by quartzmo** [comment]
In that case, the sooner we remove it, the better. Sounds good to me. Thanks for the heads up @jgeewax.

**Comment by blowmage** [comment]
I'll gladly remove it. :)
