### ISSUE TITLE
Error only for datastore

### ISSUE THREAD

**Issue by vyper** [GoogleCloudPlatform/gcloud-ruby#635]
I can't use `datastore`, but the same environment vars work normally for others api (`storage` or `logging`).

```
$ export GOOGLE_CLOUD_PROJECT=my-project-id
$ export GOOGLE_CLOUD_KEYFILE='/root/my-project-id-key-file.json'
$ gem install gcloud
[...]
Successfully installed gcloud-0.7.2
27 gems installed

$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

$ irb
> require 'gcloud'
> gcloud = Gcloud.new
> dataset = gcloud.datastore
> dataset.find 'MyKind', '1'
Gcloud::Datastore::ApiError: API call to lookup was not successful
  from /usr/local/bundle/gems/gcloud-0.7.2/lib/gcloud/datastore/connection.rb:170:in `rpc'
  from /usr/local/bundle/gems/gcloud-0.7.2/lib/gcloud/datastore/connection.rb:70:in `lookup'
  from /usr/local/bundle/gems/gcloud-0.7.2/lib/gcloud/datastore/dataset.rb:173:in `find_all'
  from /usr/local/bundle/gems/gcloud-0.7.2/lib/gcloud/datastore/dataset.rb:154:in `find'
  from (irb):4
  from /usr/local/bin/irb:11:in `<main>'

> storage = gcloud.storage
> storage.buckets.first.name
=> "artifacts.my-project-id.appspot.com"
```

**Comment by quartzmo** [comment]
Hi @vyper, 

Have you enabled the Cloud Datastore API in the [Google Developers Console](https://console.developers.google.com/projectselector/apis/api/datastore/overview)?

**Comment by vyper** [comment]
Yehp @quartzmo, using python works...

```
>> from gcloud import datastore
>> client = datastore.Client(project = 'my-project-id')
>> key = datastore.key.Key('MyKind', '1', project = 'my-project-id')
>> print client.get(key)
<Entity[{'kind': u'MyKind', 'id': 1}, ...]
```

**Comment by quartzmo** [comment]
Thanks for checking that, @vyper. I'm looking into it now.

**Comment by quartzmo** [comment]
I have not been able to reproduce the issue on my own project, everything appears OK (using `v0.7.2`).

**Comment by blowmage** [comment]
@vyper Can you catch the error and print the `.response` object on the error? That might tell us more information about why the service returned an error.

```ruby
begin
  dataset.find 'MyKind', '1'
rescue Gcloud::Datastore::ApiError => e
  puts e.response.inspect
end
```

**Comment by vyper** [comment]
@blowmage below...

```
response.status => 403
response.body => Unauthorized.

response.inspect
#<Faraday::Response:0x00558338142d08 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="Unauthorized." @url=#<URI::HTTPS https://www.googleapis.com/datastore/v1beta2/datasets/my-project-id/lookup> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"gcloud-node/0.7.2", "Content-Type"=>"application/x-protobuf", "Authorization"=>"Bearer ya29..0ALgaJ55352Di8NfpRKJmBnGl1eW93YFz4L5ogMgr4yn2W2sbf4CJTZx-lpaEIC7qqE", "Cache-Control"=>"no-store"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00558338142d08 ...> @response_headers={"vary"=>"Origin, X-Origin", "content-type"=>"text/html; charset=UTF-8", "date"=>"Tue, 26 Apr 2016 21:04:38 GMT", "expires"=>"Tue, 26 Apr 2016 21:04:38 GMT", "cache-control"=>"private, max-age=0", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "server"=>"GSE", "alternate-protocol"=>"443:quic", "alt-svc"=>"quic=\":443\"; ma=2592000; v=\"33,32,31,30,29,28,27,26,25\"", "connection"=>"close", "transfer-encoding"=>"chunked"} @status=403>>
```

**Comment by blowmage** [comment]
@vyper Thanks! I have no idea why Datastore is unable to authenticate where the other services are. When did you generate your JSON keyfile?

**Comment by blowmage** [comment]
Do you have any other environment variables set? Like `DATASTORE_PROJECT` or `DATASTORE_KEYFILE`?

**Comment by vyper** [comment]
I generated the json keyfile using:

* Open:  Web Console > Permissions > Services accounts
* Create a service account
* Create a key file (json)

I tried others env vars and I tried also using `gcloud = Gcloud.new 'my-project-id', '/app/my-project-id-key-file.json'`, but does not worked.

**Comment by blowmage** [comment]
One way to check that both datastore and storage are using the same credentials is to run the following. This code should return `true`.

```ruby
Gcloud.datastore.connection.credentials.client.issuer ==
  Gcloud.storage.connection.credentials.client.issuer
```

Fair warning, this code is using private objects that are not part of the public API, and will change as gcloud moves to GRPC.

**Comment by vyper** [comment]
```ruby
require 'gcloud/datastore'
require 'gcloud/storage'

Gcloud.datastore.connection.credentials.client.issuer == Gcloud.storage.connection.credentials.client.issuer
# => true
```

**Comment by vyper** [comment]
Running acceptance tests I received the same errors...

https://gist.github.com/vyper/ee91c776083401399750549bf2396720

**Comment by vyper** [comment]
@blowmage In my personal account worked fine... Now, I don't know what is occurred. ):

**Comment by blowmage** [comment]
@vyper Yeah, this is very strange. AFAICT datastore isn't doing anything different than the other services.

Can you tell us which versions of the gems signet, googleauth, and faraday you are using?

`$ gem list signet googleauth faraday`

Also, are you configuring Faraday to use any particular middleware?

**Comment by blowmage** [comment]
I hate to ask, but can you try creating a new service account and downloading a new JSON file and see if the new JSON file also has problems?

**Comment by timanovsky** [comment]
Make sure you enable "Google Cloud Datastore API (v1beta2)" (which is hidden, and you need to search for it) not only "Google Cloud Datastore API". I think I have the same problem, not sure if it was 403 though.

**Comment by vyper** [comment]
@blowmage I am using a empty container of docker (ruby:2.3.0-alpine).

```
gem list signet googleauth faraday

*** LOCAL GEMS ***

signet (0.7.2)

*** LOCAL GEMS ***

googleauth (0.5.1)

*** LOCAL GEMS ***

faraday (0.9.2)
```

@timanovsky Service is enabled!

![screen shot 2016-04-27 at 09 27 43](https://cloud.githubusercontent.com/assets/22549/14852035/52171a10-0c5a-11e6-91fc-e56d104d77e7.png)

I tried create another service account, but I received the same error.

**Comment by timanovsky** [comment]
Another reason I had was VM clock were out of sync which made tokens not to
pass validation

Best regards,
Alexey Timanovsky.

**Comment by vyper** [comment]
@timanovsky for this error the message is:
```
400 Bad Request
Invalid JWT: Token must be a short-lived token and in a reasonable timeframe
```

**Comment by vyper** [comment]
@blowmage I tried using gcloud from this branch https://github.com/GoogleCloudPlatform/gcloud-ruby/pull/620 and work! Any idea?

**Comment by quartzmo** [comment]
@vyper That is good information. Thank you for trying the branch, and for continuing to work on this. Just so you know, there is an issue with the `datastore` topic branch: You will get an error if you send `false` property values, as [discussed here](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/314#issuecomment-209559214).

**Comment by blowmage** [comment]
Any default value, really. Like `0` or `""` as well. A upstream fix is coming, and we'll release support for v1beta3 as soon as it arrives.

**Comment by vyper** [comment]
@blowmage same in 0.8.2 error continues... and I don't have your branch for use now. ):

**Comment by vyper** [comment]
@blowmage same in 0.8.2 error continues...

**Comment by timanovsky** [comment]
@vyper Some people complained they can not use API unless they setup a budget for the project on Billing page. (Just bringing more crazy idea on the table)

**Comment by quartzmo** [comment]
@vyper The branch you were using (`blowmage/datastore-changes`) was merged into the `datastore` branch on this repo. Have you tried that?

**Comment by vyper** [comment]
Yeh, I tried @quartzmo and it is broken for me. ):

@timanovsky haha, I've setted up a budget for project. But does not work only datastore, others services is fine. ):

**Comment by blowmage** [comment]
@vyper Hmmm, I'm confused. In [this comment](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/635#issuecomment-215097649) you indicated that the branch `blowmage/datastore-changes` branch did work. But now you are saying the branch `gcloud-ruby/datastore` does _not_ work? Can you confirm?

**Comment by vyper** [comment]
I am too @blowmage 

# using blowmage/datastore-changes (commit: 678e428)

```
$ bundle install
[...]
Using gcloud 0.7.2 from git://github.com/blowmage/gcloud-ruby.git (at datastore-changes@678e428)
Bundle complete! 8 Gemfile dependencies, 57 gems now installed.
Bundled gems are installed into /usr/local/bundle.

$ bundle exec irb
> require 'gcloud/datastore' # => true
> Gcloud.datastore.find 'Subscription', '8565' # => #<Gcloud::Datastore::Entity:0x00562ee77069f0 @properties=#<Gcloud::Datastore::Properties:0x00562ee9267ed8>
```

# using 0.8.2

```
$ bundle install
[...]
Installing beefcake 1.1.0
Installing gcloud 0.8.2 (was 0.7.2)
Bundle complete! 8 Gemfile dependencies, 58 gems now installed.
Bundled gems are installed into /usr/local/bundle.
$ bundle exec irb
> require 'gcloud/datastore' # => true
> Gcloud.datastore.find 'Subscription', '8565'
Gcloud::Datastore::ApiError: API call to lookup was not successful
  from /usr/local/bundle/gems/gcloud-0.8.2/lib/gcloud/datastore/connection.rb:184:in `rpc'
  from /usr/local/bundle/gems/gcloud-0.8.2/lib/gcloud/datastore/connection.rb:77:in `lookup'
  from /usr/local/bundle/gems/gcloud-0.8.2/lib/gcloud/datastore/dataset.rb:232:in `find_all'
  from /usr/local/bundle/gems/gcloud-0.8.2/lib/gcloud/datastore/dataset.rb:204:in `find'
  from (irb):2
  from /usr/local/bin/irb:11:in `<top (required)>'

> begin
  Gcloud.datastore.find 'Subscription', '8565'
rescue Gcloud::Datastore::ApiError => e
  puts e.response.status, e.response.body
end

403
Unauthorized.
```

**Comment by blowmage** [comment]
Ahh, 0.8.2 is the branch `gcloud-ruby/master`. I'm asking for you to try the branch`gcloud-ruby/datastore`.

**Comment by blowmage** [comment]
@vyper Can you also try changing the scope of the authentication to use the global scope?

```
$ export GOOGLE_CLOUD_PROJECT=my-project-id
$ export GOOGLE_CLOUD_KEYFILE='/root/my-project-id-key-file.json'
$ irb
> require 'gcloud'
> gcloud = Gcloud.new
> global_scopes = ["https://www.googleapis.com/auth/userinfo.email",
*                  "https://www.googleapis.com/auth/cloud-platform"]
> dataset = gcloud.datastore scope: global_scopes
> dataset.find 'MyKind', '1'
```

**Comment by blowmage** [comment]
@vyper If that doesn't work, let's step away from `gcloud-ruby` and see if you can authenticate to `v1beta2` using the JSON/REST API and Google API Client:

```
$ export GOOGLE_CLOUD_PROJECT=my-project-id
$ export GOOGLE_CLOUD_KEYFILE='/root/my-project-id-key-file.json'
$ irb
> require "googleauth"
>
> auth = Google::Auth::ServiceAccountCredentials.make_creds(
*   json_key_io: File.open(ENV["GOOGLE_CLOUD_KEYFILE"]))
> auth.scope = ["https://www.googleapis.com/auth/userinfo.email",
*               "https://www.googleapis.com/auth/datastore"] 
> auth.fetch_access_token!
> 
> require "google/api_client"
> 
> client = Google::APIClient.new
> client.authorization = auth
> 
> datastore = client.discovered_api "datastore", "v1beta2"
> 
> response = client.execute(
*   api_method: datastore.datasets.lookup,
*   parameters: { datasetId: ENV["GOOGLE_CLOUD_PROJECT"] },
*   body_object: { keys: [{ path: [{ kind: "MyKind", name: "1" }] }] }
> )
> response.success? #=> ???
```

**Comment by vyper** [comment]
@blowmage using version 0.8.2:
- testing with `global_scopes` I received same error.
- testing with `json api` I received same error.

```
[...] 
{"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"PERMISSION_DENIED", "message"=>"Unauthorized."}], "code"=>403, "message"=>"Unauthorized."}}>>
> response.success?
=> false
```

**Comment by vyper** [comment]
@blowmage using GoogleCloudPlatform/gcloud-ruby.git (at datastore@bf78930) its work!

```
Using gcloud 0.7.2 (was 0.8.2) from git://github.com/GoogleCloudPlatform/gcloud-ruby.git (at datastore@bf78930)
Bundle complete! 8 Gemfile dependencies, 57 gems now installed.
Bundled gems are installed into /usr/local/bundle.

$ bundle exec rib
> require 'gcloud/datastore'
> Gcloud.datastore.find 'Subscription', '8565'
=> #<Gcloud::Datastore::Entity:0x007fb2100061e8 @properties=#<Gcloud::Datastore::Properties ...
```

**Comment by blowmage** [comment]
Okay, so the problem here is that `gcloud-ruby` 0.8.2, the Google API Client calling the JSON/REST API, _and_ `gcloud-ruby`'s datastore branch all use the same exact authentication mechanism. You are only getting the Unauthorized error when calling Datastore v1beta2. The `gcloud-ruby`'s datastore branch is calling v1beta3, as is gcloud-python. That's the commonality.

So when I combine that information along with the fact that I cannot replicate the behavior, it leaves me with the conclusion that there is something in your account that is not allowing you to connect to Datastore v1beta2. This looks to be an account issue and not a code issue. And because of that there isn't much we can do to fix it...

Other than releasing a new version of `gcloud-ruby` that switches to v1beta3, which we plan on doing early next week.

**Comment by vyper** [comment]
@blowmage for now I will continue using "unstable" branch and I will open the issue in google for this point.

Thank you! (:

**Comment by blowmage** [comment]
Closing for now. Please reopen if you can provide a reproduction for this on another account.
