### ISSUE TITLE
Implement auth token refresh

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#638]
I'm not sure if this problem affects services other than Datastore. What I see is after 4 hrs (I think it is auth token ttl) after server start, I sometimes (not always) see `401 "Invalid Credentials"` responses.  My theory is that it is because of race condition here: https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/datastore/credentials.rb#L39

Probably check for expiration time should be more conservative, and consider token expired few seconds or minutes before actual date. 

Other option is to retry request at library level.

At application level it is hard for me to decide if I should retry the request, normally 4XX requests should not be repeated.

**Comment by blowmage** [comment]
Google's default expiration for OAuth access tokens are an hour. I think you may be right about a race condition where the token expires after a request is sent, but before the request is processed.

**Comment by quartzmo** [comment]
@timanovsky Have you had a chance to look at #641? I prefer this solution to retries. If merged, it will close this issue, although you can always re-open.

**Comment by timanovsky** [comment]
Me too. Looks good

Best regards,
Alexey Timanovsky.
