### ISSUE TITLE
Datastore: when rolling back failed transaction exception may be lost if there is secondary exception in `rollback` rpc

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#645]
If exception happens at line https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/datastore/dataset.rb#L287 it is poped up to user code, masking real exception in transaction block rescued one line higher.

My real world example is that `commit` fails with timeout error (why, this I will be investigating), and then this rescue code tries to unwind transaction with `rollback` and it fails as transaction duration of 30s is expired by that time. I can imagine more error causes in `rollback`.

I'm not sure what ideal implementation should be, but if Datastore automatically rolls back uncommitted transaction (which I think is implied by 30 seconds limit), then secondary exception in rollback can probably be just muted.

_Since you asked for more bug reports ;)_

**Comment by blowmage** [comment]
Thanks for the report!

**Comment by blowmage** [comment]
@timanovsky Can you give us your thoughts on #649?

**Comment by blowmage** [comment]
@timanovsky This has been released in [0.8.1](https://rubygems.org/gems/gcloud/versions/0.8.1). Please give it a try. Thanks for your help!

**Comment by quartzmo** [comment]
We just released [0.8.2](https://rubygems.org/gems/gcloud/versions/0.8.2) to fix a bug in 0.8.1 (see #667 for details.)
