### ISSUE TITLE
Allow Datastore calls to insert vs. update

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#648]
The original design goal for Datastore was to design a humane API at the expense of not exposing all features. This is why `Datastore#save` calls `upsert`, because it has the lowest conceptual overhead. But now the thinking has changed and gcloud-ruby should expose all Datastore features. To that end gcloud-ruby should add `Dataset#insert` and `Dataset#update`, so that users can decide of they want the API call to fail if the entities exist or not. IMO `Datastore#save` should be aliased as `Datastore#upsert` for consistency.

**Comment by jgeewax** [comment]
Couldn't we just pass in a parameter if people want to be explicit? I have a hard time believing that the common case is "I care so much about whether I'm inserting or updating or usperting that I want to always call a specific one!"

If it were me, I'd say we should...

- keep `#save` around as the default, but allow a specific "operation" to be set when calling it
- make `#upsert`/ `#insert` / `#update` aliases that set that operation value and fail appropriately

The common case will still be `#save`, but if people want to be specific, they can. Most people won't want to. If they did, then all the ORMs out there would be requiring you to say whether you want to update or insert (those are SQL equivalents) -- they're not.

@pcostell : Correct me if I'm wrong here.

**Comment by blowmage** [comment]
I'm fine sitting on this issue for now and collecting feedback. This was a thought that occurred to us as we are making other enhancements to Datastore, and it is a bit of an attempt to get ahead of an upcoming request for this feature.

I may not have phrased the issue very well, but the intention here is as you stated: `#save` remains the main mechanism to save entities, and `#upsert`, `#insert`, and `#update` are effectively aliases that add the option for the save to fail if expected preconditions are not met. We leave the easy things easy, but add options that are not currently supported now.

**Comment by quartzmo** [comment]
I'm in support of adding `#upsert`, `#insert`, and `#update` to the API. I strongly disagree with the reductionist/revisionist approach of the "original design goal" (thank you @blowmage for providing this background), because I think we can have our cake (easy onboarding for new users emphasizing `save` or `upsert`) and eat it too (full access to the underlying API for experienced users).

The suggestion by @jgeewax sounds OK to me.
