### ISSUE TITLE
Custom documentation theme

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#65]
We need a custom documentation theme to match the look and feel of the [gcloud-ruby](http://googlecloudplatform.github.io/gcloud-ruby/) site. The [current documentation](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/) using the default RDoc template.

The theme can be for either RDoc or YARD.

**Comment by jgeewax** [comment]
Looks like this is all completed, right?

**Comment by blowmage** [comment]
We could close this, but I kept it open to collect feedback on the template. I'm fine closing it and opening a new issue for any changes.

**Comment by jgeewax** [comment]
Yep, let's do that.
