### ISSUE TITLE
Vision Location Normalization

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#672]
We might consider performing some normalization of the Location values (latitude/longitude). The [official docs](https://cloud.google.com/vision/reference/rest/v1/images/annotate#LatLng) have some code to do this.

**Comment by quartzmo** [comment]
I don't think gcloud-ruby should *ever* attempt to normalize latitude/longitude. I consider this the responsibility of client code.

**Comment by quartzmo** [comment]
I think we should close this issue. I haven't had a chance to test it out, but if by some chance the Vision API does something weird like rolling over out-of-bounds values instead of raising an error, then we can open a new issue to deal with that when it comes up.
