### ISSUE TITLE
Datastore library requires valid Google authentication token even when using datastore emulator 

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#676]
If i set JSON credentials `gcloud.datastore()` call tries to authenticate against google (and fails if machine clock is out of sync for example)

If I don't set JSON credentials code falls to https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/credentials.rb#L81 and fails.

This is undesired behavior in both cases. In integration tests we WebMock and do not expect real HTTP requests to live service. I expect all requests only hit emulator.

**Comment by quartzmo** [comment]
@timanovsky Thanks for reporting. Have you read the recent discussion in #610? Is there anything helpful there?

**Comment by blowmage** [comment]
The current emulator support was not intended to side-step existing authentication mechanisms. We will update this as part of the v1beta3 release, but for now you will need to provide some working credentials.
