### ISSUE TITLE
Support Application Default Credentials in Google App Engine (GAE)

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#677]
Now that [Ruby on Google App Engine goes beta](https://cloudplatform.googleblog.com/2016/05/Ruby-on-Google-App-Engine-goes-betaruntime.html), we need to provide documentation (and if needed, library support) for using the Application Default Credentials available in GAE with gcloud-ruby.

* [Application Default Credentials docs for google-api-client](https://developers.google.com/identity/protocols/application-default-credentials#callingruby)
* [gcloud-python docs for Google App Engine Environment](http://gcloud-python.readthedocs.io/en/latest/gcloud-auth.html#google-app-engine-environment)

**Comment by blowmage** [comment]
It's possible that googleauth already detects the authentication credentials when running on GAE, so all we may need to do is find the `project_id` similar to how we already do on GCE.

**Comment by blowmage** [comment]
Looks like App Engine is all running on top of GCE, so we may not need to change anything extra to support GAE. Gonna have to deploy some apps to verify for sure though.

**Comment by bmclean** [comment]
@blowmage I believe you are correct (nothing extra required). We tried out the App Engine managed VMs (now named Flexible Environment) in February using the ruby runtime with gcloud-ruby and connected to cloud datastore simply by passing in the project_id to `Gcloud.datastore`.

**Comment by blowmage** [comment]
Yep, that's what we are seeing. Now we just need to make that point very clearly in the documentation so folks don't get confused.

**Comment by blowmage** [comment]
This works. We didn't need to make any code changes to support this since the ruby GAE is built on top of GCE.
