### ISSUE TITLE
Update README.md to fit consistent style

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#68]
See https://github.com/GoogleCloudPlatform/gcloud-meta/issues/3 for the format.

**Comment by blowmage** [comment]
Is there anything in particular that is missing from the current README that you want added? I think the most recent revision is pretty close.

**Comment by jgeewax** [comment]
If it matches the Proposal in https://github.com/GoogleCloudPlatform/gcloud-meta/issues/3, then feel free to close. I don't think it lines up exactly just yet.
