### ISSUE TITLE
Pass an array to translate

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#682]
Allow arrays of strings to be passed to translate. Currently, users need to splat the array:

```ruby
require "gcloud"

gcloud = Gcloud.new
translate = gcloud.translate

words = ["chien", "chat"]
translations = translate.translate *words, to: "en"
```

We want to allow users to pass the array without the splat:

```ruby
require "gcloud"

gcloud = Gcloud.new
translate = gcloud.translate

words = ["chien", "chat"]
translations = translate.translate words, to: "en"
```

**Comment by jgeewax** [comment]
Also - if we have to choose between allowing the `translate "word1", "word2", to: "fr"` or not requiring the splat, I vote for the non-splatting version.

I expect that the number of people hard-coding stuff in that call is far lower than the number of people who have an array of things that need translating...

**Comment by blowmage** [comment]
We don't have to choose. Ruby supports splat arguments and optional arguments on the same method.
