### ISSUE TITLE
Datastore: hangs instead of throwing exception

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#688]
Two example:

1) when I set `DATASTORE_EMULATOR_HOST` to "http://127.0.0.1:3001" as it was with `DATASTORE_HOST`, and invokead datastore operation I've got the following message in terminal
```
E0512 06:54:20.906399472    9828 resolve_address_posix.c:126] getaddrinfo: Name or service not known
```
After which ruby process just hanged and could not be interrupted by Ctrl-C, only `kill -9` did the job

2) When I fixed  `DATASTORE_EMULATOR_HOST` to "127.0.0.1:3001" but did not start the actual emulator I've got enless loop of
```
E0512 07:00:34.884748956    9918 tcp_client_posix.c:173]     failed to connect to 'ipv4:127.0.0.1:3001': socket error: connection refused
E0512 07:00:35.886550255    9918 tcp_client_posix.c:173]     failed to connect to 'ipv4:127.0.0.1:3001': socket error: connection refused
```
Again with only `kill -9` to help.

Something wrong with network stack

**Comment by bmclean** [comment]
@timanovsky What if you try localhost without the http:// like this?
`ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:3001'`

**Comment by blowmage** [comment]
Are you running the `gcd.sh` grpc emulator [linked to in the docs](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.9.0/gcloud/datastore)? Or are you running the emulator by using `$ gcloud beta emulators start`?

**Comment by bmclean** [comment]
@blowmage I am able to see the same thing using the new gcd.sh grpc emulator. If I initialize my cloud datastore dataset like this:
`ENV['DATASTORE_EMULATOR_HOST'] = 'http://localhost:8180'`
The first time I interact with the gcd emulator I receive the following:
`E0512 08:14:03.713381000 123145316659200 resolve_address_posix.c:126] getaddrinfo: nodename nor servname provided, or not known`
and I have to manually kill the gcd process.
However if I remove the http:// and initialize it like this:
`ENV['DATASTORE_EMULATOR_HOST'] = 'localhost:8180'`
the emulator seems to run OK but I do see this output:
`E0512 08:23:25.219103000 123145307635712 tcp_client_posix.c:173] failed to connect to 'ipv6:[::1]:8180': socket error: connection refused`

**Comment by blowmage** [comment]
We have verified that setting the host to an invalid value will hang the ruby client. This is an upstream issue and have opened grpc/grpc#6559 for it.

When starting the emulator you are given the following message:

```
If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:

export DATASTORE_EMULATOR_HOST=localhost:8978
```

It is important to properly set the environment variable name and value to get the integration to work.

**Comment by timanovsky** [comment]
@blowmage I missed that part about `gcd.sh`, I was using `beta emulators`. So the second part of the ticket is probably not relevant

**Comment by blowmage** [comment]
@timanovsky Okay. For the first part of the issue you should set the environment variable to the value the emulator provides. If you do that you should have no problems.

I'm going to close this issue. The issue filed against GRPC remains still open, and hopefully we see the GRPC client stop hanging when set with an invalid host soon.

**Comment by timanovsky** [comment]
What about second part? If host is not there it also hangs. This may happen
in real set up to due to network problems. (Sorry, at the moment I don't
have time to simulate this)

Best regards,
Alexey Timanovsky.

**Comment by blowmage** [comment]
In both cases the host provided was invalid. When you provide a valid host (pointing to a working service) the emulator connectivity works. The hanging on an invalid host is an upstream issue with GRPC and there isn't much gcloud-ruby can do about it other than raise the issue to them, which we have done.
