### ISSUE TITLE
Datastore does not talk to emulator

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#689]
I'm having a bad luck with new release and emulator. After starting actual emulator (see my previous attempts #688) and invoking datastore query I'm getting the following exception:

```
E0512 07:07:15.781534626   10158 parsing.c:472]              Unknown frame type 50
E0512 07:07:16.785532939   10158 parsing.c:472]              Unknown frame type 50
E0512 07:07:18.788983845   10158 parsing.c:472]              Unknown frame type 50
E0512 07:07:21.792760769   10158 parsing.c:472]              Unknown frame type 50
Exception: Gcloud::UnavailableError: 14: -> GRPC::BadStatus: 14: 
/home/vagrant/.rvm/gems/ruby-2.3.0/gems/gcloud-0.9.0/lib/gcloud/datastore/dataset.rb:406:in `rescue in run'
/home/vagrant/.rvm/gems/ruby-2.3.0/gems/gcloud-0.9.0/lib/gcloud/datastore/dataset.rb:397:in `run'
...
```

**Comment by blowmage** [comment]
@timanovsky Are you running the `gcd.sh` grpc emulator [linked to in the docs](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.9.0/gcloud/datastore)? Or are you running the emulator by using `$ gcloud beta emulators start`?

**Comment by timanovsky** [comment]
@blowmage I missed that part about `gcd.sh`, I was using `beta emulators`. So the second part of the ticket is probably not relevant
