### ISSUE TITLE
Datastore feature request: implement Enumerator interface in QueryResults 

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/gcloud-ruby#690]
Something like `QueryResults.to_enum` should return enumerator with lazy page loading contrary to `.all` eager loading.

**Comment by blowmage** [comment]
I 100% agree. I had a spike that implemented this many moons ago, but it was before gcloud-ruby dropped 1.9 support. Now that gcloud-ruby only supports 2.0+ we can safely add this. When we do we will add this to all result objects, across all services.

Also, the method `QueryResults#to_enum` already exists. The object is a delegate to an array, and you can already enumerate over the page of results. So the future enumerator method will need to be named something new.

**Comment by blowmage** [comment]
Resolved in the 0.11.0 release.
