### ISSUE TITLE
Looks like the build is broken?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#70]
On the homepage the badge says failing... So either the badge needs fixing or the build needs fixing... not sure which.

**Comment by jgeewax** [comment]
Badge is back... resolving...

**Comment by blowmage** [comment]
The build is somewhat unreliable because we run multiple tests concurrently for the various versions of ruby. Sometimes we make too many requests across the concurrent tests and the service rate limits us. Even with incremental backoff. Retuning the failed will resolve it.
