### ISSUE TITLE
Unable to set chunk_size in BigQuery Table#load

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#701]
As [reported](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/570#issuecomment-220314990) there is no way to set the `chunk_size` options in `Gcloud::Bigquery::Table#load` since the move away from an options hash to named arguments. We need this restored.

Additionally, it is reported that files larger than 2GB need to have a chunk_size set to something less than 2GB. Therefore we should set a chunk_size if one is not provided, and the file size is very large.

**Comment by blowmage** [comment]
@gramos74 We've been discussing it and we think 10MB should be the default chunk size. Once we restore the `chunk_size` option you will be able to set a 1GB chunk size, trading memory usage in the ruby upload process for the performance benefits.

**Comment by gramos74** [comment]
ok, got it
