### ISSUE TITLE
Publishing messages to PubSub with 0.6.2 or earlier failing

### ISSUE THREAD

**Issue by arparker** [GoogleCloudPlatform/gcloud-ruby#713]
Utilizing version 0.6.2 or earlier of the gem, publishing messages to a topic (topic.publish "Hello") appears to have begun failing out with an API error code of 400 and message:

"Invalid value at 'messages[0].data' (TYPE_BYTES), \"SGVsbG8=\n\""

This was previously working in several ongoing functioning apps, but appears to have broken sometime earlier this month (estimated May 10th).  Updating to a newer (0.7.0 or later) version of the gem appears to fix the issue, but is not an immediate option in my case due to libc dependencies.

Stack:
```
/Users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.6.2/lib/gcloud/pubsub/topic.rb:558:in `publish_batch_messages': Invalid value at 'messages[0].data' (TYPE_BYTES), "SGVsbG8= (Gcloud::Pubsub::ApiError)
"
	from /Users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.6.2/lib/gcloud/pubsub/topic.rb:342:in `publish'
	from simple-example.rb:19:in `<main>'
```

Is there any workaround for this (outside of updating the gem past 0.6.2)?

**Comment by quartzmo** [comment]
@arparker Thanks for reporting this issue. We will try to reproduce it and get back to you by tomorrow.

If we need to release a fix, updating to a new patch version (0.6.3) is an option for you, correct?

**Comment by arparker** [comment]
Thanks for the quick response.  Yes, a patch like that should work.

**Comment by blowmage** [comment]
@arparker When did this error message start?

**Comment by arparker** [comment]
We don't have complete log data to pinpoint exactly, but best we can tell we started seeing instances of it on or around May 10-11th.  It appears that it may have been intermittent at first, then becoming constant.  The earliest log evidence we still have is for May 12th, where it still appeared intermittent.

**Comment by blowmage** [comment]
I think I've identified the issue. In gcloud pre-0.7.0 the pubsub data is encoded using base64, as required by the Pub/Sub REST API. The data was encoded according to [RFC 2045](https://tools.ietf.org/html/rfc2045), which has worked fine. However, now the service returns an error. The solution is to encode using [RFC 4648](https://tools.ietf.org/html/rfc4648) instead.

Release coming soon.

**Comment by blowmage** [comment]
@arparker gcloud [0.6.3](https://github.com/GoogleCloudPlatform/gcloud-ruby/releases/tag/v0.6.3) was just published and should fix this issue. Thanks for opening the issue!

**Comment by blowmage** [comment]
Kinda frustrating the commit isn't being linked properly. Here is the fix: 6b3bcfa126186460ec587df4f9d92bddee391bbd

**Comment by ktowle** [comment]
Thank you! I was able to bundle 0.6.3 successfully and it's put us back in business until we can get into an environment where we can upgrade. Really appreciate the quick resolution.

(I work with @arparker)

**Comment by arparker** [comment]
Yes, thank you for the quick turn around!  We'll go with this and let you know if anything turns up.

**Comment by blowmage** [comment]
This is likely due to a change made by the Pub/Sub API. They were probably rolling out the change which is why the error was inconsistent for a while. 

Thanks for making us aware of the issue!
