### ISSUE TITLE
Installing dependencies for native extensions

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/gcloud-ruby#715]
When deploying apps built with gcloud-ruby, say I want to use capybara-webkit, which has a lot of server side dependencies... how would I go about getting docker to automatically install these dependencies? Right now I am just using `gcloud preview app deploy` to deploy to managed app engine. Would love to see some documentation associated with this in gcloud-ruby, as it is sort of a ruby-specific problem.

**Comment by samkelly** [comment]
FYI I currently use a very complicated shell script to keep capybara-webkit from being installed server side when I deploy, but obviously this is specific to my situation and isn't a future-proof solution

**Comment by quartzmo** [comment]
@samkelly Is this perhaps more of a general question about [Ruby and App Engine](https://cloud.google.com/ruby/getting-started/hello-world)? I think of gcloud-ruby as agnostic about its runtime environment. I'm not sure gcloud-ruby is the right place for this documentation.

**Comment by quartzmo** [comment]
@samkelly Thanks. If you find something helpful, can you link to it from this issue? For anyone who lands here in the future...

**Comment by samkelly** [comment]
I haven't found anything but will certainly link it if I do
