### ISSUE TITLE
Does gcloud-ruby works with TEXT_DETECTION type?

### ISSUE THREAD

**Issue by designium** [GoogleCloudPlatform/gcloud-ruby#742]
I'm trying to do OCR with gcloud but I can't find how to do it.

**Comment by quartzmo** [comment]
Use the gcloud-ruby [support for Cloud Vision API](http://www.rubydoc.info/gems/gcloud/Gcloud/Vision). Either use the general-purpose [Project#annotate](http://www.rubydoc.info/gems/gcloud/Gcloud/Vision/Project#annotate-instance_method) method with the `text` flag, or use the special-purpose [Image#text](http://www.rubydoc.info/gems/gcloud/Gcloud/Vision/Image#text-instance_method) convenience method.

**Comment by designium** [comment]
I tried the following based on what I found from the source code of gcloud-ruby:

  gcloud = Gcloud.new [credentials]
  vision = gcloud.vision
  img = vision.image "IMAGE.JPG"
  txt = img.text

The system keeps hanging on irb. I tried using the landmark example and it happens the same, so not sure if the server has replied to my computer but the response is lost somewhere.

**Comment by quartzmo** [comment]
I will try it myself within the next 30 minutes. It may simply be a question of availability. I have noticed in the past that sometimes there are periods where requests time out. Let me know if it starts working for you.

**Comment by quartzmo** [comment]
@designium It works for me right now, using this image from the project's acceptance tests. Note that I am using environment variables for my credentials, and a `console` rake task included in the project, which initializes the top-level Gcloud object.

```sh
Christophers-MacBook-Air:gcloud-ruby quartzmo$ bundle exec rake console
irb(main):001:0> vision = gcloud.vision
=> #<Gcloud::Vision::Project:0x007fa09f21aa10 @connection=Gcloud::Vision::Connection(bustling-kayak-91516)>
irb(main):002:0> image = vision.image "./acceptance/data/text.png"
=> #<Gcloud::Vision::Image (?PNG

IHDR...)>
irb(main):003:0> text = image.text
=> #<Text text: "Google Cloud Client Library for Ruby an idiomatic, intuitive, and\nnatural way for Ruby developers to integrate with Google Cloud\nPlatform services, like Cloud Datastore and Cloud Storage.\n", locale: "en", bounds: 4, words: 28>
```

**Comment by designium** [comment]
Thanks, quartzmo.

So I left the commands on without doing ctrl+z to stop the processes and after more than 10 minutes!!! they returned the results.

Is that normal or expected behavior? I mean, if I create an app with that kind of response time, I'm doomed.

**Comment by designium** [comment]
Just saw your message now. 

I did some network test and I realized that my current upload speed is at 0.30 Mbps, maybe that's the issue.

Thanks again, quartzmo.

**Comment by quartzmo** [comment]
No problem! 

Anyway, how big are your files? There are some guidelines here:

https://cloud.google.com/vision/docs/image-best-practices#image_sizing

If they are a lot bigger than 1024 x 768, maybe you can do some preprocessing?

**Comment by designium** [comment]
The file I was testing is about 2448 × 3264 with 2.6MB.

What is the recommendation for preprocessing? Should I use Imagemagick or Google has something for preprocessing the image? Or do you recommend something else?

I found Imagmagick kind of bulky and then I tried the mini-magick which is a bit better in terms of memory processing but it's not 2016-ish. Most image processing tools are old guard.

**Comment by quartzmo** [comment]
Personally I have only ever used Imagemagick. I don't know of anything else to recommend. But if you (or any future reader of this issue) find something better, please post it here!

**Comment by designium** [comment]
Just FYI: gcloud-ruby ahead of gcloud-python:

https://github.com/GoogleCloudPlatform/gcloud-python/issues/1896#issuecomment-228230869
