### ISSUE TITLE
vision API runs all features unless one is set to `true`

### ISSUE THREAD

**Issue by Temikus** [GoogleCloudPlatform/gcloud-ruby#744]
I noticed a behaviour that the features I don't need don't get deselected unless one of them is set to true:
```
[28] pry(main)> annotations = vision.annotate photo, faces: false, logos: false, text: false, safe_search: false
=> #<Gcloud::Vision::Annotation (faces: 1, landmarks: 0, logos: 0, labels: 5, text: true, safe_search: true, properties: true)>
[29] pry(main)> annotations = vision.annotate photo, faces: false, labels: true, logos: false, text: false, safe_search: false
=> #<Gcloud::Vision::Annotation (faces: 0, landmarks: 0, logos: 0, labels: 5, text: false, safe_search: false, properties: false)>
```

**Comment by jgeewax** [comment]
I think this is on purpose -- the idea being if you call `annotate`, you want all annotations. Unless you specify certain annotations (ie, faces only). Otherwise you're trying to annotate an image with no annotations, which is a no-op.. right?

Or are we missing an important point ?

**Comment by Temikus** [comment]
@jgeewax Thanks for looking into this!

The important point here is that I called annotation with `faces: false` but it still made the request and, ofc., billed me for it. IMO this should not be so. I fully accept I may be missing something here too.

**Comment by blowmage** [comment]
Hi @Temikus, thanks for using gcloud-ruby and opening this issue!

The behavior of `Gcloud::Vision::Project#annotate` is to run all features unless one or more are selected. The [documentation states](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.11.0/gcloud/vision/project?method=annotate-instance):

> If no options for features are provided, all image detection features will be performed, with a default of 10 results for faces, landmarks, logos, and labels. If any feature option is provided, only the specified feature detections will be performed. Please review Pricing before use, as a separate charge is incurred for each feature performed on an image.

(The count in the docs is wrong. The default is actually 100. We will get that corrected.)

So your first example of:

```ruby
annotations = vision.annotate photo, faces: false, logos: false, text: false, safe_search: false
```

sends the following JSON to the API to request all features:

```javascript
[
  {
    "image": { "content": "..." },
    "features": [
      { "type": "FACE_DETECTION", "maxResults": 100 },
      { "type": "LANDMARK_DETECTION", "maxResults": 100 },
      { "type": "LOGO_DETECTION", "maxResults": 100 },
      { "type": "LABEL_DETECTION", "maxResults": 100 },
      { "type": "TEXT_DETECTION", "maxResults": 1 },
      { "type": "SAFE_SEARCH_DETECTION", "maxResults": 1},
      { "type": "IMAGE_PROPERTIES", "maxResults": 1 }
    ],
    "imageContext": null
  }
]
```

Your second example specifies the `labels` feature:

```ruby
annotations = vision.annotate photo, faces: false, labels: true, logos: false, text: false, safe_search: false
```

and as such only the label feature is sent to the API:

```javascript
[
  {
    "image": { "content": "..." },
    "features": [
      { "type": "LABEL_DETECTION", "maxResults": 100 }
    ],
    "imageContext": null
  }
]
```

So with this request you specified `faces: false` and that feature was not requested of the Vision API. Therefore you should not have been billed for it. I've run many, many combinations of arguments on `#annotate` and I can't make it send the feature to the Vision API (which is where the billing happens). I don't know how you were billed for a feature you did not specify. Can you verify you are being billed in this circumstance?

----------

I think part of the confusion here may be how the annotation object is shown when inspected. An empty annotation lists all of the features, even though the annotation object doesn't contain any of them:

```
#<Gcloud::Vision::Annotation (faces: 0, landmarks: 0, logos: 0, labels: 0, text: false, safe_search: false, properties: false)>
```

Unfortunately this representation of the object doesn't show what was requested, only the data available. We could change this representation so it only shows the features that have data:

```ruby
vision.annotate photo # run all features
=> #<Gcloud::Vision::Annotation (faces: 1, labels: 5, text: true, safe_search: true, properties: true)>
vision.annotate photo, labels: true
=> #<Gcloud::Vision::Annotation (labels: 5)>
```

**Comment by Temikus** [comment]
@blowmage Thanks for looking into this. 

I've re-read the docs and it seems that I made a logical error, assuming that the arguments work both ways, not only as inclusive arguments, but as exclusive (`false`) as well.

I think I may not be the only one to run into this issue, however, looking through the code, I do not see a more elegant way to do it either, so I you can close this as WAI.

**Comment by blowmage** [comment]
Documentation updated in #749.

**Comment by quartzmo** [comment]
@blowmage Can we close this?

**Comment by blowmage** [comment]
Looks like it.
