### ISSUE TITLE
Update mentions of "Cloud Logging" to "Stackdriver Logging"

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#750]
The [official docs](https://cloud.google.com/logging/docs) now use "Stackdriver Logging" in all API descriptions. For example:

>  If omitted, Stackdriver Logging will use the time the log entry is received.

Update all gcloud-ruby Logging docs to match.

**Comment by quartzmo** [comment]
@jgeewax Should we do this?

**Comment by jgeewax** [comment]
I'm +1 to that. Can you make a ticket on gcloud-common so that others can do similarly ?

**Comment by quartzmo** [comment]
This is gcloud-ruby issue for GoogleCloudPlatform/gcloud-common#147.
