### ISSUE TITLE
Rename Pubsub::Topic::Batch to Pubsub::Topic::Updater

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#756]

**Comment by blowmage** [comment]
The more I think of this, the more I think Updater is not correct. A better name is `Topic::Publisher` since the only thing this object does is publish. It does not represent multiple changes to the Topic the way an `Updater` does in other services.

@quartzmo Thoughts?

**Comment by quartzmo** [comment]
Publisher seems better than Updater, I agree.
