### ISSUE TITLE
Bug: Cors::Rule freezing GAPI object values

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#771]
The Cors::Rule object is using the GAPI object's arrays by reference,
and when the rule object freezes it is partially freezing the GAPI object.
Be sure to dup the arrays when creating a Cors::Rule from a GAPI object,
and when createing a GAPI object from a Cors::Rule object.

**Comment by quartzmo** [comment]
Good find! Way to go.
