### ISSUE TITLE
Documentation links to master instead of latest release version

### ISSUE THREAD

**Issue by dbenjamin57** [GoogleCloudPlatform/gcloud-ruby#777]
This whole block of code doesnt work:

require "gcloud"

gcloud = Gcloud.new
bigquery = gcloud.bigquery
dataset = bigquery.dataset "my_dataset"

schema_fields = [
  Gcloud::Bigquery::Schema::Field.new(
    "first_name", :string, mode: :required),
  Gcloud::Bigquery::Schema::Field.new(
    "cities_lived", :record, mode: :repeated
    fields: [
      Gcloud::Bigquery::Schema::Field.new(
        "place", :string, mode: :required),
      Gcloud::Bigquery::Schema::Field.new(
        "number_of_years", :integer, mode: :required),
      ])
]
table = dataset.create_table "my_table", fields: schema_fields

**Comment by quartzmo** [comment]
@dbenjamin57 Thanks for reporting this, I'll give it a try myself today. When you write "doesn't work", what do you mean? Do you get an error? Can you paste in a backtrace?

**Comment by dbenjamin57** [comment]
NameError: uninitialized constant Gcloud::Bigquery::Schema

**Comment by quartzmo** [comment]
@dbenjamin57 Thanks a lot. I couldn't reproduce this on my first try, but I will continue to investigate. Which version of gcloud-ruby are you using?

**Comment by dbenjamin57** [comment]
I am using 0.11. 

Just noticed that you removed this example in the new version of the documentation:
http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.11.0/Gcloud/Bigquery/Dataset.html

In master (the doc version that opens initially) it still exists: 
http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Bigquery/Dataset.html

**Comment by quartzmo** [comment]
I can also reproduce this in `v0.11.0`.

```sh
irb(main):001:0> bigquery = gcloud.bigquery
=> #<Gcloud::Bigquery::Project:0x007ff4753ae910 @connection=Gcloud::Bigquery::Connection(bustling-kayak-91516)>
irb(main):002:0> Gcloud::Bigquery::Schema::Field.new
NameError: uninitialized constant Gcloud::Bigquery::Schema
	from (irb):2
	from /Users/quartzmo/code/google/codez/gcloud-ruby/rakelib/console.rake:27:in `block in <top (required)>'
```

**Comment by quartzmo** [comment]
Using the big, red "Read the Docs" button at https://googlecloudplatform.github.io/gcloud-ruby/ should always bring you to the latest version instead of master, in case that helps.

**Comment by dbenjamin57** [comment]
Well.. take a look at your documentation - it leads to:
http://googlecloudplatform.github.io/gcloud-ruby/docs/master/Gcloud/Bigquery.html

**Comment by quartzmo** [comment]
It's not that it "still exists" in master and was removed. The current version `v0.11.0` is *older* than master. `Gcloud::Bigquery::Schema` was introduced in [this recent commit](https://github.com/GoogleCloudPlatform/gcloud-ruby/commit/8817fd47e7ce270f5f5334dbb729cc2c25922d2e).

Which link did you use to reach the documentation for master? We are trying hard to direct to the latest version by default, but it seems there are always loose ends.

**Comment by dbenjamin57** [comment]
Just below the bigquery section (and beneath the authentication) in the
main documentation there's a link to the documentation.
ᐧ

**Comment by quartzmo** [comment]
@dbenjamin57 Great, thank you for pointing that out! I'm going to leave this issue open until we can figure out what to do about those links, which continue to link to `master` even if you switch the version in GitHub.

Really appreciate your help!

**Comment by quartzmo** [comment]
@dbenjamin57 We are going to update these Readme links to point to the latest release, rather than master. Thanks again.
