### ISSUE TITLE
uninitialized constant Gcloud::Pubsub::Subscription::Hurley

### ISSUE THREAD

**Issue by mpcm** [GoogleCloudPlatform/gcloud-ruby#811]
Hit this just a few moments ago:

`rescued...
uninitialized constant Gcloud::Pubsub::Subscription::Hurley`

specific line with issue: https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/pubsub/subscription.rb#L237

general search link: https://github.com/GoogleCloudPlatform/gcloud-ruby/search?utf8=%E2%9C%93&q=Hurley

Not sure if this is just left over and still needs removing, or needs other special handling....

**Comment by mpcm** [comment]
For those hitting this, looks like requiring hurley myself is a valid work around...
`require 'hurley'`

**Comment by blowmage** [comment]
Hi @mpcm, thanks for opening this issue. The problem is that `#pull` is rescuing the wrong class. The latest Google API Client the dependency switched from Faraday to Hurley, but Pub/Sub is using gRPC, so the rescue is all sorts of wrong. We'll try to get a fix released for this today.

**Comment by quartzmo** [comment]
@mpcm Thanks for catching this! I'm merging @blowmage's fix now and will release it soon (hopefully within an hour or so.)

**Comment by mpcm** [comment]
Thanks.
