### ISSUE TITLE
Automate Individual Package Documentation Build

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#830]
With the switch from monolithic gem to individual gems, we need to replace the previous build process that identifies new releases and generates the documentation. The new mechanism should be aware of package-specifc git tags (google-cloud-datastore:v1.2.0 vs. v1.2.0) and create a new version for the appropriate gem.

**Comment by quartzmo** [comment]
@blowmage To be clear, when a new version of an individual gem is released, a new version of the `gcloud-common` "bundled" gem will also be released, and new documentation published for both the individual and the bundled gems? 

See [previous discussion on gcloud-common](https://github.com/GoogleCloudPlatform/gcloud-common/pull/157#issuecomment-237376667):

> when a subpackage gets a feature, our umbrella package gets a feature... which is a feature, so we should tag it as one.
