### ISSUE TITLE
Update gcloud-ruby/google-cloud-datastore to use the v1 API

### ISSUE THREAD

**Issue by eddavisson** [GoogleCloudPlatform/gcloud-ruby#835]
The v1 API is now available.

The protos are identical (just a different package name). The only behavioral change is captured in the release notes:
https://cloud.google.com/datastore/release-notes

**Comment by quartzmo** [comment]
Hooray for `v1`! Thanks @eddavisson.

Nice to see these changes:

> Attempting to insert an entity that already exists will return error code ALREADY_EXISTS. In v1beta3, it returned INVALID_ARGUMENT.
> Attempting to update an entity that does not exist will return error code NOT_FOUND. In v1beta3, it returned INVALID_ARGUMENT.
