### ISSUE TITLE
issues with README instructions and gcloud gem

### ISSUE THREAD

**Issue by apolcyn** [GoogleCloudPlatform/gcloud-ruby#839]
I think this is related to https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/789 and https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/837. 

The main README on the github page here says to `gem install gcloud`, and then `require google/cloud`.

Found that I needed to do

```
require 'gcloud'
...
gcloud = Gcloud.new
```

in order to use the package.

**Comment by quartzmo** [comment]
@apolcyn The library is in transition to a new namespace in `master`. However, if you use the latest release (`0.12.2`), you should indeed use `require "gcloud"`. If you switch [the version in GitHub to the latest release](https://github.com/GoogleCloudPlatform/gcloud-ruby/tree/v0.12.2), the docs correctly show this.

**Comment by quartzmo** [comment]
If you go to the docs site:

https://googlecloudplatform.github.io/gcloud-ruby/

and click the "Read the Docs" button, it should always bring you to the correct documentation version for the latest release (not `master`.) The examples here also display `require "gcloud"`.
