### ISSUE TITLE
Is the gem working? 

### ISSUE THREAD

**Issue by quekshuy** [GoogleCloudPlatform/gcloud-ruby#84]
I'm trying to use this gem but so far am unsuccessful with trying to load it. 

I installed as usual. I used sudo, since this is the system installation of ruby.

In irb I do this and it says cannot load such file:

```
irb(main):001:0> require 'gcloud'
LoadError: cannot load such file -- gcloud
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
irb(main):002:0>
```

I only have one ruby installation and that's the system one. 

Could it be the gem is broken? If it isn't then I apologize for submitting this issue and I'll try again.

**Comment by quekshuy** [comment]
Sorry it's my own error.

**Comment by VincentVanGoat** [comment]
Hey what was the error?

**Comment by quartzmo** [comment]
@quekshuy Can you please post your error and solution? It may help @VincentVanGoat resolve #229.

**Comment by quekshuy** [comment]
Hello,

Sorry for the delay in responding.

In an older version of the gem, the requires weren’t working. I updated to
a later version of the gem (0.2.0) and it works now. Is it happening with
the latest version for you @VincentVanGoat?

**Comment by VincentVanGoat** [comment]
Yes. I found that in my project as well. It is fixed now! Thanks!

**Comment by quekshuy** [comment]
No problem. Again, sorry I didn’t reply sooner!
