### ISSUE TITLE
Manage Bucket Versioning

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#91]
Support management of a bucket's versioning setting. Allow getting values using a well named method.

```ruby
bucket.versioning #=> false
```

Allow setting a new value using a setter method.

```ruby
bucket.versioning = true
```

**Comment by jgeewax** [comment]
Are we going to make these one set of attributes, or a method for each one? ie, 

```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
bucket.set_website_config :index=>'index.html, :not_found=>'404.html'
```

or
```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
bucket.update :website => {:index=>'index.html, :not_found=>'404.html'}
```

**Comment by blowmage** [comment]
Closing this issue. New issues are being created for each of these features.
