### ISSUE TITLE
Manage File Attributes

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#92]
Support management (create, read, update) of the following:

- [x] contentType
- [x] cacheControl
- [x] contentDisposition
- [x] contentEncoding
- [x] contentLanguage

In addition, support create and read only of the following:

- [x] md5Hash
- [x] crc32c

Allow providing values during file creation:

```ruby
bucket.create_file "hello.txt", cache_control: "private, max-age=0, no-cache"
```
Allow getting values using a well named method.

```ruby
file.content_type #=> "text/ext"
```

Allow setting new values using a setter method that makes an API call.

```ruby
file.content_type = "text/ext"
```

Making multiple changes in a single API call will be addressed in a future issue to add the update method which can make multiple at the same time:

```ruby
file.update do |f|
  f.content_type = "text/ext"
  f.content_encoding = "gzip"
  f.metadata["title"] = "Goodbye cruel world!"
end
```

**Comment by jgeewax** [comment]
What's the code I'd write to set these things? Would it be one method or separate methods?

One idea that seems good is....

```ruby
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
file = bucket.find_file "path/to/my-file.ext"

file.set_content_type "text/plain" # Makes an API request
file.get_content_type # Makes an API request, returns text/plain
# Similarly for cache-control and content-*

file.set_metadata "key" "value" # Push up a single piece of metadata?
file.set_metadata {:key=>"value", :key2=>"value2"} # Push up all of the meta data in one go?
file.get_metadata # Get the entire hash of metadata?
file.get_metadata "key" # Get a single piece of metadata?
```

**Comment by blowmage** [comment]
file.content_type #=> "text/plain"
file.content_type "text/html"

**Comment by jgeewax** [comment]
Is that ruby-ish to have things look like properties but actually make API requests?

**Comment by blowmage** [comment]
Reading the properties wouldn't make API requests, only updating them. Another option is make changes to a file object and then call `.save` to make all the calls to the API.

```ruby
# Update the content type in the object
file.content_type = "text/html"
# Update metadata in the object
file.metadata["foo"] = "baz"
# Calls the API to persist changes
file.save
```

**Comment by jgeewax** [comment]
Hmm the `.save` style means that there might be some state hanging around... I'm -1 to that, but I also know very little about Ruby...

Are read-only properties with setter methods a reasonable idea ?

**Comment by blowmage** [comment]
Yes, that is where I was going. The common idiom for setter methods is `file.content_type = val` instead of `file.set_content_type(val)`.

**Comment by jgeewax** [comment]
Also - if the reads don't make an API request, there's a chance of stale data in long-lived processes, right? So we'd need a way to force a reload of all that data too.

@ryanseys , How do we handle the File properties (ie, file.content_type) in Node.js?

**Comment by blowmage** [comment]
IIRC, all file attributes are acquired when the file data is retrieved from the API.

```ruby
require "gcloud/storage"
storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
file = bucket.find_file "path/to/my-file.ext"
file.content_type #=> "file/ext" # No additional API call required.
```

**Comment by jgeewax** [comment]
But 

```ruby
file.content_type = "newfile/newext"
```

Would make an API call, correct?

**Comment by jgeewax** [comment]
In the AWS version of this (for S3), note that `content_type` is read-only... However in S3, objects seem to be immutable... so to update metadata, you copy to a new object (changing the metadata at copy-time) and delete the old object (or copy to/from the same name? ... it's not entirely clear).

**Comment by blowmage** [comment]
yes, the direction I've been going has been to make the API call when setting the property.

Another common idiom is to use "bang methods" for methods that mutate state, have side effects, or are dangerous in some way.

```ruby
# API call is made here
file.acl.public!
```

We could do something similar for managing these attributes:

```ruby
# API call is made here
file.content_type! "text/ext"
```

Or, we could isolate the mutable state to an `update` method call that yields a mutable object to the block.

```ruby
file.update do |f|
  f.content_type = "text/ext"
  f.metadata["foo"] = "baz"
end # API calls are made for any changed values when block finishes
```

**Comment by jgeewax** [comment]
I think the latter (`file.update` block) is really nice, but a lot of extra typing if you just want to set one thing (ie, `content_type`). Is it crazy to offer both the first (bang-style) and the second (block-style) ?

**Comment by blowmage** [comment]
Not crazy, no. I also prefer the `update` method, but like the convenience of the bang methods. The benefit of `update` is that users could change all the attributes and only make one call to the [update API](https://cloud.google.com/storage/docs/json_api/v1/objects/update).

A simple implementation for the bang methods would be:

```ruby
def content_type! new_content_type
  update do |f|
    f.content_type = new_content_type
  end
end
```

These tradeoffs are what I was hung up on, BTW. Talking through them really helps. Thanks.

**Comment by jgeewax** [comment]
No problem -- I think it'd be cool to offer the bang-style methods (implemented as you mentioned) for the one-off changes, and mention in the docs that if you're doing multiple changes at once, we have a zippier way of doing that... (`.update do |f|`).

**Comment by jgeewax** [comment]
@blowmage : Can you update the description of what we're going to do based on this thread?

**Comment by blowmage** [comment]
Updated! :sunglasses:

**Comment by ryanseys** [comment]
> How do we handle the File properties (ie, file.content_type) in Node.js?

IIRC we get the content type for a file based on its extension using a mimetype library which maps extensions to mime types. Otherwise we fallback to `application/octet-stream` as the type.

**Comment by Capstan** [comment]
Can we rather suggest clients integrate with something like [Transaction::Simple](http://www.rubydoc.info/gems/transaction-simple/1.4.0.2) or an analog that calls a hidden/utility method that allows batch update of metaadata?

**Comment by blowmage** [comment]
Moved metadata to a separate issue.

**Comment by quartzmo** [comment]
I think it probably makes sense to add a read method for `timeCreated`, since Bucket supports it and the Object representation has it.

**Comment by blowmage** [comment]
Agreed.

**Comment by quartzmo** [comment]
@blowmage Should these 5 attributes also be options in `Bucket#create_file`? As far as I can tell they are writable on File insert. Should we add that to this issue?

**Comment by blowmage** [comment]
Yes, they should be available on create and part of this issue.

**Comment by quartzmo** [comment]
In that case, I think we should also add  `md5Hash` and `crc32c` as  `Bucket#create_file` options. We can also add File attributes readers for them, although I don't think updating them should supported given their purpose:

> If your application has already computed the object’s MD5 or CRC32c prior to starting the upload, you can supply it with the upload request, and Google Cloud Storage will only create the object if the hash you provided matches the value we calculated.

-- [Hashes and ETags: Best Practices](https://cloud.google.com/storage/docs/hashes-etags)

**Comment by blowmage** [comment]
Makes sense. I didn't know this.

**Comment by quartzmo** [comment]
I'll update the issue description for posterity.

**Comment by quartzmo** [comment]
@blowmage The new behavior will be that a user-supplied `content-type` will override the one discovered in `mime_type_for`:

```ruby
options[:content_type] ||= mime_type_for(local_path)
```

From this [commented-out line](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.0/lib/gcloud/storage/connection.rb#L217), I think maybe you already had this planned for `Connection#insert_file_resumable`. Is it also ok for `Connection#insert_file_multipart`?

**Comment by blowmage** [comment]
@quartzmo Yeah, the intention is to allow the provided content type to override the discovered content type. That behavior should be the same for both resumable and multipart uploads.
