### ISSUE TITLE
Support PubSub's v1beta2 API

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#98]
Looks like [v1beta2 was just released](https://groups.google.com/d/msg/cloud-pubsub-lp/VClP6U8gTWU/Q1Kd438lmKkJ). The gcloud-ruby implementation in process is for v1beta1, and should switch to support v1beta2 instead.

**Comment by blowmage** [comment]
@jgeewax We should switch versions, yes?

**Comment by jgeewax** [comment]
I suspect that v1beta2 will be much closer to the final `v1`, so my guess is yes.

**Comment by blowmage** [comment]
Yes, the mailing list has indicated that there are no changes planned between v1beta2 and v1.
